import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Auto-generated by the Workflow SDK build step (gitignored).
    "app/.well-known/workflow/**",
    // Pre-compiled MakeCode Arcade game JS files (generated, not hand-edited).
    "public/arcade/games/**",
    // Vendored MakeCode simulator (generated, not hand-edited).
    "public/simulator/**",
  ]),
]);

export default eslintConfig;
