import type { ExtensionDoc } from "@/content/extensions/types";

export const raycastingPxtExtension: ExtensionDoc = {
  owner: "The-Code-Zone",
  repo: "Raycasting-pxt-extension",
  displayName: "Raycasting 3D Render",
  packageSlug: "github:The-Code-Zone/Raycasting-pxt-extension",
  description: "Transforms flat MakeCode Arcade tilemaps into first-person 3D games with height dimensions, directional sprite animations, and custom cameras.",
  tools: [
    {
      slug: "create-animations",
      title: "create animations",
      blockId: "create_animation",
      blockString: "interval$frameInterval=timePicker animates:$frames1=animation_editor|| $frames2=animation_editor $frames3=animation_editor $frames4=animation_editor",
      group: "Animate",
      weight: 100,
      problem: "You want a character or enemy sprite to look realistic in 3D by changing its animation depending on whether the player sees it from the left, front, right, or back.",
      whatItDoes: "Creates a multi-directional animation set from lists of frames. Up to 4 directional animation sequences can be defined, corresponding to looking at the sprite from different angles.",
      parameters: [
        { name: "frameInterval", type: "number", default: "150", meaning: "Time in milliseconds between animation frame changes." },
        { name: "frames1", type: "Image[]", default: "", meaning: "Image list for the first side (starts from the left view)." },
        { name: "frames2", type: "Image[]", default: "", meaning: "Optional image list for additional directional angles." },
        { name: "frames3", type: "Image[]", default: "", meaning: "Optional image list for a third direction view." },
        { name: "frames4", type: "Image[]", default: "", meaning: "Optional image list for a fourth direction view." },
      ],
      returns: { type: "Animations", meaning: "An animation container object ready to apply to 3D sprites." },
      example: "let anim = Render.createAnimations(150, [img`.`])",
    },
    {
      slug: "get-rc-render-instance",
      title: "get raycasting render instance",
      blockId: "rcRender_getRCRenderInstance",
      blockString: "raycasting render",
      group: "Instance",
      weight: 100,
      problem: "You need direct low-level access to the internal raycasting engine to modify core rendering properties programmatically.",
      whatItDoes: "Returns the global raycasting engine manager instance.",
      parameters: [],
      returns: { type: "RayCastingRender", meaning: "The main 3D raycasting renderer object." },
      example: "let renderer = Render.getRCRenderInstance()",
    },
    {
      slug: "get-render-sprite-variable",
      title: "myself sprite variable",
      blockId: "rcRender_getRenderSpriteVariable",
      blockString: "myself sprite",
      group: "Instance",
      weight: 99,
      problem: "You want to set up your player's initial spawn point, velocity, or collision reactions as the first-person camera viewpoint.",
      whatItDoes: "Retrieves the player sprite that represents the camera viewpoint in the 3D world.",
      parameters: [],
      returns: { type: "Sprite", meaning: "The player sprite holding the camera view point." },
      example: `let mySprite = Render.getRenderSpriteVariable()
mySprite.setPosition(80, 80)`,
    },
    {
      slug: "get-render-sprite-instance",
      title: "myself sprite instance",
      blockId: "rcRender_getRenderSpriteInstance",
      blockString: "myself sprite",
      group: "Instance",
      weight: 98,
      problem: "You need to reference the player camera sprite directly inside an event handler to check its position or check collisions.",
      whatItDoes: "Returns the player sprite object acting as the 3D view point source.",
      parameters: [],
      returns: { type: "Sprite", meaning: "The player sprite representing the current view point." },
      example: "Render.getRenderSpriteInstance().setPosition(100, 100)",
    },
    {
      slug: "toggle-view-mode",
      title: "toggle view mode",
      blockId: "rcRender_toggleViewMode",
      blockString: "toggle current view mode",
      group: "Basic",
      weight: 90,
      problem: "You want players to press a button to switch between a top-down 2D map view and the 3D first-person perspective.",
      whatItDoes: "Switches the current display mode between standard 2D tilemap view and 3D raycasting view.",
      parameters: [],
      example: `controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.toggleViewMode()
})`,
    },
    {
      slug: "set-ceiling-tilemap",
      title: "set ceiling tilemap",
      blockId: "rc_Render_setCeilingTilemap",
      blockString: "set ceiling as $tilemap",
      group: "Basic",
      weight: 89,
      problem: "You are building an indoor dungeon or tunnel and want an overhead ceiling tilemap rendered above the player's head.",
      whatItDoes: "Assigns a tilemap to be drawn overhead as a 3D ceiling. The ceiling tilemap must have matching dimensions to the ground tilemap.",
      parameters: [
        { name: "tilemap", type: "tiles.TileMapData", default: "", meaning: "The tilemap data to render as a ceiling overhead." },
      ],
      example: "Render.setCeilingTilemap(tilemap`level1`)",
    },
    {
      slug: "is-view-mode",
      title: "is view mode",
      blockId: "rcRender_isViewMode",
      blockString: "current is $viewMode",
      group: "Basic",
      weight: 88,
      problem: "You want to run specific gameplay logic or draw custom UI elements only when the game is in 3D mode rather than 2D mode.",
      whatItDoes: "Checks whether the game is currently set to a specific view mode (2D TileMap Mode or 3D Raycasting Mode).",
      parameters: [
        { name: "viewMode", type: "ViewMode", default: "", meaning: "The view mode to test (ViewMode.raycastingView or ViewMode.tilemapView)." },
      ],
      returns: { type: "boolean", meaning: "true if the current view mode matches the argument." },
      example: `if (Render.isViewMode(ViewMode.raycastingView)) {
    console.log("In 3D view")
}`,
    },
    {
      slug: "set-view-mode",
      title: "set view mode",
      blockId: "rcRender_setViewMode",
      blockString: "set view mode $viewMode",
      group: "Basic",
      weight: 87,
      problem: "You want to force the camera into standard 2D mode during map transitions, cutscenes, or inventory menus.",
      whatItDoes: "Explicitly sets the active rendering perspective to either 3D raycasting view or 2D tilemap view.",
      parameters: [
        { name: "viewMode", type: "ViewMode", default: "", meaning: "The target view mode to set." },
      ],
      example: "Render.setViewMode(ViewMode.tilemapView)",
    },
    {
      slug: "get-attribute",
      title: "get attribute",
      blockId: "rcRender_getAttribute",
      blockString: "get %attribute",
      group: "Basic",
      weight: 83,
      problem: "You need to read the current field-of-view angle or camera vector direction to spawn projectiles in the direction the player is looking.",
      whatItDoes: "Reads global 3D render settings such as view direction vectors (dirX, dirY), field-of-view (fov), or wall Z-scale height.",
      parameters: [
        { name: "attr", type: "attribute", default: "", meaning: "The rendering property to read (dirX, dirY, fov, or wallZScale)." },
      ],
      returns: { type: "number", meaning: "The numeric value of the queried render attribute." },
      example: "let currentFov = Render.getAttribute(Render.attribute.fov)",
    },
    {
      slug: "set-attribute",
      title: "set attribute",
      blockId: "rcRender_setAttribute",
      blockString: "set %attribute = %value",
      group: "Basic",
      weight: 82,
      problem: "You want to create a sniper scope effect that zooms the camera in by lowering the field of view.",
      whatItDoes: "Updates global 3D rendering parameters like FOV or wall Z-height scale factor.",
      parameters: [
        { name: "attr", type: "attribute", default: "", meaning: "The attribute setting to adjust." },
        { name: "value", type: "number", default: "", meaning: "The new numeric value for the attribute." },
      ],
      example: "Render.setAttribute(Render.attribute.fov, 0.33)",
    },
    {
      slug: "get-default-fov",
      title: "default fov",
      blockId: "rcRender_getDefaultFov",
      blockString: "defaultFov",
      group: "Basic",
      weight: 81,
      problem: "You temporarily altered the player's field of view for a power-up effect and want to reset it back to normal when the effect ends.",
      whatItDoes: "Returns the default field-of-view ratio used by the 3D raycasting engine.",
      parameters: [],
      returns: { type: "number", meaning: "The default FOV numeric constant." },
      example: "Render.setAttribute(Render.attribute.fov, Render.getDefaultFov())",
    },
    {
      slug: "set-view-angle-in-degree",
      title: "set view angle in degrees",
      blockId: "rcRender_setViewAngleInDegree",
      blockString: "set view angle$angle",
      group: "Basic",
      weight: 80,
      problem: "You want the player camera to instantly snap to face North, East, South, or West when entering a new room.",
      whatItDoes: "Rotates the player's view direction camera to an absolute angle specified in degrees (0° to 360°).",
      parameters: [
        { name: "angle", type: "number", default: "90", meaning: "The target viewing direction in degrees (0 = East, 90 = South, 180 = West, 270 = North)." },
      ],
      example: "Render.setViewAngleInDegree(180)",
    },
    {
      slug: "set-view-angle",
      title: "set view angle",
      blockId: "rcRender_setViewAngle",
      blockString: "set view angle by dirX%dirX and dirY%dirY",
      group: "Basic",
      weight: 79,
      problem: "You want the 3D camera angle to point directly toward a target point in the tilemap using directional vector coordinates.",
      whatItDoes: "Sets the viewing angle of the camera based on X and Y direction values.",
      parameters: [
        { name: "dirX", type: "number", default: "", meaning: "X vector component of the look direction." },
        { name: "dirY", type: "number", default: "", meaning: "Y vector component of the look direction." },
      ],
      example: "Render.setViewAngle(0, -1)",
    },
    {
      slug: "set-z-offset",
      title: "set z offset",
      blockId: "rcRender_setZOffset",
      blockString: "set Sprite %spr=variables_get(mySprite) floating %offset pixels|| duration $duration=timePicker|ms ",
      group: "Dimension Z",
      weight: 77,
      problem: "You want a hovering drone enemy or floating coin to stay hovering above ground level in 3D space.",
      whatItDoes: "Sets the steady floating height (Z offset) of a sprite above or below the ground level.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite to raise or lower." },
        { name: "offset", type: "number", default: "8", meaning: "Floating height offset in pixels (positive lifts up, negative drops down)." },
        { name: "duration", type: "number", default: "0", meaning: "Transition duration in milliseconds to move to the target height." },
      ],
      example: `let coin = sprites.create(img\`.\`, SpriteKind.Food)
Render.setZOffset(coin, 12, 200)`,
    },
    {
      slug: "set-sprite-attribute",
      title: "set sprite attribute",
      blockId: "rcRender_setSpriteAttribute",
      blockString: "set Sprite %spr=variables_get(mySprite) %attribute = %value",
      group: "Dimension Z",
      weight: 75,
      problem: "You want to manually change a sprite's vertical velocity or vertical gravity acceleration in 3D space.",
      whatItDoes: "Sets vertical motion parameters along the Z dimension for a sprite, including Z offset, Z position, Z velocity, or Z acceleration.",
      parameters: [
        { name: "spr", type: "Sprite", default: "mySprite", meaning: "The target sprite." },
        { name: "attr", type: "RCSpriteAttribute", default: "", meaning: "The Z motion property to change (ZOffset, ZPosition, ZVelocity, or ZAcceleration)." },
        { name: "value", type: "number", default: "", meaning: "The value to set." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Render.setSpriteAttribute(mySprite, RCSpriteAttribute.ZVelocity, 50)`,
    },
    {
      slug: "get-sprite-attribute",
      title: "get sprite attribute",
      blockId: "rcRender_getSpriteAttribute",
      blockString: "get Sprite %spr=variables_get(mySprite) %attribute",
      group: "Dimension Z",
      weight: 74,
      problem: "You want to check if a jumping player has hit the ground or reached maximum height.",
      whatItDoes: "Gets vertical motion properties of a sprite in the Z dimension (ZOffset, ZPosition, ZVelocity, or ZAcceleration).",
      parameters: [
        { name: "spr", type: "Sprite", default: "mySprite", meaning: "The target sprite to check." },
        { name: "attr", type: "RCSpriteAttribute", default: "", meaning: "The vertical attribute to inspect." },
      ],
      returns: { type: "number", meaning: "The value of the requested vertical attribute." },
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
let zPos = Render.getSpriteAttribute(mySprite, RCSpriteAttribute.ZPosition)`,
    },
    {
      slug: "is-sprites-overlap-z",
      title: "is sprites overlap z",
      blockId: "rcRender_isSpritesOverlapZ",
      blockString: "is sprites $sprite1=variables_get(mySprite) and $sprite2=variables_get(mySprite2) overlaps in Z dimension",
      group: "Dimension Z",
      weight: 71,
      problem: "You shot a projectile in a 3D level, but need to check if it actually hit a jumping enemy that might be flying above the bullet.",
      whatItDoes: "Determines whether two sprites overlap each other along the vertical Z axis. Combine this with normal overlap events to ensure full 3D collision.",
      parameters: [
        { name: "sprite1", type: "Sprite", default: "mySprite", meaning: "First sprite to test." },
        { name: "sprite2", type: "Sprite", default: "mySprite2", meaning: "Second sprite to test." },
      ],
      returns: { type: "boolean", meaning: "true if both sprites share overlapping height spaces in Z dimension." },
      example: `sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (sprite, otherSprite) {
    if (Render.isSpritesOverlapZ(sprite, otherSprite)) {
        otherSprite.destroy()
    }
})`,
    },
    {
      slug: "jump-with-height-and-duration",
      title: "jump with height and duration",
      blockId: "rcRender_jumpWithHeightAndDuration",
      blockString: "Sprite %spr=variables_get(mySprite) jump, with height $height duration $duration=timePicker|ms ",
      group: "Dimension Z",
      weight: 70,
      problem: "You want the player to jump over low obstacles when pressing a button, specifying the exact peak height and jump duration.",
      whatItDoes: "Makes a grounded sprite jump upward to a target peak pixel height and hang time before returning back down.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite that will perform the jump." },
        { name: "height", type: "number", default: "16", meaning: "Peak jump height in pixels." },
        { name: "duration", type: "number", default: "500", meaning: "Total duration of the jump animation in milliseconds." },
      ],
      example: `controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.jumpWithHeightAndDuration(Render.getRenderSpriteInstance(), 16, 500)
})`,
    },
    {
      slug: "jump",
      title: "jump",
      blockId: "rcRender_jump",
      blockString: "Sprite %spr=variables_get(mySprite) jump||, with speed $v=spriteSpeedPicker acceleration $a",
      group: "Dimension Z",
      weight: 68,
      problem: "You want realistic physical jumping behavior with customizable vertical speed and downward gravity.",
      whatItDoes: "Launches a standing sprite into a vertical jump using upward velocity and downward acceleration.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite that should jump." },
        { name: "v", type: "number", default: "60", meaning: "Initial upward vertical speed in pixels per second." },
        { name: "a", type: "number", default: "-250", meaning: "Downward acceleration (gravity) in pixels per second squared." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Render.jump(mySprite, 80, -300)`,
    },
    {
      slug: "move",
      title: "move",
      blockId: "rcRender_move",
      blockString: "Sprite %spr=variables_get(mySprite) move, with speed $v=spriteSpeedPicker|| acceleration $a",
      group: "Dimension Z",
      weight: 66,
      problem: "You want an airborne enemy or launching projectile to move vertically along the Z axis even while already in mid-air.",
      whatItDoes: "Applies immediate vertical velocity and acceleration to a sprite along the Z axis, regardless of whether it is currently standing on the ground.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "Target sprite to move vertically." },
        { name: "v", type: "number", default: "60", meaning: "Vertical speed in pixels per second." },
        { name: "a", type: "number", default: "-250", meaning: "Vertical acceleration in pixels per second squared." },
      ],
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
Render.move(enemy, 50, -200)`,
    },
    {
      slug: "moveWithController",
      title: "move with controller",
      blockId: "rcRender_moveWithController",
      blockString: "move with buttons velocity $v|| turn speed $va camera sway$cameraSway pixels",
      group: "Advanced",
      weight: 60,
      problem: "You want the player to move forward/backward with Up/Down buttons and turn the 3D viewing angle left/right with Left/Right buttons.",
      whatItDoes: "Binds arcade D-pad controller inputs to move the player viewpoint forward and backward while turning the 3D camera smoothly.",
      parameters: [
        { name: "v", type: "number", default: "2", meaning: "Forward and backward walking movement velocity." },
        { name: "va", type: "number", default: "3", meaning: "Turning rotational angle velocity." },
        { name: "cameraSway", type: "number", default: "", meaning: "Optional head-bobbing sway intensity in pixels while walking." },
      ],
      example: "Render.moveWithController(2, 3, 1)",
    },
    {
      slug: "takeover-scene-sprites",
      title: "takeover scene sprites",
      blockId: "rcRender_takeoverSceneSprites",
      blockString: "takeover sprites in scene",
      group: "Advanced",
      weight: 49,
      problem: "You spawned a new sprite mid-game, but it appears rendered flat on the 2D tilemap plane instead of inside the 3D world.",
      whatItDoes: "Forces the 3D renderer to immediately adopt all active scene sprites into the 3D raycasting pipeline.",
      parameters: [],
      example: `let spr = sprites.create(img\`.\`, SpriteKind.Enemy)
Render.takeoverSceneSprites()`,
    },
    {
      slug: "register-on-sprite-direction-update-handler",
      title: "register on sprite direction update handler",
      blockId: "rcRender_registerOnSpriteDirectionUpdateHandler",
      blockString: "run code when sprite $spr dirction updated to $dir",
      group: "Advanced",
      weight: 48,
      problem: "You want to run custom animation logic whenever a sprite's apparent direction relative to the camera changes.",
      whatItDoes: "Registers a callback event handler that runs whenever a sprite's viewing direction relative to the camera is recalculated.",
      parameters: [
        { name: "handler", type: "(spr: Sprite, dir: number) => void", default: "", meaning: "Function called with the updated sprite and normalized angle direction value (0 to 1)." },
      ],
      example: `Render.registerOnSpriteDirectionUpdateHandler(function (spr, dir) {
    console.log("Sprite direction updated")
})`,
    }
  ],
};
