import type { ExtensionDoc } from "@/content/extensions/types";

export const raycastingPxtExtension: ExtensionDoc = {
  owner: "The-Code-Zone",
  repo: "Raycasting-pxt-extension",
  displayName: "3D Raycasting Render",
  packageSlug: "github:The-Code-Zone/Raycasting-pxt-extension",
  description: "Transforms your 2D tilemap into a first-person 3D world with raycasting, directional sprite animations, and vertical jumping physics.",
  tools: [
    {
      slug: "create-animations",
      title: "create animations",
      blockId: "create_animation",
      blockString: "interval$frameInterval=timePicker animates:$frames1=animation_editor|| $frames2=animation_editor $frames3=animation_editor $frames4=animation_editor",
      group: "Animate",
      weight: 100,
      problem: "You want enemies and characters in your 3D game to face different directions (front, back, left, right) and animate as the player walks around them.",
      whatItDoes: "Creates a set of multi-directional walking animations. Directions start facing left and rotate clockwise (left, front, right, back) across the provided frame lists.",
      parameters: [
        { name: "frameInterval", type: "number", default: "150", meaning: "Time in milliseconds between animation frame changes." },
        { name: "frames1", type: "Image[]", default: "[]", meaning: "List of images for the first direction (left side)." },
        { name: "frames2", type: "Image[]", default: "undefined", meaning: "Optional list of images for the second direction (front side)." },
        { name: "frames3", type: "Image[]", default: "undefined", meaning: "Optional list of images for the third direction (right side)." },
        { name: "frames4", type: "Image[]", default: "undefined", meaning: "Optional list of images for the fourth direction (back side)." },
      ],
      returns: { type: "Animations", meaning: "A directional animation container that can be attached to sprites." },
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
let anims = Render.createAnimations(150, [img\`.\`], [img\`.\`], [img\`.\`], [img\`.\`])
Render.setSpriteAnimations(enemy, anims)`,
    },
    {
      slug: "get-rc-render-instance",
      title: "raycasting render instance",
      blockId: "rcRender_getRCRenderInstance",
      blockString: "raycasting render",
      group: "Instance",
      weight: 100,
      problem: "You need direct low-level access to the underlying 3D raycasting engine singleton to tweak internal rendering settings.",
      whatItDoes: "Returns the main RayCastingRender engine object running the 3D scene.",
      parameters: [],
      returns: { type: "RayCastingRender", meaning: "The core RayCastingRender instance." },
      example: `let rc = Render.getRCRenderInstance()
rc.cameraSway = 2`,
    },
    {
      slug: "get-render-sprite-variable",
      title: "myself sprite variable",
      blockId: "rcRender_getRenderSpriteVariable",
      blockString: "myself sprite",
      group: "Instance",
      weight: 99,
      problem: "You want to move, reposition, or check collisions for the player's 3D viewpoint camera as if it were a normal sprite.",
      whatItDoes: "Returns the automatically created player sprite that holds the 3D camera viewpoint and handles standard 2D physical collisions.",
      parameters: [],
      returns: { type: "Sprite", meaning: "The player's camera viewpoint sprite." },
      example: `let mySprite = Render.getRenderSpriteVariable()
mySprite.setPosition(80, 60)`,
    },
    {
      slug: "get-render-sprite-instance",
      title: "myself sprite instance",
      blockId: "rcRender_getRenderSpriteInstance",
      blockString: "myself sprite",
      group: "Instance",
      weight: 98,
      problem: "You need to quickly modify the player's camera sprite inside an event handler without saving it to a variable first.",
      whatItDoes: "Fetches the player's viewpoint sprite instance representing the player in the 3D world.",
      parameters: [],
      returns: { type: "Sprite", meaning: "The player's camera viewpoint sprite." },
      example: "Render.getRenderSpriteInstance().setPosition(32, 32)",
    },
    {
      slug: "toggle-view-mode",
      title: "toggle view mode",
      blockId: "rcRender_toggleViewMode",
      blockString: "toggle current view mode",
      group: "Basic",
      weight: 90,
      problem: "You want the player to press a button to switch between an overhead 2D mini-map view and the immersive 3D first-person view.",
      whatItDoes: "Switches the display between the flat 2D tilemap mode and the 3D raycasting mode.",
      parameters: [],
      returns: { type: "void", meaning: "Nothing." },
      example: `controller.menu.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.toggleViewMode()
})`,
    },
    {
      slug: "set-ceiling-tilemap",
      title: "set ceiling tilemap",
      blockId: "rc_Render_setCeilingTilemap",
      blockString: "set ceiling as $tilemap",
      group: "Basic",
      weight: 89,
      problem: "You are building an indoor dungeon or spaceship and want textured ceilings above the player instead of an open sky.",
      whatItDoes: "Applies a tilemap layout to render textured ceilings above the player. The ceiling tilemap dimensions must match your base tilemap.",
      parameters: [
        { name: "tilemap", type: "tiles.TileMapData", default: "undefined", meaning: "The tilemap data containing the textures to use as the ceiling." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: "Render.setCeilingTilemap(tilemap`level1`)",
    },
    {
      slug: "is-view-mode",
      title: "is view mode",
      blockId: "rcRender_isViewMode",
      blockString: "current is $viewMode",
      group: "Basic",
      weight: 88,
      problem: "You need to know whether the game is currently showing the 2D tilemap or the 3D camera so you can display the correct UI or background.",
      whatItDoes: "Checks if the current rendering mode matches the specified ViewMode (tilemapView or raycastingView).",
      parameters: [
        { name: "viewMode", type: "ViewMode", default: "ViewMode.raycastingView", meaning: "The view mode to compare against (tilemapView or raycastingView)." },
      ],
      returns: { type: "boolean", meaning: "true if the current view matches the specified mode, otherwise false." },
      example: `if (Render.isViewMode(ViewMode.tilemapView)) {
    scene.setBackgroundColor(7)
}`,
    },
    {
      slug: "set-view-mode",
      title: "set view mode",
      blockId: "rcRender_setViewMode",
      blockString: "set view mode $viewMode",
      group: "Basic",
      weight: 87,
      problem: "You want to force the game into the overhead 2D map view when opening an inventory screen and switch back to 3D when closed.",
      whatItDoes: "Sets the rendering mode directly to either 2D tilemap view or 3D raycasting view.",
      parameters: [
        { name: "viewMode", type: "ViewMode", default: "ViewMode.raycastingView", meaning: "The view mode to activate." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: "Render.setViewMode(ViewMode.raycastingView)",
    },
    {
      slug: "get-attribute",
      title: "get attribute",
      blockId: "rcRender_getAttribute",
      blockString: "get %attribute",
      group: "Basic",
      weight: 83,
      problem: "You want to check the player's current field-of-view (FOV), viewing direction, or wall height scale to calculate game logic or display a scope.",
      whatItDoes: "Returns the value of a global raycasting camera attribute like dirX, dirY, fov, or wallZScale.",
      parameters: [
        { name: "attr", type: "Render.attribute", default: "Render.attribute.fov", meaning: "The render attribute to read (dirX, dirY, fov, or wallZScale)." },
      ],
      returns: { type: "number", meaning: "The current numeric value of the requested attribute." },
      example: `let currentFov = Render.getAttribute(Render.attribute.fov)
console.log(currentFov)`,
    },
    {
      slug: "set-attribute",
      title: "set attribute",
      blockId: "rcRender_setAttribute",
      blockString: "set %attribute = %value",
      group: "Basic",
      weight: 82,
      problem: "You want to create a sniper zoom effect by narrowing the FOV or create tall castle walls by increasing the wall height scale.",
      whatItDoes: "Updates global camera settings including viewing direction vectors (dirX, dirY), field of view (fov), or wall height scaling (wallZScale).",
      parameters: [
        { name: "attr", type: "Render.attribute", default: "Render.attribute.fov", meaning: "The render attribute to modify." },
        { name: "value", type: "number", default: "0", meaning: "The new numeric value to set." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: "Render.setAttribute(Render.attribute.wallZScale, 2)",
    },
    {
      slug: "get-default-fov",
      title: "get default fov",
      blockId: "rcRender_getDefaultFov",
      blockString: "defaultFov",
      group: "Basic",
      weight: 81,
      problem: "You changed the player's camera zoom level during a power-up and need to reset the field-of-view back to its normal default setting.",
      whatItDoes: "Returns the default field-of-view value (approximately 0.667 or 2/3) where one tile fills the screen height when standing one step away.",
      parameters: [],
      returns: { type: "number", meaning: "The default field-of-view value." },
      example: "Render.setAttribute(Render.attribute.fov, Render.getDefaultFov())",
    },
    {
      slug: "set-view-angle-in-degree",
      title: "set view angle in degrees",
      blockId: "rcRender_setViewAngleInDegree",
      blockString: "set view angle$angle",
      group: "Basic",
      weight: 80,
      problem: "You want the player to face south (90°), west (180°), or towards a specific doorway when entering a new room.",
      whatItDoes: "Sets the 3D camera facing direction using degrees from 0 to 360 (0° = East, 90° = South, 180° = West, 270° = North).",
      parameters: [
        { name: "angle", type: "number", default: "90", meaning: "The target view angle in degrees (0 to 360)." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: "Render.setViewAngleInDegree(180)",
    },
    {
      slug: "set-view-angle",
      title: "set view angle",
      blockId: "rcRender_setViewAngle",
      blockString: "set view angle by dirX%dirX and dirY%dirY",
      group: "Basic",
      weight: 79,
      problem: "You want the camera to automatically turn and point towards an enemy's X/Y offset direction.",
      whatItDoes: "Sets the player's 3D viewing angle using directional X and Y vector components.",
      parameters: [
        { name: "dirX", type: "number", default: "0", meaning: "Horizontal direction vector component." },
        { name: "dirY", type: "number", default: "-1", meaning: "Vertical direction vector component." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: "Render.setViewAngle(0, -1)",
    },
    {
      slug: "set-z-offset",
      title: "set z offset",
      blockId: "rcRender_setZOffset",
      blockString: "set Sprite %spr=variables_get(mySprite) floating %offset pixels|| duration $duration=timePicker|ms ",
      group: "Dimension Z",
      weight: 77,
      problem: "You want a floating fairy, a flying drone, or a hovering coin to stay suspended above the floor in the 3D world.",
      whatItDoes: "Sets the vertical resting height (Z-offset) in pixels for a sprite, smoothly transitioning over a given duration.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite to float or adjust vertically." },
        { name: "offset", type: "number", default: "8", meaning: "Height in pixels above ground level (positive floats up, negative goes down)." },
        { name: "duration", type: "number", default: "0", meaning: "Transition time in milliseconds (0 for immediate snap)." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: `let coin = sprites.create(img\`.\`, SpriteKind.Food)
Render.setZOffset(coin, 8, 0)`,
    },
    {
      slug: "set-sprite-attribute",
      title: "set sprite attribute",
      blockId: "rcRender_setSpriteAttribute",
      blockString: "set Sprite %spr=variables_get(mySprite) %attribute = %value",
      group: "Dimension Z",
      weight: 75,
      problem: "You want to manually set a sprite's vertical velocity or vertical acceleration for custom 3D gravity physics.",
      whatItDoes: "Sets a 3D motion property (ZOffset, ZPosition, ZVelocity, or ZAcceleration) on a sprite.",
      parameters: [
        { name: "spr", type: "Sprite", default: "mySprite", meaning: "The sprite to modify." },
        { name: "attr", type: "RCSpriteAttribute", default: "RCSpriteAttribute.ZOffset", meaning: "The 3D vertical attribute to change." },
        { name: "value", type: "number", default: "0", meaning: "The numeric value to assign." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Render.setSpriteAttribute(mySprite, RCSpriteAttribute.ZOffset, 4)`,
    },
    {
      slug: "get-sprite-attribute",
      title: "get sprite attribute",
      blockId: "rcRender_getSpriteAttribute",
      blockString: "get Sprite %spr=variables_get(mySprite) %attribute",
      group: "Dimension Z",
      weight: 74,
      problem: "You want to check how high an enemy is currently jumping before triggering an air-strike attack.",
      whatItDoes: "Reads the current 3D vertical attribute value (ZOffset, ZPosition, ZVelocity, or ZAcceleration) of a sprite.",
      parameters: [
        { name: "spr", type: "Sprite", default: "mySprite", meaning: "The sprite to inspect." },
        { name: "attr", type: "RCSpriteAttribute", default: "RCSpriteAttribute.ZPosition", meaning: "The 3D vertical attribute to retrieve." },
      ],
      returns: { type: "number", meaning: "The numeric value of the requested vertical attribute." },
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
let currentZ = Render.getSpriteAttribute(mySprite, RCSpriteAttribute.ZPosition)
console.log(currentZ)`,
    },
    {
      slug: "is-sprites-overlap-z",
      title: "is sprites overlap z",
      blockId: "rcRender_isSpritesOverlapZ",
      blockString: "is sprites $sprite1=variables_get(mySprite) and $sprite2=variables_get(mySprite2) overlaps in Z dimension",
      group: "Dimension Z",
      weight: 71,
      problem: "You shot a projectile at an enemy, but want the shot to miss if the enemy jumped high into the air over the bullet.",
      whatItDoes: "Checks whether two sprites are touching vertically in the 3D Z-dimension. Works alongside 2D overlap events to ensure accurate 3D hits.",
      parameters: [
        { name: "sprite1", type: "Sprite", default: "mySprite", meaning: "The first sprite to check." },
        { name: "sprite2", type: "Sprite", default: "mySprite2", meaning: "The second sprite to check." },
      ],
      returns: { type: "boolean", meaning: "true if the sprites overlap in vertical Z-space, false if one is above or below the other." },
      example: `sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Projectile, function (enemy, proj) {
    if (Render.isSpritesOverlapZ(enemy, proj)) {
        enemy.destroy()
        proj.destroy()
    }
})`,
    },
    {
      slug: "jump-with-height-and-duration",
      title: "jump with height and duration",
      blockId: "rcRender_jumpWithHeightAndDuration",
      blockString: "Sprite %spr=variables_get(mySprite) jump, with height $height duration $duration=timePicker|ms ",
      group: "Dimension Z",
      weight: 70,
      problem: "You want the player or an enemy to do a simple jump reaching exactly 16 pixels high and lasting half a second.",
      whatItDoes: "Calculates smooth jump velocity and gravity automatically based on your desired jump height in pixels and total air-time duration in milliseconds.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite that will jump." },
        { name: "height", type: "number", default: "16", meaning: "Maximum jump peak height in pixels." },
        { name: "duration", type: "number", default: "500", meaning: "Total duration of the jump in milliseconds." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: `controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.jumpWithHeightAndDuration(Render.getRenderSpriteInstance(), 16, 500)
})`,
    },
    {
      slug: "jump",
      title: "jump",
      blockId: "rcRender_jump",
      blockString: "Sprite %spr=variables_get(mySprite) jump||, with speed $v=spriteSpeedPicker acceleration $a",
      group: "Dimension Z",
      weight: 68,
      problem: "You want the player to jump when pressing button B, but only if they are currently standing firmly on the ground.",
      whatItDoes: "Initiates a vertical jump with custom speed and downward gravity acceleration. Only triggers if the sprite is resting at its Z-offset ground level.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite that should jump." },
        { name: "v", type: "number", default: "60", meaning: "Initial upward vertical velocity in pixels per second." },
        { name: "a", type: "number", default: "-250", meaning: "Downward acceleration (gravity) in pixels per second squared." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: `controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.jump(Render.getRenderSpriteInstance(), 60, -250)
})`,
    },
    {
      slug: "move",
      title: "move vertical",
      blockId: "rcRender_move",
      blockString: "Sprite %spr=variables_get(mySprite) move, with speed $v=spriteSpeedPicker|| acceleration $a",
      group: "Dimension Z",
      weight: 66,
      problem: "You want an explosion or spring pad to launch an enemy into the air even if they are already mid-jump.",
      whatItDoes: "Applies immediate vertical velocity and acceleration to a sprite along the 3D Z-axis regardless of whether it is grounded.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite to move vertically." },
        { name: "v", type: "number", default: "60", meaning: "Vertical speed in pixels per second." },
        { name: "a", type: "number", default: "-250", meaning: "Vertical acceleration in pixels per second squared." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
Render.move(enemy, 80, -200)`,
    },
    {
      slug: "move-with-controller",
      title: "move with controller",
      blockId: "rcRender_moveWithController",
      blockString: "move with buttons velocity $v|| turn speed $va camera sway$cameraSway pixels",
      group: "Advanced",
      weight: 60,
      problem: "You want the D-pad arrows to control standard first-person movement: Up/Down to walk forward/backward, and Left/Right to turn the camera.",
      whatItDoes: "Enables built-in arcade controller handling for walking and turning in 3D, with optional head-bobbing camera sway. Pass 0 for both speeds to disable controller movement.",
      parameters: [
        { name: "v", type: "number", default: "2", meaning: "Walking speed forward and backward in pixels per second." },
        { name: "va", type: "number", default: "3", meaning: "Camera rotation turn speed in radians per second." },
        { name: "cameraSway", type: "number", default: "undefined", meaning: "Optional head-bobbing sway intensity in pixels while walking." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: "Render.moveWithController(2, 3, 1)",
    },
    {
      slug: "takeover-scene-sprites",
      title: "takeover scene sprites",
      blockId: "rcRender_takeoverSceneSprites",
      blockString: "takeover sprites in scene",
      group: "Advanced",
      weight: 49,
      problem: "You spawned a new enemy or projectile mid-game, but it is drawing flat on the 2D tilemap instead of inside the 3D raycasted world.",
      whatItDoes: "Registers all existing sprites in the scene into the 3D raycasting renderer. The engine does this periodically, but calling this immediately after spawning ensures seamless 3D rendering.",
      parameters: [],
      returns: { type: "void", meaning: "Nothing." },
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
Render.takeoverSceneSprites()`,
    },
    {
      slug: "register-on-sprite-direction-update-handler",
      title: "on sprite direction updated",
      blockId: "rcRender_registerOnSpriteDirectionUpdateHandler",
      blockString: "run code when sprite $spr dirction updated to $dir",
      group: "Advanced",
      weight: 48,
      problem: "You are using a custom character animation library and need to know the angle at which the player is viewing an enemy sprite.",
      whatItDoes: "Runs a callback whenever a sprite's relative facing angle updates, passing the sprite and a normalized direction float (0 to 1 representing 0° to 360°).",
      parameters: [
        { name: "handler", type: "(spr: Sprite, dir: number) => void", default: "undefined", meaning: "The function to run when direction updates, receiving the sprite and direction ratio (0 to 1)." },
      ],
      returns: { type: "void", meaning: "Nothing." },
      example: `Render.registerOnSpriteDirectionUpdateHandler(function (spr, dir) {
    let dirIndex = Math.round(dir * 4) % 4
    console.log(dirIndex)
})`,
    }
  ],
};
