import type { ExtensionDoc } from "@/content/extensions/types";

export const raycastingPxtExtension: ExtensionDoc = {
  owner: "The-Code-Zone",
  repo: "Raycasting-pxt-extension",
  displayName: "3D Raycasting",
  packageSlug: "github:The-Code-Zone/Raycasting-pxt-extension",
  description: "A 3D first-person raycasting renderer that turns Arcade tilemaps into 3D mazes with multi-directional sprite animations and vertical Z-height movement.",
  tools: [
    {
      slug: "create-animations",
      title: "create animations",
      blockId: "create_animation",
      blockString: "interval$frameInterval=timePicker animates:$frames1=animation_editor|| $frames2=animation_editor $frames3=animation_editor $frames4=animation_editor",
      group: "Animate",
      weight: 100,
      problem: "You want a 3D sprite or enemy to face towards, away from, or sideways from your camera as you walk around it in a 3D maze.",
      whatItDoes: "Creates a multi-directional animation set for a sprite in 3D space. It divides up to four animation directions evenly around 360 degrees so sprites automatically show their front, back, or side frames based on your viewing angle.",
      parameters: [
        { name: "frameInterval", type: "number", default: 150, meaning: "Time in milliseconds between animation frame changes." },
        { name: "frames1", type: "Image[]", meaning: "Animation frames for the left direction (or default direction)." },
        { name: "frames2", type: "Image[]", meaning: "Optional animation frames for additional directions (e.g., front)." },
        { name: "frames3", type: "Image[]", meaning: "Optional animation frames for additional directions (e.g., right)." },
        { name: "frames4", type: "Image[]", meaning: "Optional animation frames for additional directions (e.g., back)." },
      ],
      returns: { type: "Render.Animations", meaning: "A directional animation container object to assign to a sprite." },
      example: `let anim = Render.createAnimations(150, [img\`
. . . . f f f f . . . .
. . f f e e e e f f . .
. f e e e e e e e e f .
. . f f f f f f f f . .
\`])
let mySprite = Render.getRenderSpriteVariable()
Render.setSpriteAnimations(mySprite, anim)`,
    },
    {
      slug: "get-rc-render-instance",
      title: "raycasting render instance",
      blockId: "rcRender_getRCRenderInstance",
      blockString: "raycasting render",
      group: "Instance",
      weight: 100,
      problem: "You need low-level access to the core engine instance that controls the 3D raycasting renderer.",
      whatItDoes: "Returns the underlying RayCastingRender instance driving the 3D viewport. Note that this block is hidden from the block toolbox and intended for advanced script setups.",
      parameters: [],
      returns: { type: "RayCastingRender", meaning: "The main raycasting renderer instance." },
      example: "let engine = Render.getRCRenderInstance()",
    },
    {
      slug: "get-render-sprite-variable",
      title: "myself sprite variable",
      blockId: "rcRender_getRenderSpriteVariable",
      blockString: "myself sprite",
      group: "Instance",
      weight: 99,
      problem: "You need to store the player's 3D camera sprite into a variable so you can position it, add collision events, or give it health.",
      whatItDoes: "Gets the player sprite automatically created by the 3D engine to track the camera's location and physical collisions in the tilemap.",
      parameters: [],
      returns: { type: "Sprite", meaning: "The player sprite holding the camera view point." },
      example: `let player = Render.getRenderSpriteVariable()
player.setPosition(80, 80)`,
    },
    {
      slug: "get-render-sprite-instance",
      title: "myself sprite instance",
      blockId: "rcRender_getRenderSpriteInstance",
      blockString: "myself sprite",
      group: "Instance",
      weight: 98,
      problem: "You want to modify the player camera sprite directly inside an event or function without creating a new variable.",
      whatItDoes: "Returns the internal player sprite used for camera viewpoint positioning and tilemap collision handling.",
      parameters: [],
      returns: { type: "Sprite", meaning: "The player sprite holding the camera viewpoint." },
      example: "Render.getRenderSpriteInstance().setPosition(100, 100)",
    },
    {
      slug: "toggle-view-mode",
      title: "toggle view mode",
      blockId: "rcRender_toggleViewMode",
      blockString: "toggle current view mode",
      group: "Basic",
      weight: 90,
      problem: "You want to let the player switch between a top-down 2D map view and a 3D first-person perspective by pressing a button.",
      whatItDoes: "Toggles the game view mode back and forth between 3D raycasting mode and traditional 2D flat tilemap mode.",
      parameters: [],
      example: `controller.menu.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.toggleViewMode()
})`,
    },
    {
      slug: "set-ceiling-tilemap",
      title: "set ceiling tilemap",
      blockId: "rc_Render_setCeilingTilemap",
      blockString: "set ceiling as $tilemap",
      group: "Basic",
      weight: 89,
      problem: "You are making an indoor dungeon game and want a textured ceiling tilemap drawn above the player instead of an open sky.",
      whatItDoes: "Assigns a separate tilemap to render overhead as a ceiling in 3D mode. The ceiling tilemap must have the exact same dimensions as the main ground tilemap.",
      parameters: [
        { name: "tilemap", type: "tiles.TileMapData", meaning: "The tilemap layout to render on the ceiling." },
      ],
      example: "Render.setCeilingTilemap(tilemap`level1`)",
    },
    {
      slug: "is-view-mode",
      title: "is view mode",
      blockId: "rcRender_isViewMode",
      blockString: "current is $viewMode",
      group: "Basic",
      weight: 88,
      problem: "You want your HUD elements or minimap code to run only when the game is showing the flat 2D tilemap view.",
      whatItDoes: "Checks whether the active viewport is currently set to a specific view mode (either raycastingView or tilemapView).",
      parameters: [
        { name: "viewMode", type: "ViewMode", meaning: "The view mode to check against (ViewMode.raycastingView or ViewMode.tilemapView)." },
      ],
      returns: { type: "boolean", meaning: "true if the camera matches the given view mode." },
      example: `if (Render.isViewMode(ViewMode.tilemapView)) {
    console.log("Showing 2D Map")
}`,
    },
    {
      slug: "set-view-mode",
      title: "set view mode",
      blockId: "rcRender_setViewMode",
      blockString: "set view mode $viewMode",
      group: "Basic",
      weight: 87,
      problem: "You want to switch the view mode to 2D tilemap mode when opening a game menu and return to 3D raycasting mode when closing it.",
      whatItDoes: "Sets the active camera perspective directly to either 3D first-person raycasting mode or 2D top-down tilemap mode.",
      parameters: [
        { name: "viewMode", type: "ViewMode", meaning: "The perspective mode to enable." },
      ],
      example: "Render.setViewMode(ViewMode.tilemapView)",
    },
    {
      slug: "get-attribute",
      title: "get attribute",
      blockId: "rcRender_getAttribute",
      blockString: "get %attribute",
      group: "Basic",
      weight: 83,
      problem: "You want to read rendering settings like camera direction vector or field of view (FOV) to dynamically adjust zoom levels.",
      whatItDoes: "Returns the numeric value of a specific rendering setting, such as view direction X/Y, field of view, or wall height scale.",
      parameters: [
        { name: "attr", type: "Render.attribute", meaning: "The camera attribute to inspect (dirX, dirY, fov, wallZScale)." },
      ],
      returns: { type: "number", meaning: "The numeric value of the requested render attribute." },
      example: "let fov = Render.getAttribute(Render.attribute.fov)",
    },
    {
      slug: "set-attribute",
      title: "set attribute",
      blockId: "rcRender_setAttribute",
      blockString: "set %attribute = %value",
      group: "Basic",
      weight: 82,
      problem: "You want to make walls appear twice as tall in a boss room or zoom the camera in when aiming.",
      whatItDoes: "Changes camera rendering settings, including field of view angle and wall height scale factor in 3D space.",
      parameters: [
        { name: "attr", type: "Render.attribute", meaning: "The camera attribute to change." },
        { name: "value", type: "number", meaning: "The new numeric value." },
      ],
      example: "Render.setAttribute(Render.attribute.wallZScale, 2)",
    },
    {
      slug: "default-fov",
      title: "default fov",
      blockId: "rcRender_getDefaultFov",
      blockString: "defaultFov",
      group: "Basic",
      weight: 81,
      problem: "You changed the camera zoom during gameplay and need to reset the field of view back to standard settings.",
      whatItDoes: "Returns the default camera field of view ratio value (approximately 0.666), where a 1-tile wide wall fills the screen height when standing 1 tile away.",
      parameters: [],
      returns: { type: "number", meaning: "The standard field of view ratio." },
      example: "Render.setAttribute(Render.attribute.fov, Render.getDefaultFov())",
    },
    {
      slug: "set-view-angle-in-degree",
      title: "set view angle in degree",
      blockId: "rcRender_setViewAngleInDegree",
      blockString: "set view angle$angle",
      group: "Basic",
      weight: 80,
      problem: "You want the player to face a specific direction (such as 180 degrees for West) when spawning in a new level.",
      whatItDoes: "Sets the facing direction angle of the camera in degrees from 0 to 360 (0 = East, 90 = South, 180 = West, 270 = North).",
      parameters: [
        { name: "angle", type: "number", default: 90, meaning: "The view angle in degrees (0 to 360)." },
      ],
      example: "Render.setViewAngleInDegree(180)",
    },
    {
      slug: "set-view-angle",
      title: "set view angle",
      blockId: "rcRender_setViewAngle",
      blockString: "set view angle by dirX%dirX and dirY%dirY",
      group: "Basic",
      weight: 79,
      problem: "You want the camera angle to turn toward an objective using X and Y directional offset values.",
      whatItDoes: "Sets the 3D camera facing angle using X and Y direction vector components.",
      parameters: [
        { name: "dirX", type: "number", meaning: "The X direction component." },
        { name: "dirY", type: "number", meaning: "The Y direction component." },
      ],
      example: "Render.setViewAngle(0, -1)",
    },
    {
      slug: "set-z-offset",
      title: "set z offset",
      blockId: "rcRender_setZOffset",
      blockString: "set Sprite %spr=variables_get(mySprite) floating %offset pixels|| duration $duration=timePicker|ms ",
      group: "Dimension Z",
      weight: 77,
      problem: "You want a floating collectible or flying ghost sprite to hover high above the floor in your 3D world.",
      whatItDoes: "Sets the floating height (Z offset) of a sprite in pixels above the floor over an optional transition duration.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite to raise or lower." },
        { name: "offset", type: "number", default: 8, meaning: "Offset height in pixels (positive floats upward, negative downward)." },
        { name: "duration", type: "number", default: 0, meaning: "Transition time in milliseconds (0 for immediate movement)." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Enemy)
Render.setZOffset(mySprite, 12, 500)`,
    },
    {
      slug: "set-sprite-attribute",
      title: "set sprite attribute",
      blockId: "rcRender_setSpriteAttribute",
      blockString: "set Sprite %spr=variables_get(mySprite) %attribute = %value",
      group: "Dimension Z",
      weight: 75,
      problem: "You want to manually set a sprite's vertical upward speed or downward gravitational acceleration in 3D height space.",
      whatItDoes: "Sets specific Z-dimension motion attributes for a sprite, including resting height offset, current position, velocity, and gravity acceleration.",
      parameters: [
        { name: "spr", type: "Sprite", default: "mySprite", meaning: "The sprite to update." },
        { name: "attr", type: "RCSpriteAttribute", meaning: "The Z attribute to set (ZOffset, ZPosition, ZVelocity, or ZAcceleration)." },
        { name: "value", type: "number", meaning: "The target value." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Render.setSpriteAttribute(mySprite, RCSpriteAttribute.ZOffset, 10)`,
    },
    {
      slug: "get-sprite-attribute",
      title: "get sprite attribute",
      blockId: "rcRender_getSpriteAttribute",
      blockString: "get Sprite %spr=variables_get(mySprite) %attribute",
      group: "Dimension Z",
      weight: 74,
      problem: "You want to check how high off the ground a jumping sprite currently is before letting them double-jump.",
      whatItDoes: "Reads a sprite's current Z-dimension motion property, such as resting offset, position height, vertical speed, or acceleration.",
      parameters: [
        { name: "spr", type: "Sprite", default: "mySprite", meaning: "The sprite to inspect." },
        { name: "attr", type: "RCSpriteAttribute", meaning: "The Z attribute to read." },
      ],
      returns: { type: "number", meaning: "The numeric value of the requested Z-dimension attribute." },
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
let height = Render.getSpriteAttribute(mySprite, RCSpriteAttribute.ZPosition)`,
    },
    {
      slug: "is-sprites-overlap-z",
      title: "is sprites overlap z",
      blockId: "rcRender_isSpritesOverlapZ",
      blockString: "is sprites $sprite1=variables_get(mySprite) and $sprite2=variables_get(mySprite2) overlaps in Z dimension",
      group: "Dimension Z",
      weight: 71,
      problem: "A player walking under a floating item triggers a collision even though the player is on the ground and the item is high in the air.",
      whatItDoes: "Checks if two sprites overlap along the vertical Z height axis, helping ensure 3D collisions only happen when sprites are at the same height.",
      parameters: [
        { name: "sprite1", type: "Sprite", default: "mySprite", meaning: "The first sprite." },
        { name: "sprite2", type: "Sprite", default: "mySprite2", meaning: "The second sprite." },
      ],
      returns: { type: "boolean", meaning: "true if both sprites overlap in Z height." },
      example: `sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (Render.isSpritesOverlapZ(sprite, otherSprite)) {
        info.changeLifeBy(-1)
    }
})`,
    },
    {
      slug: "jump-with-height-and-duration",
      title: "jump with height and duration",
      blockId: "rcRender_jumpWithHeightAndDuration",
      blockString: "Sprite %spr=variables_get(mySprite) jump, with height $height duration $duration=timePicker|ms ",
      group: "Dimension Z",
      weight: 70,
      problem: "You want the player to jump over low obstacles with a specific maximum jump height and air time.",
      whatItDoes: "Makes a standing sprite perform a vertical jump calculated from a peak jump height in pixels and total duration in milliseconds. Jump only executes if the sprite is currently standing on the floor.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite that will jump." },
        { name: "height", type: "number", default: 16, meaning: "Peak height of the jump in pixels." },
        { name: "duration", type: "number", default: 500, meaning: "Total air time in milliseconds." },
      ],
      example: `controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Render.jumpWithHeightAndDuration(Render.getRenderSpriteInstance(), 16, 500)
})`,
    },
    {
      slug: "jump",
      title: "jump",
      blockId: "rcRender_jump",
      blockString: "Sprite %spr=variables_get(mySprite) jump||, with speed $v=spriteSpeedPicker acceleration $a",
      group: "Dimension Z",
      weight: 68,
      problem: "You want a sprite to jump upward with custom launch speed and gravitational pull when pressing a button.",
      whatItDoes: "Launches a standing sprite into a vertical jump using upward velocity and negative vertical gravity. Only takes effect if the sprite is on the ground.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite to jump." },
        { name: "v", type: "number", default: 60, meaning: "Initial vertical upward speed in pixels per second." },
        { name: "a", type: "number", default: -250, meaning: "Vertical gravity acceleration in pixels per second squared." },
      ],
      example: `let mySprite = Render.getRenderSpriteVariable()
Render.jump(mySprite, 60, -250)`,
    },
    {
      slug: "move",
      title: "move",
      blockId: "rcRender_move",
      blockString: "Sprite %spr=variables_get(mySprite) move, with speed $v=spriteSpeedPicker|| acceleration $a",
      group: "Dimension Z",
      weight: 66,
      problem: "You want an enemy or bouncing item to pop upward in the air regardless of whether it is currently standing on the floor.",
      whatItDoes: "Applies immediate vertical Z velocity and acceleration to a sprite, allowing vertical movements even mid-air.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The target sprite." },
        { name: "v", type: "number", default: 60, meaning: "Vertical launch speed in pixels per second." },
        { name: "a", type: "number", default: -250, meaning: "Vertical acceleration in pixels per second squared." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Enemy)
Render.move(mySprite, 80, -200)`,
    },
    {
      slug: "move-with-controller",
      title: "move with controller",
      blockId: "rcRender_moveWithController",
      blockString: "move with buttons velocity $v|| turn speed $va camera sway$cameraSway pixels",
      group: "Advanced",
      weight: 60,
      problem: "You want players to drive the 3D first-person camera around the level using controller buttons, with realistic walking head sway.",
      whatItDoes: "Binds direction buttons to 3D movement: Up/Down moves forward/backward, and Left/Right turns the view camera. You can also add pixel head sway to simulate walking.",
      parameters: [
        { name: "v", type: "number", default: 2, meaning: "Forward and backward speed in pixels per second." },
        { name: "va", type: "number", default: 3, meaning: "Turning angular velocity in radians per second." },
        { name: "cameraSway", type: "number", meaning: "Optional walking camera bobbing distance in pixels." },
      ],
      example: "Render.moveWithController(2, 3, 1)",
    },
    {
      slug: "takeover-scene-sprites",
      title: "takeover scene sprites",
      blockId: "rcRender_takeoverSceneSprites",
      blockString: "takeover sprites in scene",
      group: "Advanced",
      weight: 49,
      problem: "A newly created sprite briefly flashes at its flat 2D tilemap position before the 3D renderer takes control of it.",
      whatItDoes: "Forces the 3D renderer to immediately take control of all active sprites in the current scene so they are drawn inside the 3D perspective right away.",
      parameters: [],
      example: `let myEnemy = sprites.create(img\`.\`, SpriteKind.Enemy)
Render.takeoverSceneSprites()`,
    },
    {
      slug: "run-code-when-sprite-direction-updated",
      title: "run code when sprite direction updated",
      blockId: "rcRender_registerOnSpriteDirectionUpdateHandler",
      blockString: "run code when sprite $spr dirction updated to $dir",
      group: "Advanced",
      weight: 48,
      problem: "You are using a custom character animation extension and need to swap sprite frames whenever the camera's viewing angle relative to a sprite changes.",
      whatItDoes: "Registers a custom handler that runs whenever the relative viewing angle of a sprite changes, passing in the normalized viewing direction between 0 and 1.",
      parameters: [
        { name: "handler", type: "function", meaning: "Callback function receiving (spr: Sprite, dir: number) where dir is a normalized angle value from 0 to 1." },
      ],
      example: `Render.registerOnSpriteDirectionUpdateHandler(function (spr, dir) {
    let dirIndex = Math.round(dir * 4) % 4
})`,
    }
  ],
};
