import type { ExtensionDoc } from "@/content/extensions/types";

export const retrofx: ExtensionDoc = {
  owner: "CrzLe0723",
  repo: "RetroFx",
  displayName: "Retro FX",
  packageSlug: "github:CrzLe0723/RetroFx",
  description: "Retro-style UI and game juice extension for MakeCode Arcade featuring customizable sound effects, particle bursts, screen effects, dialogues, and movement helpers.",
  tools: [
    {
      slug: "show-long-text",
      title: "show long text",
      blockId: "retro_skip_text",
      blockString: "skip text",
      group: "Dialog",
      weight: 0,
      problem: "You want to show story text or dialogue that displays letter-by-letter with animated effects like typewriter or glitch.",
      whatItDoes: "Starts the retro text engine to display long text at a specified typing speed with visual effects.",
      parameters: [
        { name: "text", type: "string", meaning: "The message to display." },
        { name: "speed", type: "number", meaning: "Delay between characters in milliseconds." },
        { name: "effect", type: "TextFx", meaning: "Animation style for the text (Typewriter, Scroll, Glitch, Fade)." },
      ],
      example: "Retro.showLongText(\"Welcome to the dungeon!\", 50, TextFx.Typewriter)",
    },
    {
      slug: "get-text",
      title: "get text",
      blockId: "retro_get_text",
      blockString: "get text output",
      group: "Dialog",
      weight: 100,
      problem: "You want to read the current text string that has been generated so far by the text engine.",
      whatItDoes: "Returns the output text string generated so far by the retro text engine.",
      parameters: [],
      returns: { type: "string", meaning: "The currently visible text string." },
      example: `let currentText = Retro.getText()
console.log(currentText)`,
    },
    {
      slug: "text-finished",
      title: "text finished",
      blockId: "retro_text_finished?",
      blockString: "text finished?",
      group: "Dialog",
      weight: 100,
      problem: "You want to check if a dialogue line has finished typing before letting the player press A to continue.",
      whatItDoes: "Returns true if the text engine has completed typing out the full message.",
      parameters: [],
      returns: { type: "boolean", meaning: "true if the text animation is complete." },
      example: `if (Retro.textFinished()) {
    console.log("Dialogue completed!")
}`,
    },
    {
      slug: "skip-text",
      title: "skip text",
      blockId: "retro_skip_text",
      blockString: "skip text",
      group: "Dialog",
      weight: 100,
      problem: "You want to let impatient players instantly reveal the entire line of dialogue when they press a button.",
      whatItDoes: "Instantly completes the current text typing animation and reveals all text.",
      parameters: [],
      example: `controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Retro.skipText()
})`,
    },
    {
      slug: "play-retro-sound",
      title: "play retro sound",
      blockId: "retro_play_sound",
      blockString: "play retro sound $sound",
      group: "Sound",
      weight: 100,
      problem: "You want to play classic 8-bit sound effects like jumping, collecting coins, or taking damage.",
      whatItDoes: "Plays a built-in retro sound effect from the library.",
      parameters: [
        { name: "sound", type: "Sounds", meaning: "The preset retro sound effect to play." },
      ],
      example: "Retro.playRetroSound(Sounds.Coin)",
    },
    {
      slug: "quantize-pitch",
      title: "quantize pitch",
      blockId: "retro_quantize_pitch",
      blockString: "quantize pitch $pitch step $step",
      group: "Utility",
      weight: 40,
      problem: "You want sound frequencies or pitch values to snap to musical steps so custom sound effects sound in tune.",
      whatItDoes: "Rounds a pitch value to the nearest step increment.",
      parameters: [
        { name: "pitch", type: "number", meaning: "The starting pitch frequency in Hertz." },
        { name: "step", type: "number", default: "50", meaning: "The step size to snap the pitch to." },
      ],
      returns: { type: "number", meaning: "The quantized pitch frequency." },
      example: `let tunedPitch = Retro.quantizePitch(630, 50)
console.log(tunedPitch)`,
    },
    {
      slug: "envelope-sound",
      title: "envelope sound",
      blockId: "retro_envelope_sound",
      blockString: "play envelope sound start pitch $startPitch end pitch $endPitch||attack $attack decay $decay sustain $sustain release $release",
      group: "Sound",
      weight: 93,
      problem: "You want custom control over a sound's volume and pitch stages like attack, decay, sustain, and release.",
      whatItDoes: "Plays a dynamic sound with controlled pitch slides and duration envelope stages.",
      parameters: [
        { name: "startPitch", type: "number", default: "600", meaning: "Pitch frequency at the start." },
        { name: "endPitch", type: "number", default: "400", meaning: "Pitch frequency at the end." },
        { name: "attack", type: "number", default: "50", meaning: "Attack time in milliseconds." },
        { name: "decay", type: "number", default: "50", meaning: "Decay time in milliseconds." },
        { name: "sustain", type: "number", default: "180", meaning: "Sustain volume level." },
        { name: "release", type: "number", default: "100", meaning: "Release time in milliseconds." },
      ],
      example: "Retro.envelopeSound(800, 300, 40, 40, 200, 80)",
    },
    {
      slug: "pitch-sweep",
      title: "pitch sweep",
      blockId: "retro_pitch_sweep",
      blockString: "play pitch sweep start $startPitch end $endPitch duration $duration ms",
      group: "General",
      weight: 92,
      problem: "You want to make custom sound effects that smoothly slide up or down, like a falling whistle or rising power-up tone.",
      whatItDoes: "Plays a synthesizer sound that smoothly sweeps from a starting pitch to an ending pitch over a given duration.",
      parameters: [
        { name: "startPitch", type: "number", default: "1200", meaning: "Starting pitch frequency." },
        { name: "endPitch", type: "number", default: "200", meaning: "Ending pitch frequency." },
        { name: "duration", type: "number", default: "120", meaning: "Length of the sweep in milliseconds." },
      ],
      example: "Retro.pitchSweep(1200, 300, 150)",
    },
    {
      slug: "play-sounds-together",
      title: "play sounds together",
      blockId: "retro_parallel_sounds",
      blockString: "play sounds together $a and $b",
      group: "Sound",
      weight: 91,
      problem: "You want two distinct sound effects to trigger at the exact same time during an important game event.",
      whatItDoes: "Plays two retro sound effects simultaneously in parallel.",
      parameters: [
        { name: "a", type: "Sounds", meaning: "First retro sound effect." },
        { name: "b", type: "Sounds", meaning: "Second retro sound effect." },
      ],
      example: "Retro.playSoundsTogether(Sounds.Coin, Sounds.PowerCharged)",
    },
    {
      slug: "play-sound-bank",
      title: "play sound bank",
      blockId: "retro_sound_bank",
      blockString: "play random sound from bank $sounds",
      group: "Variation",
      weight: 89,
      problem: "You want sound variety when actions repeat, like playing slightly different footsteps or hit noises.",
      whatItDoes: "Randomly selects and plays one sound effect from an array of retro sound choices.",
      parameters: [
        { name: "sounds", type: "Sounds[]", meaning: "Array of sound effects to randomly select from." },
      ],
      example: "Retro.playSoundBank([Sounds.EnemyHit, Sounds.Hurt, Sounds.BreakBlock])",
    },
    {
      slug: "play-sound-bank-variation",
      title: "play sound bank variation",
      blockId: "retro_sound_bank_var",
      blockString: "play sound bank $sounds pitch variation $variation",
      group: "Variation",
      weight: 88,
      problem: "You want repeated actions like sword swings or footsteps to pick a random sound and shift pitch slightly so they don't sound repetitive.",
      whatItDoes: "Picks a random sound from a sound bank and plays it with randomized pitch variation.",
      parameters: [
        { name: "sounds", type: "Sounds[]", meaning: "List of sound effects to choose from." },
        { name: "variation", type: "number", default: "20", meaning: "Amount of pitch variation offset." },
      ],
      example: "Retro.playSoundBankVariation([Sounds.Jump, Sounds.DoubleJump], 25)",
    },
    {
      slug: "play-sound-with-variation",
      title: "play sound with variation",
      blockId: "retro_variation_sound",
      blockString: "play variation pitch $pitch duration $duration volume $volume",
      group: "Variation",
      weight: 80,
      problem: "You want to create procedural sound effects that vary slightly in pitch, volume, and duration every time they play.",
      whatItDoes: "Plays a synthesized sound with randomized variation added to pitch, volume, and duration.",
      parameters: [
        { name: "pitch", type: "number", default: "600", meaning: "Base pitch frequency." },
        { name: "duration", type: "number", default: "100", meaning: "Base duration in milliseconds." },
        { name: "volume", type: "number", default: "120", meaning: "Base volume level." },
      ],
      example: "Retro.playSoundWithVariation(700, 120, 150)",
    },
    {
      slug: "probability-event",
      title: "probability event",
      blockId: "retro_probability_event",
      blockString: "with $chance % chance do",
      group: "Variation",
      weight: 98,
      problem: "You want an action (like dropping a rare item or playing a critical hit effect) to happen only a percentage of the time.",
      whatItDoes: "Executes a block of code based on a specified percentage chance out of 100.",
      parameters: [
        { name: "chance", type: "number", default: "50", meaning: "Percentage chance (0 to 100)." },
        { name: "handler", type: "() => void", meaning: "Code block to run if the random check passes." },
      ],
      example: `Retro.probabilityEvent(25, function () {
    Retro.playRetroSound(Sounds.RareItem)
})`,
    },
    {
      slug: "velocity-variation",
      title: "velocity variation",
      blockId: "retro_velocity_variation",
      blockString: "velocity variation from $velocity min $min max $max",
      group: "Variation",
      weight: 97,
      problem: "You want values like pitch or particle counts to scale based on how fast a sprite is moving.",
      whatItDoes: "Returns the absolute magnitude of a velocity value clamped between a minimum and maximum threshold.",
      parameters: [
        { name: "velocity", type: "number", default: "50", meaning: "Sprite velocity magnitude." },
        { name: "min", type: "number", default: "0", meaning: "Minimum output value." },
        { name: "max", type: "number", default: "100", meaning: "Maximum output value." },
      ],
      returns: { type: "number", meaning: "Clamped variation number." },
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
let v = Retro.velocityVariation(mySprite.vx, 10, 80)
console.log(v)`,
    },
    {
      slug: "variation-table",
      title: "variation table",
      blockId: "retro_variation_table",
      blockString: "variation from table $values",
      group: "Variation",
      weight: 96,
      problem: "You want to randomly select a number from a list of predefined options.",
      whatItDoes: "Picks and returns a random number from an array of numbers.",
      parameters: [
        { name: "values", type: "number[]", meaning: "List of available numbers." },
      ],
      returns: { type: "number", meaning: "A randomly selected number from the list." },
      example: `let randomPitch = Retro.variationTable([400, 600, 800, 1000])
console.log(randomPitch)`,
    },
    {
      slug: "play-dash",
      title: "play dash",
      blockId: "retro_dash_sound",
      blockString: "play dash sound speed $speed",
      group: "Dynamic",
      weight: 70,
      problem: "You want a swoosh sound effect when your hero dashes whose pitch depends on movement speed.",
      whatItDoes: "Plays a dash sound effect with pitch dynamically calculated from the speed value.",
      parameters: [
        { name: "speed", type: "number", default: "100", meaning: "Movement speed of the dash." },
      ],
      example: "Retro.playDash(120)",
    },
    {
      slug: "play-jump",
      title: "play jump",
      blockId: "retro_jump_sound",
      blockString: "play jump sound force $force",
      group: "Dynamic",
      weight: 69,
      problem: "You want a jump sound that sounds higher and punchier when doing a high jump or charged jump.",
      whatItDoes: "Plays a retro jump sound effect scaled according to jump force.",
      parameters: [
        { name: "force", type: "number", default: "50", meaning: "Jump force strength." },
      ],
      example: "Retro.playJump(75)",
    },
    {
      slug: "play-enemy-hit",
      title: "play enemy hit",
      blockId: "retro_enemy_hit",
      blockString: "play enemy hit combo $combo",
      group: "Dynamic",
      weight: 68,
      problem: "You want hit sound effects to increase in pitch as the player builds up a higher attack combo.",
      whatItDoes: "Plays an enemy hit sound effect with a higher pitch for higher combo counts.",
      parameters: [
        { name: "combo", type: "number", default: "1", meaning: "Current combo level." },
      ],
      example: "Retro.playEnemyHit(3)",
    },
    {
      slug: "play-charge",
      title: "play charge",
      blockId: "retro_charge_sound",
      blockString: "play charge sound charge $charge max $maxCharge",
      group: "Dynamic",
      weight: 67,
      problem: "You want audio feedback that rises in pitch while the player holds down a button to charge an attack.",
      whatItDoes: "Plays a sound effect with pitch mapped between current charge and max charge.",
      parameters: [
        { name: "charge", type: "number", default: "0", meaning: "Current charge level." },
        { name: "maxCharge", type: "number", default: "100", meaning: "Maximum charge level." },
      ],
      example: "Retro.playCharge(50, 100)",
    },
    {
      slug: "camera-follow-lag",
      title: "camera follow lag",
      blockId: "retro_camera_follow_lag",
      blockString: "camera follow $sprite lag $lag",
      group: "Camera",
      weight: 84,
      problem: "You want smooth, cinematic camera tracking that follows the player with a slight delay.",
      whatItDoes: "Causes the camera to follow a sprite smoothly with a configurable lag factor.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Player", meaning: "The sprite for the camera to follow." },
        { name: "lag", type: "number", default: "4", meaning: "Lag intensity factor (higher values follow slower)." },
      ],
      example: `let myPlayer = sprites.create(img\`.\`, SpriteKind.Player)
Retro.cameraFollowLag(myPlayer, 5)`,
    },
    {
      slug: "camera-punch",
      title: "camera punch",
      blockId: "retro_camera_punch",
      blockString: "camera punch for $sprite intensity $intensity duration $duration ms",
      group: "Effects",
      weight: 0,
      problem: "You want a brief screen jerk when a heavy weapon connects or a bomb explodes.",
      whatItDoes: "Displaces the camera randomly by an intensity amount for a short duration before snapping back.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Object", meaning: "Target sprite position focus." },
        { name: "intensity", type: "number", default: "4", meaning: "Pixel displacement strength." },
        { name: "duration", type: "number", default: "60", meaning: "Duration of displacement in milliseconds." },
      ],
      example: `let myPlayer = sprites.create(img\`.\`, SpriteKind.Player)
Retro.cameraPunch(myPlayer, 6, 80)`,
    },
    {
      slug: "play-random-sound",
      title: "play random sound",
      blockId: "retro_random_sound",
      blockString: "play random retro sound",
      group: "Sound",
      weight: 95,
      problem: "You want quick random sound feedback for mystery boxes, chaos modes, or glitched items.",
      whatItDoes: "Plays a completely random sound effect from the retro sounds library.",
      parameters: [],
      example: "Retro.playRandomSound()",
    },
    {
      slug: "float-control",
      title: "float control",
      blockId: "retro_float_control",
      blockString: "float movement %sprite factor %value",
      group: "Movement",
      weight: 0,
      problem: "You want floating or underwater controls for a character sprite.",
      whatItDoes: "Applies floating movement handling to a sprite.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Player", meaning: "Sprite to apply float controls to." },
        { name: "value", type: "number", default: "200", meaning: "Float factor value." },
      ],
      example: `let myPlayer = sprites.create(img\`.\`, SpriteKind.Player)
Retro.floatControl(myPlayer, 200)`,
    },
    {
      slug: "input-buffer",
      title: "input buffer",
      blockId: "retro_input_buffer",
      blockString: "input buffer handler %handler buffer $bufferTime ms",
      group: "Input",
      weight: 0,
      problem: "You want button inputs (like jump) to be buffered so actions trigger smoothly even if pressed a fraction of a second early.",
      whatItDoes: "Queues a handler action to run after a buffer delay window.",
      parameters: [
        { name: "handler", type: "() => void", meaning: "Action block to execute." },
        { name: "bufferTime", type: "number", default: "200", meaning: "Buffer retention time in milliseconds." },
      ],
      example: `Retro.inputBuffer(function () {
    console.log("Buffered input executed!")
}, 200)`,
    },
    {
      slug: "screen-vignette",
      title: "screen vignette",
      blockId: "retro_screen_vignette",
      blockString: "screen vignette intensity $intensity",
      group: "Camera",
      weight: 0,
      problem: "You want to darken the screen edges to create a retro arcade monitor or spooky cave mood.",
      whatItDoes: "Applies a screen border vignette overlay with custom intensity.",
      parameters: [
        { name: "intensity", type: "number", default: "80", meaning: "Vignette border color intensity." },
      ],
      example: "Retro.screenVignette(100)",
    },
    {
      slug: "set-speed",
      title: "set speed",
      blockString: "set speed to $speed",
      group: "Movement",
      weight: 0,
      problem: "You want to update a character's base speed parameter.",
      whatItDoes: "Sets the speed variable.",
      parameters: [
        { name: "speed", type: "number", default: "50", meaning: "Movement speed value." },
      ],
      example: "Retro.setSpeed(75)",
    },
    {
      slug: "pixel-dissolve",
      title: "pixel dissolve",
      blockId: "retro_pixel_dissolve",
      blockString: "pixel dissolve $sprite duration $duration ms",
      group: "Effects",
      weight: 0,
      problem: "You want enemies or defeated bosses to disintegrate into pixels when destroyed.",
      whatItDoes: "Fades a sprite away by randomly clearing its pixels over time, then destroys it.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Entity", meaning: "The sprite to dissolve." },
        { name: "duration", type: "number", default: "400", meaning: "Time in milliseconds for the dissolve effect." },
      ],
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
Retro.pixelDissolve(enemy, 500)`,
    },
    {
      slug: "play-custom-sound",
      title: "play custom sound",
      blockId: "retro_custom_sound",
      blockString: "play retro sound $sound volume $volume pitch $pitch",
      group: "Sound",
      weight: 94,
      problem: "You want to play a preset sound effect with customized volume and pitch.",
      whatItDoes: "Plays a retro sound alongside a custom synthesized tone.",
      parameters: [
        { name: "sound", type: "Sounds", meaning: "Base sound effect type." },
        { name: "volume", type: "number", default: "120", meaning: "Custom volume level." },
        { name: "pitch", type: "number", default: "600", meaning: "Custom pitch frequency." },
      ],
      example: "Retro.playCustomSound(Sounds.Hurt, 150, 450)",
    },
    {
      slug: "loop-sound",
      title: "loop sound",
      blockId: "retro_loop_sound",
      blockString: "loop retro sound $sound",
      group: "Utility",
      weight: 80,
      problem: "You want background alarms, charging hums, or engine sounds to repeat continuously.",
      whatItDoes: "Loops a retro sound effect continuously.",
      parameters: [
        { name: "sound", type: "Sounds", meaning: "The sound effect to loop." },
      ],
      example: "Retro.loopSound(Sounds.Charging)",
    },
    {
      slug: "stop-sounds",
      title: "stop sounds",
      blockId: "retro_stop_sound",
      blockString: "stop retro sounds",
      group: "Utility",
      weight: 79,
      problem: "You want to immediately silence all playing audio when entering a menu or pausing the game.",
      whatItDoes: "Stops all currently playing sounds and music.",
      parameters: [],
      example: "Retro.stopSounds()",
    },
    {
      slug: "sequence-sounds",
      title: "sequence sounds",
      blockId: "retro_sequence_sound",
      blockString: "play sound sequence $first then $second",
      group: "Utility",
      weight: 78,
      problem: "You want two sounds to play one right after another, like an alert chime followed by an explosion.",
      whatItDoes: "Plays the first sound until done, then immediately plays the second sound.",
      parameters: [
        { name: "first", type: "Sounds", meaning: "First sound effect." },
        { name: "second", type: "Sounds", meaning: "Second sound effect." },
      ],
      example: "Retro.sequenceSounds(Sounds.PowerCharged, Sounds.LaserHit)",
    },
    {
      slug: "reactive-sound",
      title: "reactive sound",
      blockId: "retro_reactive_sound",
      blockString: "reactive sound value $value min $min max $max",
      group: "Dynamic",
      weight: 70,
      problem: "You want sound pitch to change dynamically based on game variables like health, fuel, or speed.",
      whatItDoes: "Plays a sound whose pitch scales between 300Hz and 900Hz based on a given value range.",
      parameters: [
        { name: "value", type: "number", default: "50", meaning: "Current stat value." },
        { name: "min", type: "number", default: "0", meaning: "Minimum stat value." },
        { name: "max", type: "number", default: "100", meaning: "Maximum stat value." },
      ],
      example: "Retro.reactiveSound(75, 0, 100)",
    },
    {
      slug: "set-pause-mode",
      title: "set pause mode",
      blockId: "retro_pause_toggle",
      blockString: "set retro sound pause mode $state",
      group: "Utility",
      weight: 60,
      problem: "You want sound effects to play synchronously until finished when pause mode is active.",
      whatItDoes: "Sets whether retro sound playback uses synchronous pause mode.",
      parameters: [
        { name: "state", type: "boolean", meaning: "true to enable pause playback mode." },
      ],
      example: "Retro.setPauseMode(true)",
    },
    {
      slug: "set-global-volume",
      title: "set global volume",
      blockId: "retro_global_volume",
      blockString: "set global retro volume $volume",
      group: "Sound",
      weight: 90,
      problem: "You want an in-game volume menu option that changes the global volume for all audio.",
      whatItDoes: "Sets the master sound and music volume level (0 to 255).",
      parameters: [
        { name: "volume", type: "number", meaning: "Volume level between 0 and 255." },
      ],
      example: "Retro.setGlobalVolume(180)",
    },
    {
      slug: "play-combo",
      title: "play combo",
      blockId: "retro_combo_sound",
      blockString: "play retro combo $combo",
      group: "Combo",
      weight: 85,
      problem: "You want preset sound sequences for major achievements like leveling up or finding rare items.",
      whatItDoes: "Plays a preset audio combo sequence for events like Level Up or Rare Item.",
      parameters: [
        { name: "combo", type: "SoundCombos", meaning: "Preset sound combo to play." },
      ],
      example: "Retro.playCombo(SoundCombos.LevelUp)",
    },
    {
      slug: "spawn-effect",
      title: "spawn effect",
      blockId: "retro_particles",
      blockString: "spawn effect $effect at x $x y $y",
      group: "Effect",
      weight: 0,
      problem: "You want retro particle effects like sparks, coin bursts, or explosions at target screen coordinates.",
      whatItDoes: "Spawns particle spread effects at screen coordinates (X, Y) using preset particle styles.",
      parameters: [
        { name: "effect", type: "Effects", meaning: "Particle effect preset to spawn." },
        { name: "x", type: "number", meaning: "Horizontal screen coordinate." },
        { name: "y", type: "number", meaning: "Vertical screen coordinate." },
      ],
      example: "Retro.spawnEffect(Effects.CoinBurst, 80, 60)",
    },
    {
      slug: "play-explosion",
      title: "play explosion",
      blockId: "retro_explosion",
      blockString: "play 8-bit explosion power %power||pitch %pitch duration %duration",
      group: "Special",
      weight: 100,
      problem: "You want a heavy 8-bit explosion sound when a missile hits or a boss detonates.",
      whatItDoes: "Plays a noise-based 8-bit explosion sound with custom power, pitch, and duration.",
      parameters: [
        { name: "power", type: "number", default: "5", meaning: "Explosion power strength." },
        { name: "pitch", type: "number", default: "200", meaning: "Base pitch frequency." },
        { name: "duration", type: "number", default: "300", meaning: "Sound duration in milliseconds." },
      ],
      example: "Retro.playExplosion(8, 180, 400)",
    },
    {
      slug: "trail-effect",
      title: "trail effect",
      blockId: "retro_trail_effect",
      blockString: "add trail to $sprite image $img interval $interval ms",
      group: "Effect",
      weight: 96,
      problem: "You want a fast-moving player or projectile to leave visual trail ghosts behind them.",
      whatItDoes: "Spawns fading trail sprites behind a target sprite at repeated intervals.",
      parameters: [
        { name: "sprite", type: "Sprite", meaning: "Sprite to attach the trail to." },
        { name: "img", type: "Image", meaning: "Image used for trail ghosts." },
        { name: "interval", type: "number", default: "50", meaning: "Time in milliseconds between trail spawns." },
      ],
      example: `let player = sprites.create(img\`.\`, SpriteKind.Player)
Retro.trailEffect(player, img\`.\`, 40)`,
    },
    {
      slug: "screen-ripple",
      title: "screen ripple",
      blockId: "retro_screen_ripple",
      blockString: "screen ripple strength $strength duration $duration ms",
      group: "Effects",
      weight: 99,
      problem: "You want rapid screen shake pulses during boss attacks or earthquakes.",
      whatItDoes: "Triggers repeated camera shakes over a specified duration.",
      parameters: [
        { name: "strength", type: "number", default: "3", meaning: "Camera shake intensity." },
        { name: "duration", type: "number", default: "200", meaning: "Total duration in milliseconds." },
      ],
      example: "Retro.screenRipple(4, 300)",
    },
    {
      slug: "screen-flash",
      title: "screen flash",
      blockId: "retro_screen_flash",
      blockString: "screen flash to white for $duration,pause for $pauseTime",
      group: "Effect",
      weight: 100,
      problem: "You want a flash of bright white screen light during lightning or big power-ups.",
      whatItDoes: "Fades the screen to white for a duration and restores the palette after a pause.",
      parameters: [
        { name: "pauseTime", type: "number", meaning: "Pause duration while full white." },
        { name: "duration", type: "number", default: "120", meaning: "Fade transition duration." },
      ],
      example: "Retro.screenFlash(200, 100)",
    },
    {
      slug: "play-laser",
      title: "play laser",
      blockId: "retro_laser",
      blockString: "play laser intensity %intensity||start pitch %startPitch end pitch %endPitch",
      group: "Special",
      weight: 99,
      problem: "You want a futuristic blaster sound when firing laser weapons.",
      whatItDoes: "Plays a sweeping retro laser sound effect with customizable pitch sweep.",
      parameters: [
        { name: "intensity", type: "number", default: "4", meaning: "Laser power intensity." },
        { name: "startPitch", type: "number", default: "1200", meaning: "Starting pitch frequency." },
        { name: "endPitch", type: "number", default: "300", meaning: "Ending pitch frequency." },
      ],
      example: "Retro.playLaser(5, 1400, 200)",
    },
    {
      slug: "coin-cascade",
      title: "coin cascade",
      blockId: "retro_coin_cascade",
      blockString: "play coin cascade coins %coins||start pitch %startPitch | pausefor",
      group: "Special",
      weight: 98,
      problem: "You want a rewarding series of rising pings when opening a treasure chest full of coins.",
      whatItDoes: "Plays a rapid series of coin pickup pings that step up in pitch.",
      parameters: [
        { name: "coins", type: "number", default: "5", meaning: "Number of coin pings to play." },
        { name: "startPitch", type: "number", default: "800", meaning: "Starting pitch frequency." },
        { name: "pauseTime", type: "number", meaning: "Delay between each coin chime." },
      ],
      example: "Retro.coinCascade(6, 800, 50)",
    },
    {
      slug: "play-glitch",
      title: "play glitch",
      blockId: "retro_glitch",
      blockString: "play glitch intensity %intensity||bursts %bursts",
      group: "General",
      weight: 97,
      problem: "You want static noise bursts when a character takes corruption damage or touches a broken computer.",
      whatItDoes: "Plays a series of rapid noise bursts to simulate a retro glitch sound effect.",
      parameters: [
        { name: "intensity", type: "number", default: "5", meaning: "Volume and strength of noise bursts." },
        { name: "bursts", type: "number", default: "4", meaning: "Number of noise bursts." },
      ],
      example: "Retro.playGlitch(6, 5)",
    },
    {
      slug: "startup-jingle",
      title: "startup jingle",
      blockId: "retro_startup",
      blockString: "play retro startup jingle||base pitch %pitch speed %speed",
      group: "General",
      weight: 96,
      problem: "You want an ascending boot chime when your arcade game starts up.",
      whatItDoes: "Plays a classic 4-note ascending console boot jingle.",
      parameters: [
        { name: "pitch", type: "number", default: "400", meaning: "Base starting pitch frequency." },
        { name: "speed", type: "number", default: "80", meaning: "Delay between notes in milliseconds." },
      ],
      example: "Retro.startupJingle(400, 80)",
    },
    {
      slug: "parallax-camera",
      title: "parallax camera",
      blockId: "retro_parallax_camera",
      blockString: "parallax camera layer $layer factor $factor",
      group: "Camera",
      weight: 0,
      problem: "You want distant background layers to move slower than the player to create 3D visual depth.",
      whatItDoes: "Anchors a background layer sprite to camera movement scaled by a division factor.",
      parameters: [
        { name: "layer", type: "Sprite", default: "Layer", meaning: "Background layer sprite." },
        { name: "factor", type: "number", default: "3", meaning: "Movement scale division factor." },
      ],
      example: `let bg = sprites.create(img\`.\`, SpriteKind.UI)
Retro.parallaxCamera(bg, 3)`,
    },
    {
      slug: "flash-sprite",
      title: "flash sprite",
      blockId: "retro_flash_sprite",
      blockString: "flash sprite $sprite times $times||interval $interval",
      group: "Combat",
      weight: 89,
      problem: "You want a player sprite to flash briefly invisible and visible after taking damage.",
      whatItDoes: "Toggles sprite visibility on and off for a specified number of flashes.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Player", meaning: "Sprite to flash." },
        { name: "times", type: "number", default: "4", meaning: "Number of flash cycles." },
        { name: "interval", type: "number", default: "80", meaning: "Flash toggle speed in milliseconds." },
      ],
      example: `let player = sprites.create(img\`.\`, SpriteKind.Player)
Retro.flashSprite(player, 5, 60)`,
    },
    {
      slug: "screen-wrap",
      title: "screen wrap",
      blockId: "retro_screen_wrap",
      blockString: "enable screen wrap for $sprite",
      group: "General",
      weight: 85,
      problem: "You want arcade-style wrapping where moving past the left edge wraps the sprite over to the right edge.",
      whatItDoes: "Continuously wraps a sprite's position around screen borders.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Object", meaning: "Sprite to apply screen wrapping to." },
      ],
      example: `let player = sprites.create(img\`.\`, SpriteKind.Player)
Retro.screenWrap(player)`,
    },
    {
      slug: "enable-dash",
      title: "enable dash",
      blockId: "retro_enable_dash",
      blockString: "enable dash for $sprite speed $speed",
      group: "General",
      weight: 82,
      problem: "You want to register a sprite into the dash system.",
      whatItDoes: "Enables dash capability for a sprite.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Object", meaning: "Sprite to enable dash for." },
        { name: "speed", type: "number", default: "80", meaning: "Dash speed magnitude." },
      ],
      example: `let player = sprites.create(img\`.\`, SpriteKind.Player)
Retro.enableDash(player, 100)`,
    },
    {
      slug: "dash-cooldown",
      title: "dash cooldown",
      blockId: "retro_dash_cooldown",
      blockString: "dash $sprite speed $speed cooldown $cooldown ms",
      group: "General",
      weight: 81,
      problem: "You want a character to burst forward with extra velocity and then pause for a cooldown period.",
      whatItDoes: "Adds speed to a sprite's horizontal velocity and pauses for a cooldown duration.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Player", meaning: "Sprite performing the dash." },
        { name: "speed", type: "number", default: "100", meaning: "Speed added during dash." },
        { name: "cooldown", type: "number", default: "500", meaning: "Cooldown time in milliseconds." },
      ],
      example: `let player = sprites.create(img\`.\`, SpriteKind.Player)
Retro.dashCooldown(player, 120, 400)`,
    },
    {
      slug: "teleport-sprite",
      title: "teleport sprite",
      blockId: "retro_teleport_sprite",
      blockString: "teleport $sprite to x $x y $y",
      group: "General",
      weight: 80,
      problem: "You want a player or wizard enemy to instantly warp to new coordinates with sound feedback.",
      whatItDoes: "Moves a sprite to target screen coordinates and plays a teleport sound effect.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Object", meaning: "Sprite to teleport." },
        { name: "x", type: "number", meaning: "Target X position." },
        { name: "y", type: "number", meaning: "Target Y position." },
      ],
      example: `let player = sprites.create(img\`.\`, SpriteKind.Player)
Retro.teleportSprite(player, 120, 80)`,
    },
    {
      slug: "freeze-frame",
      title: "freeze frame",
      blockId: "retro_freeze_frame",
      blockString: "freeze frame $time ms",
      group: "Time",
      weight: 88,
      problem: "You want to pause gameplay for a split second on huge hits (hitstop) to make combat feel punchy.",
      whatItDoes: "Briefly halts game logic updates for a specified duration.",
      parameters: [
        { name: "time", type: "number", default: "60", meaning: "Freeze duration in milliseconds." },
      ],
      example: "Retro.freezeFrame(80)",
    },
    {
      slug: "increase-combo",
      title: "increase combo",
      blockId: "retro_increase_combo",
      blockString: "increase combo",
      group: "Combo",
      weight: 78,
      problem: "You want to track landing hits in a row and play punchier hit sound effects.",
      whatItDoes: "Increments the combo counter and plays an escalating hit sound.",
      parameters: [],
      example: "Retro.increaseCombo()",
    },
    {
      slug: "reset-combo",
      title: "reset combo",
      blockId: "retro_reset_combo",
      blockString: "reset combo",
      group: "Combo",
      weight: 77,
      problem: "You want to reset the hit combo counter when the player takes damage or misses an attack.",
      whatItDoes: "Resets the combo counter to 0.",
      parameters: [],
      example: "Retro.resetCombo()",
    },
    {
      slug: "floating-text",
      title: "floating text",
      blockId: "retro_floating_text",
      blockString: "floating text $text at $sprite",
      group: "Text",
      weight: 86,
      problem: "You want damage numbers or status text (like \"+100\" or \"CRIT!\") to pop up above a sprite.",
      whatItDoes: "Spawns a temporary text sprite above the target sprite that disappears after a short time.",
      parameters: [
        { name: "text", type: "string", meaning: "Text message to float." },
        { name: "sprite", type: "Sprite", meaning: "Sprite anchor location." },
      ],
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
Retro.floatingText("CRIT!", enemy)`,
    },
    {
      slug: "typewriter-text",
      title: "typewriter text",
      blockId: "retro_type_writer",
      blockString: "typewriter text $text pause per letter $pausePerCharacter at x $x y $y|| destroy after $destroyAfter",
      group: "Text",
      weight: 97,
      problem: "You want fancy text printed on screen letter-by-letter at specific coordinates.",
      whatItDoes: "Displays text letter-by-letter on screen at X/Y coordinates with character delays.",
      parameters: [
        { name: "text", type: "string", meaning: "Message text to print." },
        { name: "pausePerCharacter", type: "number", meaning: "Delay between typing each letter." },
        { name: "x", type: "number", default: "80", meaning: "X coordinate." },
        { name: "y", type: "number", default: "60", meaning: "Y coordinate." },
        { name: "destroyAfter", type: "number", meaning: "Optional duration before destroying text." },
      ],
      example: "Retro.typewriterText(\"Level 1\", 50, 80, 40, 1000)",
    },
    {
      slug: "knockback",
      title: "knockback",
      blockId: "retro_knockback",
      blockString: "knockback $sprite vx $vx vy $vy",
      group: "General",
      weight: 83,
      problem: "You want enemies or the player to get knocked backward when taking damage.",
      whatItDoes: "Sets a sprite's horizontal and vertical velocity to knock it backward.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Entity", meaning: "Sprite to knock back." },
        { name: "vx", type: "number", default: "-50", meaning: "Horizontal velocity change." },
        { name: "vy", type: "number", default: "-30", meaning: "Vertical velocity change." },
      ],
      example: `let player = sprites.create(img\`.\`, SpriteKind.Player)
Retro.knockback(player, -80, -40)`,
    },
    {
      slug: "smart-knockback",
      title: "smart knockback",
      blockId: "retro_smart_knockback",
      blockString: "smart knockback $sprite vx $vx vy $vy",
      group: "General",
      weight: 0,
      problem: "You want knockback direction to adjust automatically based on how the target is moving.",
      whatItDoes: "Adds knockback velocity aligned with the target sprite's current direction.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Object", meaning: "Target sprite." },
        { name: "vx", type: "number", default: "-50", meaning: "Horizontal knockback force." },
        { name: "vy", type: "number", default: "-30", meaning: "Vertical knockback force." },
      ],
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
Retro.smartKnockback(enemy, -60, -20)`,
    },
    {
      slug: "impact-sparks",
      title: "impact sparks",
      blockId: "retro_impact_sparks",
      blockString: "impact sparks x $x y $y count $count for $t || amount of particles $particlesPerSecond | diamter $d",
      group: "Hit",
      weight: 0,
      problem: "You want a burst of spark particles to shoot out when a weapon hits metal armor.",
      whatItDoes: "Creates custom particle spread impact spark effects at target coordinates.",
      parameters: [
        { name: "x", type: "number", default: "80", meaning: "X position for impact sparks." },
        { name: "y", type: "number", default: "60", meaning: "Y position for impact sparks." },
        { name: "count", type: "number", default: "6", meaning: "Number of particle bursts." },
        { name: "t", type: "number", default: "500", meaning: "Duration of effect in milliseconds." },
        { name: "particlesPerSecond", type: "number", default: "8", meaning: "Particles per second rate." },
        { name: "d", type: "number", default: "50", meaning: "Spread diameter." },
      ],
      example: "Retro.impactSparks(80, 60, 5, 500)",
    },
    {
      slug: "countdown",
      title: "countdown",
      blockId: "retro_countdown",
      blockString: "countdown $seconds seconds",
      group: "Game",
      weight: 79,
      problem: "You want a countdown timer displayed at the top of the screen during timed levels.",
      whatItDoes: "Starts the arcade info countdown timer for a given number of seconds.",
      parameters: [
        { name: "seconds", type: "number", default: "10", meaning: "Number of seconds to count down." },
      ],
      example: "Retro.countdown(30)",
    },
    {
      slug: "on-button-held",
      title: "on button held",
      blockId: "retro_button_hold",
      blockString: "on button $button held $time ms",
      group: "Input",
      weight: 75,
      problem: "You want a charged action to execute when a player holds a controller button down.",
      whatItDoes: "Runs a code block if the specified controller button stays held down after a time threshold.",
      parameters: [
        { name: "button", type: "controller.Button", meaning: "Controller button to monitor." },
        { name: "time", type: "number", default: "500", meaning: "Hold duration in milliseconds required." },
        { name: "handler", type: "() => void", meaning: "Code block to execute." },
      ],
      example: `Retro.onButtonHeld(controller.A, 500, function () {
    Retro.playRetroSound(Sounds.PowerCharged)
})`,
    },
    {
      slug: "retro-hit-impact",
      title: "retro hit impact",
      blockId: "retro_hit_impact",
      blockString: "retro hit impact strength $shake freeze $freeze",
      group: "Hit",
      weight: 95,
      problem: "You want hitstop freeze and camera shake combined when delivering a critical attack.",
      whatItDoes: "Shakes the camera and pauses execution simultaneously to produce hit impact feel.",
      parameters: [
        { name: "shake", type: "number", meaning: "Camera shake intensity." },
        { name: "freeze", type: "number", meaning: "Freeze pause time in milliseconds." },
      ],
      example: "Retro.retroHitImpact(4, 60)",
    },
    {
      slug: "jitter-pitch",
      title: "jitter pitch",
      blockId: "retro_jitter_pitch",
      blockString: "jitter pitch $pitch amount $amount",
      group: "Utility",
      weight: 39,
      problem: "You want pitch values to randomly shift slightly up or down to make sound effects feel less repetitive.",
      whatItDoes: "Returns a pitch value modified by a small random offset.",
      parameters: [
        { name: "pitch", type: "number", meaning: "Base pitch frequency." },
        { name: "amount", type: "number", default: "15", meaning: "Maximum random variation amount." },
      ],
      returns: { type: "number", meaning: "Pitch value with random jitter added." },
      example: `let pitch = Retro.jitterPitch(600, 20)
console.log(pitch)`,
    },
    {
      slug: "retro-dialog",
      title: "retro dialog",
      blockId: "retro_retro_dialog",
      blockString: "retro dialog $text at x $x y $y",
      group: "Dialog",
      weight: 0,
      problem: "You want small arcade-style pop-up text messages at specific positions on screen.",
      whatItDoes: "Creates a temporary text sprite at specified coordinates that lasts for 2 seconds.",
      parameters: [
        { name: "text", type: "string", meaning: "Text string to display." },
        { name: "x", type: "number", default: "80", meaning: "X screen coordinate." },
        { name: "y", type: "number", default: "40", meaning: "Y screen coordinate." },
      ],
      example: "Retro.retroDialog(\"Ready!\", 80, 40)",
    }
  ],
};
