import type { ExtensionDoc } from "@/content/extensions/types";

export const retrofx: ExtensionDoc = {
  owner: "CrzLe0723",
  repo: "RetroFx",
  displayName: "Retro FX",
  packageSlug: "github:CrzLe0723/RetroFx",
  description: "Add retro juice to your games with 8-bit sound effects, screen shakes, particle bursts, camera lag, combos, and vintage UI text effects.",
  tools: [
    {
      slug: "show-long-text",
      title: "show long text",
      blockId: "retro_skip_text",
      blockString: "skip text",
      group: "Dialog",
      weight: 0,
      problem: "You want an NPC or story cutscene to reveal dialogue one character at a time with retro typewriter or glitch effects.",
      whatItDoes: "Starts the internal retro text engine with the provided string, text speed, and visual animation style.",
      parameters: [
        { name: "text", type: "string", meaning: "The message to display." },
        { name: "speed", type: "number", meaning: "The typing speed in milliseconds between characters." },
        { name: "effect", type: "TextFx", meaning: "The animation effect (Typewriter, Scroll, Glitch, or Fade)." },
      ],
      example: "Retro.showLongText(\"Welcome to the dungeon!\", 50, Retro.TextFx.Typewriter)",
    },
    {
      slug: "get-text",
      title: "get text output",
      blockId: "retro_get_text",
      blockString: "get text output",
      group: "Dialog",
      weight: 100,
      problem: "You need to update a text sprite on screen with the characters that have been typed out so far by the text engine.",
      whatItDoes: "Returns the currently typed string from the active retro text engine.",
      parameters: [],
      returns: { type: "string", meaning: "The text characters currently revealed." },
      example: "let currentText = Retro.getText()",
    },
    {
      slug: "text-finished",
      title: "text finished",
      blockId: "retro_text_finished?",
      blockString: "text finished?",
      group: "Dialog",
      weight: 100,
      problem: "You want to wait until an NPC finishes speaking their line before letting the player move or press A to advance.",
      whatItDoes: "Returns true if the retro text engine has finished revealing all characters in the current message.",
      parameters: [],
      returns: { type: "boolean", meaning: "true if the text is completely done displaying, false otherwise." },
      example: `if (Retro.textFinished()) {
    console.log("Dialogue complete!")
}`,
    },
    {
      slug: "skip-text",
      title: "skip text",
      blockId: "retro_skip_text",
      blockString: "skip text",
      group: "Dialog",
      weight: 100,
      problem: "You want players to immediately see the full dialogue message when they press the action button instead of waiting for it to finish typing.",
      whatItDoes: "Instantly finishes revealing all characters in the active retro text engine.",
      parameters: [],
      example: `controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    Retro.skipText()
})`,
    },
    {
      slug: "play-retro-sound",
      title: "play retro sound",
      blockId: "retro_play_sound",
      blockString: "play retro sound $sound",
      group: "Sound",
      weight: 100,
      problem: "You want a classic 8-bit sound effect when the player picks up a coin, jumps, takes damage, or solves a puzzle.",
      whatItDoes: "Plays a preset 8-bit retro sound effect from the sound library.",
      parameters: [
        { name: "sound", type: "Sounds", meaning: "The preset retro sound effect to trigger." },
      ],
      example: "Retro.playRetroSound(Retro.Sounds.Coin)",
    },
    {
      slug: "quantize-pitch",
      title: "quantize pitch",
      blockId: "retro_quantize_pitch",
      blockString: "quantize pitch $pitch step $step",
      group: "Utility",
      weight: 40,
      problem: "You are generating procedural sound effects and want pitches to snap to musical or stepped intervals so they sound like vintage synth notes.",
      whatItDoes: "Rounds a pitch number to the nearest multiple of the specified step value.",
      parameters: [
        { name: "pitch", type: "number", meaning: "The raw pitch frequency in Hz." },
        { name: "step", type: "number", default: "50", meaning: "The step interval to snap the pitch to." },
      ],
      returns: { type: "number", meaning: "The quantized pitch frequency." },
      example: "let note = Retro.quantizePitch(432, 50)",
    },
    {
      slug: "envelope-sound",
      title: "play envelope sound",
      blockId: "retro_envelope_sound",
      blockString: "play envelope sound start pitch $startPitch end pitch $endPitch||attack $attack decay $decay sustain $sustain release $release",
      group: "Sound",
      weight: 93,
      problem: "You want to synthesize custom synth sounds for laser blasts or magic spells with specific attack, decay, sustain, and release timings.",
      whatItDoes: "Generates and plays a dynamic wave sound transitioning from a starting pitch to an ending pitch over customized ADSR envelope stages.",
      parameters: [
        { name: "startPitch", type: "number", default: "600", meaning: "The starting frequency in Hz." },
        { name: "endPitch", type: "number", default: "400", meaning: "The ending frequency in Hz." },
        { name: "attack", type: "number", default: "50", meaning: "Attack time in milliseconds." },
        { name: "decay", type: "number", default: "50", meaning: "Decay time in milliseconds." },
        { name: "sustain", type: "number", default: "180", meaning: "Sustain volume/level." },
        { name: "release", type: "number", default: "100", meaning: "Release time in milliseconds." },
      ],
      example: "Retro.envelopeSound(800, 200, 30, 40, 150, 80)",
    },
    {
      slug: "pitch-sweep",
      title: "play pitch sweep",
      blockId: "retro_pitch_sweep",
      blockString: "play pitch sweep start $startPitch end $endPitch duration $duration ms",
      group: "General",
      weight: 92,
      problem: "You need a rising sound for a power-up or a falling whistle sound when a character falls off a platform.",
      whatItDoes: "Plays a continuous pitch glide from a starting frequency to an ending frequency over a set duration.",
      parameters: [
        { name: "startPitch", type: "number", default: "1200", meaning: "The initial frequency in Hz." },
        { name: "endPitch", type: "number", default: "200", meaning: "The final frequency in Hz." },
        { name: "duration", type: "number", default: "120", meaning: "The duration of the sweep in milliseconds." },
      ],
      example: "Retro.pitchSweep(300, 900, 200)",
    },
    {
      slug: "play-sounds-together",
      title: "play sounds together",
      blockId: "retro_parallel_sounds",
      blockString: "play sounds together $a and $b",
      group: "Sound",
      weight: 91,
      problem: "You want two audio cues to trigger simultaneously, such as an explosion blast and a coin collection chime.",
      whatItDoes: "Plays two retro sound effects at the same time using parallel threads.",
      parameters: [
        { name: "a", type: "Sounds", meaning: "The first sound effect." },
        { name: "b", type: "Sounds", meaning: "The second sound effect." },
      ],
      example: "Retro.playSoundsTogether(Retro.Sounds.EnemyHit, Retro.Sounds.Coin)",
    },
    {
      slug: "play-sound-bank",
      title: "play random sound from bank",
      blockId: "retro_sound_bank",
      blockString: "play random sound from bank $sounds",
      group: "Variation",
      weight: 89,
      problem: "You want footstep sounds or sword swings to vary slightly each time so audio doesn't sound repetitive.",
      whatItDoes: "Picks and plays a random sound effect from a provided list of retro sounds.",
      parameters: [
        { name: "sounds", type: "Sounds[]", meaning: "An array of retro sounds to pick from." },
      ],
      example: "Retro.playSoundBank([Retro.Sounds.Jump, Retro.Sounds.DoubleJump, Retro.Sounds.WallJump])",
    },
    {
      slug: "play-sound-bank-variation",
      title: "play sound bank pitch variation",
      blockId: "retro_sound_bank_var",
      blockString: "play sound bank $sounds pitch variation $variation",
      group: "Variation",
      weight: 88,
      problem: "You want a sound effect from a bank to play with slightly altered pitch so every hit sounds unique.",
      whatItDoes: "Picks a sound from the array and synthesizes a tone with pitch jitter applied.",
      parameters: [
        { name: "sounds", type: "Sounds[]", meaning: "An array of retro sounds." },
        { name: "variation", type: "number", default: "20", meaning: "Maximum pitch fluctuation amount." },
      ],
      example: "Retro.playSoundBankVariation([Retro.Sounds.Hurt, Retro.Sounds.BreakBlock], 30)",
    },
    {
      slug: "play-sound-with-variation",
      title: "play variation",
      blockId: "retro_variation_sound",
      blockString: "play variation pitch $pitch duration $duration volume $volume",
      group: "Variation",
      weight: 80,
      problem: "You want an action like firing a blaster to have subtle volume, pitch, and duration randomness each shot.",
      whatItDoes: "Generates a wave sound with slight random variations in pitch, duration, and volume.",
      parameters: [
        { name: "pitch", type: "number", default: "600", meaning: "Base pitch frequency in Hz." },
        { name: "duration", type: "number", default: "100", meaning: "Base duration in milliseconds." },
        { name: "volume", type: "number", default: "120", meaning: "Base volume level (0 to 255)." },
      ],
      example: "Retro.playSoundWithVariation(500, 80, 150)",
    },
    {
      slug: "probability-event",
      title: "with chance do",
      blockId: "retro_probability_event",
      blockString: "with $chance % chance do",
      group: "Variation",
      weight: 98,
      problem: "You want a defeated enemy to have a 25% chance of dropping a rare power-up.",
      whatItDoes: "Executes a block of code based on a percentage chance between 1% and 100%.",
      parameters: [
        { name: "chance", type: "number", default: "50", meaning: "The percentage chance (0 to 100) for the handler to run." },
        { name: "handler", type: "() => void", meaning: "The code to run if the percentage check succeeds." },
      ],
      example: `Retro.probabilityEvent(25, function () {
    Retro.playRetroSound(Retro.Sounds.RareItem)
})`,
    },
    {
      slug: "velocity-variation",
      title: "velocity variation",
      blockId: "retro_velocity_variation",
      blockString: "velocity variation from $velocity min $min max $max",
      group: "Variation",
      weight: 97,
      problem: "You want a landing sound or particle burst to scale up based on how fast the player was falling.",
      whatItDoes: "Calculates the absolute value of a velocity and clamps it between a minimum and maximum range.",
      parameters: [
        { name: "velocity", type: "number", default: "50", meaning: "The sprite's velocity value." },
        { name: "min", type: "number", default: "0", meaning: "The lower bound for the output value." },
        { name: "max", type: "number", default: "100", meaning: "The upper bound for the output value." },
      ],
      returns: { type: "number", meaning: "The clamped velocity intensity." },
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
let power = Retro.velocityVariation(mySprite.vy, 10, 100)`,
    },
    {
      slug: "variation-table",
      title: "variation from table",
      blockId: "retro_variation_table",
      blockString: "variation from table $values",
      group: "Variation",
      weight: 96,
      problem: "You want to choose randomly between a fixed set of damage multipliers or bounce velocities.",
      whatItDoes: "Selects and returns a random number from an array of numeric values.",
      parameters: [
        { name: "values", type: "number[]", meaning: "The list of numbers to pick from." },
      ],
      returns: { type: "number", meaning: "A randomly selected number from the array, or 0 if empty." },
      example: "let damage = Retro.variationTable([10, 15, 20, 50])",
    },
    {
      slug: "play-dash",
      title: "play dash sound",
      blockId: "retro_dash_sound",
      blockString: "play dash sound speed $speed",
      group: "Dynamic",
      weight: 70,
      problem: "You want the dash sound pitch to change dynamically depending on how fast the player is dashing.",
      whatItDoes: "Plays a synthesized dash sound where higher speeds produce a higher pitch.",
      parameters: [
        { name: "speed", type: "number", default: "100", meaning: "The dash speed to base the sound pitch on." },
      ],
      example: "Retro.playDash(150)",
    },
    {
      slug: "play-jump",
      title: "play jump sound",
      blockId: "retro_jump_sound",
      blockString: "play jump sound force $force",
      group: "Dynamic",
      weight: 69,
      problem: "You want big high jumps to make a higher pitched sound than small hops.",
      whatItDoes: "Plays a jump sound whose pitch scales with the jump force provided.",
      parameters: [
        { name: "force", type: "number", default: "50", meaning: "The jump force determining pitch." },
      ],
      example: "Retro.playJump(75)",
    },
    {
      slug: "play-enemy-hit",
      title: "play enemy hit combo sound",
      blockId: "retro_enemy_hit",
      blockString: "play enemy hit combo $combo",
      group: "Dynamic",
      weight: 68,
      problem: "You want combat hits to sound increasingly intense as the player's hit combo counter increases.",
      whatItDoes: "Plays an enemy hit sound with a pitch that rises with higher combo numbers.",
      parameters: [
        { name: "combo", type: "number", default: "1", meaning: "The current combo count." },
      ],
      example: "Retro.playEnemyHit(3)",
    },
    {
      slug: "play-charge",
      title: "play charge sound",
      blockId: "retro_charge_sound",
      blockString: "play charge sound charge $charge max $maxCharge",
      group: "Dynamic",
      weight: 67,
      problem: "You want a charging attack or mega-laser to ramp up in tone as the player holds down the attack button.",
      whatItDoes: "Plays a sound with a pitch mapped proportionally to the current charge level against maximum charge.",
      parameters: [
        { name: "charge", type: "number", default: "0", meaning: "The current charge amount." },
        { name: "maxCharge", type: "number", default: "100", meaning: "The maximum charge threshold." },
      ],
      example: "Retro.playCharge(75, 100)",
    },
    {
      slug: "camera-follow-lag",
      title: "camera follow lag",
      blockId: "retro_camera_follow_lag",
      blockString: "camera follow $sprite lag $lag",
      group: "Camera",
      weight: 84,
      problem: "You want smooth, cinematic camera movement that gently catches up to the player instead of snapping rigidly.",
      whatItDoes: "Smooths camera tracking on a target sprite using linear interpolation lag on each game update.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Player", meaning: "The sprite the camera should smoothly follow." },
        { name: "lag", type: "number", default: "4", meaning: "Lag damping factor (higher numbers mean slower, smoother camera catch-up)." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
controller.moveSprite(mySprite)
Retro.cameraFollowLag(mySprite, 6)`,
    },
    {
      slug: "camera-punch",
      title: "camera punch",
      blockId: "retro_camera_punch",
      blockString: "camera punch for $sprite intensity $intensity duration $duration ms",
      group: "Effects",
      weight: 0,
      problem: "You want a quick, jarring camera jolt when the player delivers a heavy melee punch or parry.",
      whatItDoes: "Offsets the camera randomly by an intensity amount, pauses briefly, and returns the camera to its original spot.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Object", meaning: "The target sprite causing the punch." },
        { name: "intensity", type: "number", default: "4", meaning: "Maximum pixel offset for the punch." },
        { name: "duration", type: "number", default: "60", meaning: "Duration of the offset in milliseconds before snapping back." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Retro.cameraPunch(mySprite, 6, 80)`,
    },
    {
      slug: "play-random-sound",
      title: "play random retro sound",
      blockId: "retro_random_sound",
      blockString: "play random retro sound",
      group: "Sound",
      weight: 95,
      problem: "You want a completely random arcade sound effect for a mystery box or glitch trigger.",
      whatItDoes: "Selects and plays a random sound effect from the entire retro sound table.",
      parameters: [],
      example: "Retro.playRandomSound()",
    },
    {
      slug: "float-control",
      title: "float movement",
      blockId: "retro_float_control",
      blockString: "float movement %sprite factor %value",
      group: "Movement",
      weight: 0,
      problem: "You want to define floaty gravity or swimming movement parameters for a player sprite.",
      whatItDoes: "Configures float movement properties for the specified sprite.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Player", meaning: "The sprite to apply float control to." },
        { name: "value", type: "number", default: "200", meaning: "The float movement factor." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Retro.floatControl(mySprite, 150)`,
    },
    {
      slug: "input-buffer",
      title: "input buffer",
      blockId: "retro_input_buffer",
      blockString: "input buffer handler %handler buffer $bufferTime ms",
      group: "Input",
      weight: 0,
      problem: "You want button presses during animations to be saved and executed right when the animation finishes.",
      whatItDoes: "Queues an action callback into an input buffer and executes it after the specified buffer delay.",
      parameters: [
        { name: "handler", type: "() => void", meaning: "The action function to queue and run." },
        { name: "bufferTime", type: "number", default: "200", meaning: "The buffer window in milliseconds." },
      ],
      example: `Retro.inputBuffer(function () {
    Retro.playRetroSound(Retro.Sounds.Jump)
}, 150)`,
    },
    {
      slug: "screen-vignette",
      title: "screen vignette",
      blockId: "retro_screen_vignette",
      blockString: "screen vignette intensity $intensity",
      group: "Camera",
      weight: 0,
      problem: "You want to darken the edges of the screen during low health or when entering a dark dungeon.",
      whatItDoes: "Creates a bordered background overlay around the screen to simulate a vintage vignette.",
      parameters: [
        { name: "intensity", type: "number", default: "80", meaning: "The border frame color index or intensity." },
      ],
      example: "Retro.screenVignette(15)",
    },
    {
      slug: "set-speed",
      title: "set speed",
      blockString: "set speed to $speed",
      group: "Movement",
      weight: 0,
      problem: "You want to configure the movement speed baseline for character state systems.",
      whatItDoes: "Sets the speed parameter for sprite movement mechanics.",
      parameters: [
        { name: "speed", type: "number", default: "50", meaning: "The target movement speed." },
      ],
      example: "Retro.setSpeed(75)",
    },
    {
      slug: "pixel-dissolve",
      title: "pixel dissolve",
      blockId: "retro_pixel_dissolve",
      blockString: "pixel dissolve $sprite duration $duration ms",
      group: "Effects",
      weight: 0,
      problem: "You want a boss or enemy to disintegrate pixel-by-pixel into dust when defeated.",
      whatItDoes: "Gradually erases random pixels from a sprite's image over time before destroying the sprite.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Entity", meaning: "The sprite to dissolve." },
        { name: "duration", type: "number", default: "400", meaning: "Total duration of the dissolve effect in milliseconds." },
      ],
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
Retro.pixelDissolve(enemy, 500)`,
    },
    {
      slug: "play-custom-sound",
      title: "play retro sound volume pitch",
      blockId: "retro_custom_sound",
      blockString: "play retro sound $sound volume $volume pitch $pitch",
      group: "Sound",
      weight: 94,
      problem: "You want to use a preset sound like a laser or jump, but with custom volume and tuned frequency.",
      whatItDoes: "Plays a retro sound alongside a synthesized wave at the specified volume and pitch.",
      parameters: [
        { name: "sound", type: "Sounds", meaning: "The preset retro sound to trigger." },
        { name: "volume", type: "number", default: "120", meaning: "The playback volume level." },
        { name: "pitch", type: "number", default: "600", meaning: "The sound frequency in Hz." },
      ],
      example: "Retro.playCustomSound(Retro.Sounds.LaserHit, 200, 850)",
    },
    {
      slug: "loop-sound",
      title: "loop retro sound",
      blockId: "retro_loop_sound",
      blockString: "loop retro sound $sound",
      group: "Utility",
      weight: 80,
      problem: "You want an alarm siren or charging drone sound to loop continuously while an event is active.",
      whatItDoes: "Plays the specified retro sound in a continuous loop until stopped.",
      parameters: [
        { name: "sound", type: "Sounds", meaning: "The sound effect to loop." },
      ],
      example: "Retro.loopSound(Retro.Sounds.LowHealthPulse)",
    },
    {
      slug: "stop-sounds",
      title: "stop retro sounds",
      blockId: "retro_stop_sound",
      blockString: "stop retro sounds",
      group: "Utility",
      weight: 79,
      problem: "You want all active sound effects and loops to cut off immediately when the game transitions to a new level or game over.",
      whatItDoes: "Stops all currently playing and looping sound effects.",
      parameters: [],
      example: "Retro.stopSounds()",
    },
    {
      slug: "sequence-sounds",
      title: "play sound sequence",
      blockId: "retro_sequence_sound",
      blockString: "play sound sequence $first then $second",
      group: "Utility",
      weight: 78,
      problem: "You want a two-part sound effect—such as a key unlocking a door followed immediately by the door opening.",
      whatItDoes: "Plays the first sound until done, then immediately starts playback of the second sound.",
      parameters: [
        { name: "first", type: "Sounds", meaning: "The first sound to play." },
        { name: "second", type: "Sounds", meaning: "The second sound to play after the first finishes." },
      ],
      example: "Retro.sequenceSounds(Retro.Sounds.KeyObtained, Retro.Sounds.DoorOpen)",
    },
    {
      slug: "reactive-sound",
      title: "reactive sound",
      blockId: "retro_reactive_sound",
      blockString: "reactive sound value $value min $min max $max",
      group: "Dynamic",
      weight: 70,
      problem: "You want a vehicle engine sound to change pitch smoothly according to a speedometer reading.",
      whatItDoes: "Maps a numeric value between a minimum and maximum range onto pitch frequencies from 300 to 900 Hz.",
      parameters: [
        { name: "value", type: "number", default: "50", meaning: "The input value to map." },
        { name: "min", type: "number", default: "0", meaning: "The minimum possible input value." },
        { name: "max", type: "number", default: "100", meaning: "The maximum possible input value." },
      ],
      example: `let fuel = 45
Retro.reactiveSound(fuel, 0, 100)`,
    },
    {
      slug: "set-pause-mode",
      title: "set retro sound pause mode",
      blockId: "retro_pause_toggle",
      blockString: "set retro sound pause mode $state",
      group: "Utility",
      weight: 60,
      problem: "You want retro sounds to block code execution until they finish playing rather than running in the background.",
      whatItDoes: "Toggles whether sounds play asynchronously or pause execution until playback completes.",
      parameters: [
        { name: "state", type: "boolean", meaning: "true to wait for sounds to finish, false to play them asynchronously." },
      ],
      example: "Retro.setPauseMode(true)",
    },
    {
      slug: "set-global-volume",
      title: "set global retro volume",
      blockId: "retro_global_volume",
      blockString: "set global retro volume $volume",
      group: "Sound",
      weight: 90,
      problem: "You are building an options menu and want the player to adjust the master sound volume.",
      whatItDoes: "Adjusts the global volume level for all game music and sound effects.",
      parameters: [
        { name: "volume", type: "number", meaning: "Volume level from 0 (silent) to 255 (maximum)." },
      ],
      example: "Retro.setGlobalVolume(180)",
    },
    {
      slug: "play-combo",
      title: "play retro combo",
      blockId: "retro_combo_sound",
      blockString: "play retro combo $combo",
      group: "Combo",
      weight: 85,
      problem: "You want a stylized multi-note fanfare when the player levels up, solves a puzzle, or finds a rare treasure.",
      whatItDoes: "Plays a pre-arranged sequence of layered retro sounds representing a major game event.",
      parameters: [
        { name: "combo", type: "SoundCombos", meaning: "The preset combo to play (LevelUp, RareItem, EnemyDefeated, or PuzzleSolved)." },
      ],
      example: "Retro.playCombo(Retro.SoundCombos.LevelUp)",
    },
    {
      slug: "spawn-effect",
      title: "spawn effect",
      blockId: "retro_particles",
      blockString: "spawn effect $effect at x $x y $y",
      group: "Effect",
      weight: 0,
      problem: "You want a particle burst when an enemy dies, a switch flips, or a key is picked up.",
      whatItDoes: "Spawns a styled spread particle effect at specified coordinates on the screen.",
      parameters: [
        { name: "effect", type: "Effects", meaning: "The visual effect preset to spawn." },
        { name: "x", type: "number", meaning: "The horizontal screen position." },
        { name: "y", type: "number", meaning: "The vertical screen position." },
      ],
      example: "Retro.spawnEffect(Retro.Effects.HitSpark, 80, 60)",
    },
    {
      slug: "play-explosion",
      title: "play 8-bit explosion",
      blockId: "retro_explosion",
      blockString: "play 8-bit explosion power %power||pitch %pitch duration %duration",
      group: "Special",
      weight: 100,
      problem: "You want a crunchy 8-bit noise blast when a bomb or missile blows up.",
      whatItDoes: "Synthesizes a tunable noise explosion sound with customizable power, pitch, and duration.",
      parameters: [
        { name: "power", type: "number", default: "5", meaning: "The explosion loudness and strength factor." },
        { name: "pitch", type: "number", default: "200", meaning: "The base noise pitch." },
        { name: "duration", type: "number", default: "300", meaning: "The length of the explosion in milliseconds." },
      ],
      example: "Retro.playExplosion(6, 180, 400)",
    },
    {
      slug: "trail-effect",
      title: "add trail to sprite",
      blockId: "retro_trail_effect",
      blockString: "add trail to $sprite image $img interval $interval ms",
      group: "Effect",
      weight: 96,
      problem: "You want the player or a fast projectile to leave a glowing afterimage trail behind as it moves.",
      whatItDoes: "Repeatedly spawns temporary image clones at the sprite's position at a given time interval.",
      parameters: [
        { name: "sprite", type: "Sprite", meaning: "The sprite that leaves the trail." },
        { name: "img", type: "Image", meaning: "The trail particle image." },
        { name: "interval", type: "number", default: "50", meaning: "Milliseconds between each spawned trail sprite." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Retro.trailEffect(mySprite, img\`.\`, 60)`,
    },
    {
      slug: "screen-ripple",
      title: "screen ripple",
      blockId: "retro_screen_ripple",
      blockString: "screen ripple strength $strength duration $duration ms",
      group: "Effects",
      weight: 99,
      problem: "You want the screen to shudder repeatedly when an earthquake strikes or a huge boss walks.",
      whatItDoes: "Shakes the camera continuously in short pulses over the specified duration.",
      parameters: [
        { name: "strength", type: "number", default: "3", meaning: "The shake amplitude in pixels." },
        { name: "duration", type: "number", default: "200", meaning: "Total ripple time in milliseconds." },
      ],
      example: "Retro.screenRipple(4, 300)",
    },
    {
      slug: "screen-flash",
      title: "screen flash",
      blockId: "retro_screen_flash",
      blockString: "screen flash to white for $duration,pause for $pauseTime",
      group: "Effect",
      weight: 100,
      problem: "You want a dramatic white flash when lightning strikes or a super-move detonates.",
      whatItDoes: "Fades the screen palette to white and then restores the original palette after a pause.",
      parameters: [
        { name: "pauseTime", type: "number", meaning: "How long in milliseconds the screen stays white before fading back." },
        { name: "duration", type: "number", default: "120", meaning: "The fade transition duration in milliseconds." },
      ],
      example: "Retro.screenFlash(100, 80)",
    },
    {
      slug: "play-laser",
      title: "play laser",
      blockId: "retro_laser",
      blockString: "play laser intensity %intensity||start pitch %startPitch end pitch %endPitch",
      group: "Special",
      weight: 99,
      problem: "You want an arcade blaster sound whenever the spaceship shoots a laser bolt.",
      whatItDoes: "Synthesizes an 8-bit laser chirp dropping rapidly from a start pitch to an end pitch.",
      parameters: [
        { name: "intensity", type: "number", default: "4", meaning: "The laser volume intensity level." },
        { name: "startPitch", type: "number", default: "1200", meaning: "The starting pitch in Hz." },
        { name: "endPitch", type: "number", default: "300", meaning: "The ending pitch in Hz." },
      ],
      example: "Retro.playLaser(5, 1400, 200)",
    },
    {
      slug: "coin-cascade",
      title: "play coin cascade",
      blockId: "retro_coin_cascade",
      blockString: "play coin cascade coins %coins||start pitch %startPitch | pausefor",
      group: "Special",
      weight: 98,
      problem: "You want a rewarding series of rising coin chimes when the player opens a treasure chest with multiple gems.",
      whatItDoes: "Plays a rapid sequence of ascending coin pings spaced out by a brief pause.",
      parameters: [
        { name: "coins", type: "number", default: "5", meaning: "The number of coin pings to play." },
        { name: "startPitch", type: "number", default: "800", meaning: "The starting pitch of the first coin ping." },
        { name: "pauseTime", type: "number", meaning: "Pause duration in milliseconds between coin pings." },
      ],
      example: "Retro.coinCascade(6, 900, 50)",
    },
    {
      slug: "play-glitch",
      title: "play glitch",
      blockId: "retro_glitch",
      blockString: "play glitch intensity %intensity||bursts %bursts",
      group: "General",
      weight: 97,
      problem: "You want a distorted static sound when a computer terminal fails or the game enters a glitch zone.",
      whatItDoes: "Plays rapid bursts of random tunable noise frequencies to create an 8-bit glitch sound.",
      parameters: [
        { name: "intensity", type: "number", default: "5", meaning: "The volume strength of the glitch." },
        { name: "bursts", type: "number", default: "4", meaning: "The number of quick noise bursts." },
      ],
      example: "Retro.playGlitch(6, 5)",
    },
    {
      slug: "startup-jingle",
      title: "play retro startup jingle",
      blockId: "retro_startup",
      blockString: "play retro startup jingle||base pitch %pitch speed %speed",
      group: "General",
      weight: 96,
      problem: "You want an iconic boot-up arpeggio when your game title screen loads.",
      whatItDoes: "Plays a 4-note ascending arcade console jingle.",
      parameters: [
        { name: "pitch", type: "number", default: "400", meaning: "The root pitch in Hz." },
        { name: "speed", type: "number", default: "80", meaning: "Milliseconds between notes." },
      ],
      example: "Retro.startupJingle(440, 90)",
    },
    {
      slug: "parallax-camera",
      title: "parallax camera layer",
      blockId: "retro_parallax_camera",
      blockString: "parallax camera layer $layer factor $factor",
      group: "Camera",
      weight: 0,
      problem: "You want distant mountains or background clouds to move slower than the foreground for a 2.5D depth effect.",
      whatItDoes: "Updates a background layer sprite's coordinates relative to camera position divided by a parallax factor.",
      parameters: [
        { name: "layer", type: "Sprite", default: "Layer", meaning: "The background sprite to scroll." },
        { name: "factor", type: "number", default: "3", meaning: "The parallax depth divider (higher numbers mean slower background movement)." },
      ],
      example: `let background = sprites.create(img\`.\`, SpriteKind.UI)
Retro.parallaxCamera(background, 4)`,
    },
    {
      slug: "flash-sprite",
      title: "flash sprite",
      blockId: "retro_flash_sprite",
      blockString: "flash sprite $sprite times $times||interval $interval",
      group: "Combat",
      weight: 89,
      problem: "You want the player sprite to blink invisibly during invincibility frames after getting hurt.",
      whatItDoes: "Toggles a sprite's visibility on and off for a specified number of cycles.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Player", meaning: "The sprite to flash." },
        { name: "times", type: "number", default: "4", meaning: "How many times the sprite will blink." },
        { name: "interval", type: "number", default: "80", meaning: "Duration in milliseconds for each blink phase." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Retro.flashSprite(mySprite, 5, 60)`,
    },
    {
      slug: "screen-wrap",
      title: "enable screen wrap",
      blockId: "retro_screen_wrap",
      blockString: "enable screen wrap for $sprite",
      group: "General",
      weight: 85,
      problem: "You are building an Asteroids-style game where flying off the left side of the screen should wrap the player to the right side.",
      whatItDoes: "Continuously checks the sprite's position on game update and loops it back when it leaves screen bounds.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Object", meaning: "The sprite that will wrap around screen borders." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Retro.screenWrap(mySprite)`,
    },
    {
      slug: "enable-dash",
      title: "enable dash",
      blockId: "retro_enable_dash",
      blockString: "enable dash for $sprite speed $speed",
      group: "General",
      weight: 82,
      problem: "You want to register a sprite into the system so it can perform dash movements at a set speed.",
      whatItDoes: "Registers a sprite into the internal dash system with a assigned dash speed value.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Object", meaning: "The sprite to grant dash capabilities." },
        { name: "speed", type: "number", default: "80", meaning: "The configured dash speed." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Retro.enableDash(mySprite, 100)`,
    },
    {
      slug: "dash-cooldown",
      title: "dash cooldown",
      blockId: "retro_dash_cooldown",
      blockString: "dash $sprite speed $speed cooldown $cooldown ms",
      group: "General",
      weight: 81,
      problem: "You want the player to dash forward quickly with extra velocity and wait through a cooldown before another action.",
      whatItDoes: "Increases the sprite's horizontal velocity by a dash speed and pauses for the cooldown duration.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Player", meaning: "The sprite to dash." },
        { name: "speed", type: "number", default: "100", meaning: "Velocity boost to add." },
        { name: "cooldown", type: "number", default: "500", meaning: "Cooldown pause time in milliseconds." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Retro.dashCooldown(mySprite, 120, 400)`,
    },
    {
      slug: "teleport-sprite",
      title: "teleport sprite",
      blockId: "retro_teleport_sprite",
      blockString: "teleport $sprite to x $x y $y",
      group: "General",
      weight: 80,
      problem: "You want an enemy or player to instantly warp to new coordinates with an accompanying teleport sound effect.",
      whatItDoes: "Moves the sprite directly to coordinates (x, y) and plays the retro teleport sound.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Object", meaning: "The sprite to teleport." },
        { name: "x", type: "number", meaning: "Target X screen coordinate." },
        { name: "y", type: "number", meaning: "Target Y screen coordinate." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Retro.teleportSprite(mySprite, 80, 60)`,
    },
    {
      slug: "freeze-frame",
      title: "freeze frame",
      blockId: "retro_freeze_frame",
      blockString: "freeze frame $time ms",
      group: "Time",
      weight: 88,
      problem: "You want \"hitstop\"—a momentary game pause right when a critical strike connects to give your combat weight.",
      whatItDoes: "Sets delta time to zero and pauses the game thread briefly to create a freeze-frame hitstop effect.",
      parameters: [
        { name: "time", type: "number", default: "60", meaning: "Duration of the hitstop freeze in milliseconds." },
      ],
      example: "Retro.freezeFrame(75)",
    },
    {
      slug: "increase-combo",
      title: "increase combo",
      blockId: "retro_increase_combo",
      blockString: "increase combo",
      group: "Combo",
      weight: 78,
      problem: "You want the player's attack combo counter to increment and play an ascending hit sound as they chain attacks.",
      whatItDoes: "Increases the global combo count by 1 and plays the corresponding enemy hit sound.",
      parameters: [],
      example: "Retro.increaseCombo()",
    },
    {
      slug: "reset-combo",
      title: "reset combo",
      blockId: "retro_reset_combo",
      blockString: "reset combo",
      group: "Combo",
      weight: 77,
      problem: "You want the hit combo counter to drop back to zero when the player misses or takes damage.",
      whatItDoes: "Resets the internal combo counter back to 0.",
      parameters: [],
      example: "Retro.resetCombo()",
    },
    {
      slug: "floating-text",
      title: "floating text",
      blockId: "retro_floating_text",
      blockString: "floating text $text at $sprite",
      group: "Text",
      weight: 86,
      problem: "You want RPG damage numbers like \"+50 XP\" or \"-12\" to pop up over a sprite and disappear.",
      whatItDoes: "Creates a temporary text sprite directly above the target sprite that vanishes after 800 milliseconds.",
      parameters: [
        { name: "text", type: "string", meaning: "The message or damage number to show." },
        { name: "sprite", type: "Sprite", meaning: "The sprite over which the text should appear." },
      ],
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
Retro.floatingText("-25 HP", enemy)`,
    },
    {
      slug: "typewriter-text",
      title: "typewriter text",
      blockId: "retro_type_writer",
      blockString: "typewriter text $text pause per letter $pausePerCharacter at x $x y $y|| destroy after $destroyAfter",
      group: "Text",
      weight: 97,
      problem: "You want a subtitle or mission objective to type out letter-by-letter on screen and optionally vanish.",
      whatItDoes: "Animates text onto the screen one character at a time with a pause per letter and optional auto-destruction.",
      parameters: [
        { name: "text", type: "string", meaning: "The text string to type out." },
        { name: "pausePerCharacter", type: "number", meaning: "Delay in milliseconds between each letter." },
        { name: "x", type: "number", default: "80", meaning: "Horizontal position." },
        { name: "y", type: "number", default: "60", meaning: "Vertical position." },
        { name: "destroyAfter", type: "number", meaning: "Optional duration in milliseconds after completion before removing the text." },
      ],
      example: "Retro.typewriterText(\"STAGE 1: FOREST\", 50, 80, 20, 2000)",
    },
    {
      slug: "knockback",
      title: "knockback",
      blockId: "retro_knockback",
      blockString: "knockback $sprite vx $vx vy $vy",
      group: "General",
      weight: 83,
      problem: "You want an enemy or player to be violently shoved backwards and into the air when struck by a melee attack.",
      whatItDoes: "Directly sets the sprite's X and Y velocities to launch it in a knockback direction.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Entity", meaning: "The sprite to apply knockback to." },
        { name: "vx", type: "number", default: "-50", meaning: "Horizontal knockback velocity." },
        { name: "vy", type: "number", default: "-30", meaning: "Vertical knockback velocity." },
      ],
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
Retro.knockback(enemy, -80, -40)`,
    },
    {
      slug: "smart-knockback",
      title: "smart knockback",
      blockId: "retro_smart_knockback",
      blockString: "smart knockback $sprite vx $vx vy $vy",
      group: "General",
      weight: 0,
      problem: "You want knockback force to automatically apply in the direction the sprite is facing or moving.",
      whatItDoes: "Multiplies the horizontal force by the direction of the sprite's current velocity and applies vertical impulse.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "Object", meaning: "The sprite to knock back." },
        { name: "vx", type: "number", default: "-50", meaning: "Base horizontal force magnitude." },
        { name: "vy", type: "number", default: "-30", meaning: "Vertical impulse force." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
Retro.smartKnockback(mySprite, -60, -30)`,
    },
    {
      slug: "impact-sparks",
      title: "impact sparks",
      blockId: "retro_impact_sparks",
      blockString: "impact sparks x $x y $y count $count for $t || amount of particles $particlesPerSecond | diamter $d",
      group: "Hit",
      weight: 0,
      problem: "You want a shower of sparks to fly off an enemy shield when a weapon strikes it.",
      whatItDoes: "Spawns multiple spread spark particle effects at a target position with custom particle count, duration, and diameter.",
      parameters: [
        { name: "x", type: "number", default: "80", meaning: "X coordinate for the sparks." },
        { name: "y", type: "number", default: "60", meaning: "Y coordinate for the sparks." },
        { name: "count", type: "number", default: "6", meaning: "Number of spark waves to spawn." },
        { name: "t", type: "number", default: "500", meaning: "Duration of each spark wave in milliseconds." },
        { name: "particlesPerSecond", type: "number", default: "8", meaning: "Rate of particles spawned per second." },
        { name: "d", type: "number", default: "50", meaning: "Spread diameter in pixels." },
      ],
      example: "Retro.impactSparks(80, 60, 4, 400, 10, 60)",
    },
    {
      slug: "countdown",
      title: "countdown",
      blockId: "retro_countdown",
      blockString: "countdown $seconds seconds",
      group: "Game",
      weight: 79,
      problem: "You want a timed mini-game challenge where the player has 15 seconds to collect all coins.",
      whatItDoes: "Starts MakeCode Arcade's built-in countdown clock for the specified number of seconds.",
      parameters: [
        { name: "seconds", type: "number", default: "10", meaning: "Number of seconds on the timer." },
      ],
      example: "Retro.countdown(30)",
    },
    {
      slug: "on-button-held",
      title: "on button held",
      blockId: "retro_button_hold",
      blockString: "on button $button held $time ms",
      group: "Input",
      weight: 75,
      problem: "You want a charged jump or heavy power attack to trigger only when the player holds a button down for half a second.",
      whatItDoes: "Listens for a button press, waits for the hold time, and runs the action handler if the button is still held.",
      parameters: [
        { name: "button", type: "controller.Button", meaning: "The controller button to monitor." },
        { name: "time", type: "number", default: "500", meaning: "Hold threshold time in milliseconds." },
        { name: "handler", type: "() => void", meaning: "The callback function to run when successfully held." },
      ],
      example: `Retro.onButtonHeld(controller.A, 600, function () {
    Retro.playRetroSound(Retro.Sounds.PowerCharged)
})`,
    },
    {
      slug: "retro-hit-impact",
      title: "retro hit impact",
      blockId: "retro_hit_impact",
      blockString: "retro hit impact strength $shake freeze $freeze",
      group: "Hit",
      weight: 95,
      problem: "You want a boss hit to feel heavy by combining a sharp screen shake with a brief freeze pause.",
      whatItDoes: "Triggers a camera shake of given strength and pauses execution for the freeze duration.",
      parameters: [
        { name: "shake", type: "number", meaning: "Screen shake intensity in pixels." },
        { name: "freeze", type: "number", meaning: "Freeze duration in milliseconds." },
      ],
      example: "Retro.retroHitImpact(5, 100)",
    },
    {
      slug: "jitter-pitch",
      title: "jitter pitch",
      blockId: "retro_jitter_pitch",
      blockString: "jitter pitch $pitch amount $amount",
      group: "Utility",
      weight: 39,
      problem: "You are synthesizing custom sound effects and want slight pitch randomness to make sounds less robotic.",
      whatItDoes: "Adds a random offset between -amount and +amount to the provided pitch value.",
      parameters: [
        { name: "pitch", type: "number", meaning: "Base pitch in Hz." },
        { name: "amount", type: "number", default: "15", meaning: "Maximum random variation range." },
      ],
      returns: { type: "number", meaning: "The pitch with random jitter applied." },
      example: "let pitch = Retro.jitterPitch(600, 25)",
    },
    {
      slug: "retro-dialog",
      title: "retro dialog",
      blockId: "retro_retro_dialog",
      blockString: "retro dialog $text at x $x y $y",
      group: "Dialog",
      weight: 0,
      problem: "You want a quick speech bubble text line to appear at an NPC's location and automatically vanish after 2 seconds.",
      whatItDoes: "Spawns a retro text sprite at (x, y) with small font height and a 2-second lifespan.",
      parameters: [
        { name: "text", type: "string", meaning: "The dialogue message." },
        { name: "x", type: "number", default: "80", meaning: "Horizontal position." },
        { name: "y", type: "number", default: "40", meaning: "Vertical position." },
      ],
      example: "Retro.retroDialog(\"It's dangerous outside!\", 80, 40)",
    }
  ],
};
