import type { ExtensionDoc } from "@/content/extensions/types";

export const arcadeSplitScreen: ExtensionDoc = {
  owner: "riknoll",
  repo: "arcade-split-screen",
  displayName: "Split Screen",
  packageSlug: "github:riknoll/arcade-split-screen",
  description: "Create two-player local multiplayer or picture-in-picture camera views in MakeCode Arcade games.",
  tools: [
    {
      slug: "split-screen-camera-follow",
      title: "split screen camera follow",
      blockId: "splitscreencamerafollowsprite",
      blockString: "split screen camera follow $sprite",
      group: "General",
      weight: 0,
      deprecated: true,
      problem: "You want a second camera to automatically track Player 2 in a split screen game, but you are using older code.",
      whatItDoes: "Note: This block is deprecated; use 'camera follow' instead. It attaches Camera 1 to follow the specified sprite and enables global split screen mode.",
      parameters: [
        { name: "sprite", type: "Sprite", meaning: "The sprite that Camera 1 should track." },
      ],
      example: `let player2 = sprites.create(img\`.\`, SpriteKind.Player)
splitScreen.splitScreenCameraFollow(player2)`,
    },
    {
      slug: "camera-follow",
      title: "camera follow",
      blockId: "splitscreensetcanerasprite",
      blockString: "camera $camera follow $sprite",
      group: "Global",
      weight: 100,
      problem: "You are making a two-player racing or fighting game and need each player to have their own view following their character across the map.",
      whatItDoes: "Assigns a specific split screen camera (such as Camera 1 or Camera 2) to track a sprite as it moves.",
      parameters: [
        { name: "camera", type: "Camera", default: "Camera.Camera1", meaning: "Which camera screen number to assign (Camera1, Camera2, etc.)." },
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite the chosen camera will track." },
      ],
      example: `let player1 = sprites.create(img\`.\`, SpriteKind.Player)
let player2 = sprites.create(img\`.\`, SpriteKind.Player)
splitScreen.cameraFollowSprite(splitScreen.Camera.Camera1, player1)
splitScreen.cameraFollowSprite(splitScreen.Camera.Camera2, player2)`,
    },
    {
      slug: "center-camera",
      title: "center camera",
      blockId: "splitscreencentercameraat",
      blockString: "center camera $camera at x $x y $y",
      group: "Global",
      weight: 90,
      problem: "You want one half of the split screen to focus on a fixed map area, like a treasure room or boss battle arena, rather than a moving player.",
      whatItDoes: "Locks a split screen camera to a fixed x and y coordinate on the screen or tilemap.",
      parameters: [
        { name: "camera", type: "Camera", meaning: "The camera number to reposition." },
        { name: "x", type: "number", meaning: "The horizontal pixel position to center on." },
        { name: "y", type: "number", meaning: "The vertical pixel position to center on." },
      ],
      example: "splitScreen.centerCameraAt(splitScreen.Camera.Camera2, 80, 60)",
    },
    {
      slug: "camera-shake",
      title: "camera shake",
      blockId: "splitscreencamerashake",
      blockString: "camera $camera shake by $amplitude pixels for $duration ms",
      group: "Global",
      weight: 80,
      problem: "Player 1 takes damage or triggers an explosion and you want only their view to shake without disorienting Player 2.",
      whatItDoes: "Shakes a specific split screen camera by a given pixel intensity for a set duration in milliseconds.",
      parameters: [
        { name: "camera", type: "Camera", meaning: "The split screen camera to shake." },
        { name: "amplitude", type: "number", default: 4, meaning: "How many pixels the camera shakes back and forth." },
        { name: "duration", type: "number", default: 500, meaning: "How long the shake effect lasts in milliseconds." },
      ],
      example: "splitScreen.cameraShake(splitScreen.Camera.Camera1, 6, 300)",
    },
    {
      slug: "set-camera-region",
      title: "set camera region",
      blockId: "splitscreensetcameraregion",
      blockString: "set camera $camera region to $region",
      group: "Global",
      weight: 70,
      problem: "You want to arrange split screen views vertically side-by-side or horizontally top-and-bottom depending on your game layout.",
      whatItDoes: "Sets where on the screen a specific camera displays, such as the left half, right half, or a corner quadrant.",
      parameters: [
        { name: "camera", type: "Camera", meaning: "The split screen camera to configure." },
        { name: "region", type: "CameraRegion", meaning: "The screen section where this camera view will be displayed." },
      ],
      example: `splitScreen.setCameraRegion(splitScreen.Camera.Camera1, splitScreen.CameraRegion.HorizontalTopHalf)
splitScreen.setCameraRegion(splitScreen.Camera.Camera2, splitScreen.CameraRegion.HorizontalBottomHalf)`,
    },
    {
      slug: "set-split-screen-enabled",
      title: "set split screen enabled",
      blockId: "splitscreencamerasetenabled",
      blockString: "set split screen enabled $enabled",
      group: "Global",
      weight: 60,
      problem: "You want to turn off split screen mode during full-screen cutscenes and turn it back on when normal gameplay resumes.",
      whatItDoes: "Enables or disables split screen rendering globally.",
      parameters: [
        { name: "enabled", type: "boolean", meaning: "Set to true to show split screen views, or false to hide them." },
      ],
      example: "splitScreen.setSplitScreenEnabled(false)",
    },
    {
      slug: "set-border-color",
      title: "set border color",
      blockId: "splitscreensetBorderColor",
      blockString: "set border color $color",
      group: "Global",
      weight: 50,
      problem: "You want a clean separator line between Player 1 and Player 2 views so players don't get confused.",
      whatItDoes: "Sets the color of the dividing border line drawn around each camera view screen.",
      parameters: [
        { name: "color", type: "number", meaning: "The color index (0-15) for the camera borders." },
      ],
      example: "splitScreen.setBorderColor(5)",
    },
    {
      slug: "camera-shadow",
      title: "camera shadow",
      blockId: "splitscreen_camerashadow",
      blockString: "$camera",
      group: "General",
      weight: 10,
      problem: "You are building a custom block menu and need a shadow block dropdown to select a camera index.",
      whatItDoes: "Internal shadow function that returns the selected camera enum value.",
      parameters: [
        { name: "camera", type: "Camera", meaning: "The selected camera enum value." },
      ],
      example: "let cam = splitScreen._cameraShadow(splitScreen.Camera.Camera1)",
    },
    {
      slug: "camera-region-shadow",
      title: "camera region shadow",
      blockId: "splitscreen_cameraregionshadow",
      blockString: "$region",
      group: "General",
      weight: 5,
      problem: "You are building a block editor extension and need a drop-down block for picking split screen screen regions.",
      whatItDoes: "Internal shadow function that returns the selected camera region enum value.",
      parameters: [
        { name: "region", type: "CameraRegion", meaning: "The camera region layout area." },
      ],
      example: "let reg = splitScreen._cameraRegionShadow(splitScreen.CameraRegion.VerticalLeftHalf)",
    },
    {
      slug: "set-split-screen-z-index",
      title: "set split screen z index",
      blockId: "splitscreen_setSplitScreenZIndex",
      blockString: "set split screen to capture everything below z $z",
      group: "Global",
      weight: 40,
      problem: "Your HUD or health bar UI elements are hidden behind the split screen views instead of rendering on top.",
      whatItDoes: "Sets the maximum layer (z-index) captured by split screen cameras, allowing elements with higher z-index to draw on top of everything.",
      parameters: [
        { name: "z", type: "number", default: 99, meaning: "The maximum z-index layer to include inside camera view renders." },
      ],
      example: "splitScreen.setSplitScreenZIndex(50)",
    },
    {
      slug: "get-sprite",
      title: "get sprite",
      blockId: "splitscreen_getSprite",
      blockString: "split screen sprite",
      group: "Global",
      weight: 30,
      problem: "You need to access the underlying sprite that manages split screen camera rendering to attach custom behavior or physics.",
      whatItDoes: "Returns the controller sprite object responsible for rendering split screen views.",
      parameters: [],
      returns: { type: "Sprite", meaning: "The internal split screen manager sprite." },
      example: `let manager = splitScreen.getSprite()
manager.z = 100`,
    },
    {
      slug: "get-camera-property",
      title: "get camera property",
      blockId: "splitscreen_getCameraProperty",
      blockString: "camera $camera $property",
      group: "Global",
      weight: 20,
      problem: "You want to check if an enemy or coin is currently visible inside Player 1's view by checking the camera position boundaries.",
      whatItDoes: "Returns spatial values like X, Y, Left, Right, Top, or Bottom coordinates for a chosen camera.",
      parameters: [
        { name: "camera", type: "Camera", meaning: "The camera number to inspect." },
        { name: "property", type: "CameraProperty", meaning: "The spatial property to measure (such as X, Y, or boundary edge)." },
      ],
      returns: { type: "number", meaning: "The requested coordinate or boundary value in pixels." },
      example: "let camLeft = splitScreen.getCameraProperty(splitScreen.Camera.Camera1, CameraProperty.Left)",
    },
    {
      slug: "set-render-size",
      title: "set render size",
      blockId: "splitscreen_setRenderSize",
      blockString: "set split screen render size width $width height $height",
      group: "Global",
      weight: 10,
      problem: "You are customizing screen dimensions for a mini display or custom arcade cabinet layout.",
      whatItDoes: "Changes the total pixel width and height used when rendering split screen camera views.",
      parameters: [
        { name: "width", type: "number", default: 160, meaning: "The width in pixels." },
        { name: "height", type: "number", default: 120, meaning: "The height in pixels." },
      ],
      example: "splitScreen.setRenderSize(160, 120)",
    },
    {
      slug: "create-camera-view",
      title: "create camera view",
      blockId: "splitscreen_createCameraView",
      blockString: "create camera view sprite width $width height $height",
      group: "Camera View",
      weight: 100,
      problem: "You want a picture-in-picture security monitor or mini-map sprite that shows another part of the world floating on screen.",
      whatItDoes: "Creates a floating camera view sprite of custom dimensions that acts like a live video monitor inside your game.",
      parameters: [
        { name: "width", type: "number", default: 160, meaning: "Width of the camera monitor frame in pixels." },
        { name: "height", type: "number", default: 120, meaning: "Height of the camera monitor frame in pixels." },
      ],
      returns: { type: "Sprite", meaning: "A CameraViewSprite object that can be moved around like any normal sprite." },
      example: "let minimap = splitScreen.createCameraView(60, 45)",
    },
    {
      slug: "camera-view-follow",
      title: "camera view follow",
      blockId: "splitscreen_cameraViewFollow",
      blockString: "camera view $cameraView follow sprite $sprite",
      group: "Camera View",
      weight: 90,
      problem: "You built a mini surveillance monitor sprite and want it to stream live footage tracking the boss monster.",
      whatItDoes: "Sets a camera view sprite to follow a target sprite.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite created earlier." },
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The target sprite to track inside the view frame." },
      ],
      example: `let monitor = splitScreen.createCameraView(80, 60)
let boss = sprites.create(img\`.\`, SpriteKind.Enemy)
splitScreen.cameraViewFollow(monitor, boss)`,
    },
    {
      slug: "center-camera-view",
      title: "center camera view",
      blockId: "splitscreen_centerCameraViewAt",
      blockString: "center camera view $cameraView at x $x y $y",
      group: "Camera View",
      weight: 80,
      problem: "You have a picture-in-picture display showing a stationary goal location, like a portal or flag.",
      whatItDoes: "Focuses a camera view sprite on a specific static coordinate in the game world.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to adjust." },
        { name: "x", type: "number", meaning: "World X position to focus on." },
        { name: "y", type: "number", meaning: "World Y position to focus on." },
      ],
      example: `let monitor = splitScreen.createCameraView(60, 60)
splitScreen.centerCameraViewAt(monitor, 300, 400)`,
    },
    {
      slug: "shake-camera-view",
      title: "shake camera view",
      blockId: "splitscreen_cameraViewShake",
      blockString: "camera view $cameraView shake by $amplitude pixels for $duration ms",
      group: "Camera View",
      weight: 70,
      problem: "An earthquake happens in a remote room and you want to shake only the security camera monitor displaying that room.",
      whatItDoes: "Shakes the view inside a picture-in-picture camera monitor sprite.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to apply shake to." },
        { name: "amplitude", type: "number", default: 4, meaning: "Intensity of shake in pixels." },
        { name: "duration", type: "number", default: 500, meaning: "Duration of shake in milliseconds." },
      ],
      example: `let monitor = splitScreen.createCameraView(80, 60)
splitScreen.shakeCameraView(monitor, 5, 400)`,
    },
    {
      slug: "camera-view-set-z-index",
      title: "camera view set z index",
      blockId: "splitscreen_cameraViewSetZIndex",
      blockString: "set camera view $cameraView to capture everything below z $z",
      group: "Camera View",
      weight: 60,
      problem: "Your mini-map display sprite is capturing and showing weather particles that should only appear above the camera frame.",
      whatItDoes: "Controls which game visual layers (z-index) get drawn inside the given camera view sprite.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to adjust." },
        { name: "z", type: "number", default: 99, meaning: "Maximum z-index layer visible inside this camera view frame." },
      ],
      example: `let monitor = splitScreen.createCameraView(80, 60)
splitScreen.cameraViewSetZIndex(monitor, 10)`,
    },
    {
      slug: "get-camera-view-property",
      title: "get camera view property",
      blockId: "splitscreen_getCameraViewProperty",
      blockString: "$cameraView camera $property",
      group: "Camera View",
      weight: 50,
      problem: "You need to know the coordinates or bounds of what a floating camera view window is currently viewing.",
      whatItDoes: "Returns position properties (such as center X/Y or edges) for a picture-in-picture camera view sprite.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to check." },
        { name: "property", type: "CameraProperty", meaning: "The camera property to query." },
      ],
      returns: { type: "number", meaning: "The requested coordinate value in pixels." },
      example: `let monitor = splitScreen.createCameraView(80, 60)
let viewX = splitScreen.getCameraViewProperty(monitor, CameraProperty.X)`,
    },
    {
      slug: "set-camera-view-border-color",
      title: "set camera view border color",
      blockId: "splitscreen_setCameraViewBorderColor",
      blockString: "set $cameraView border color $color",
      group: "Camera View",
      weight: 40,
      problem: "You want your radar or security screen sprite to have a bright red outline so it stands out against the background.",
      whatItDoes: "Sets the color of the border frame around a camera view sprite.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to style." },
        { name: "color", type: "number", meaning: "Color index (0-15) for the border frame." },
      ],
      example: `let monitor = splitScreen.createCameraView(80, 60)
splitScreen.setCameraViewBorderColor(monitor, 2)`,
    }
  ],
};
