import type { ExtensionDoc } from "@/content/extensions/types";

export const arcadeSplitScreen: ExtensionDoc = {
  owner: "riknoll",
  repo: "arcade-split-screen",
  displayName: "Split Screen",
  packageSlug: "github:riknoll/arcade-split-screen",
  description: "Add split-screen camera views and picture-in-picture viewports to Arcade games for multiplayer or mini-maps.",
  tools: [
    {
      slug: "split-screen-camera-follow",
      title: "split screen camera follow",
      blockId: "splitscreencamerafollowsprite",
      blockString: "split screen camera follow $sprite",
      group: "General",
      weight: 0,
      deprecated: true,
      problem: "You want a quick way to make the split-screen camera follow your player sprite in a 2-player game.",
      whatItDoes: "Makes Camera 1 follow the specified sprite. Note: This block is deprecated; use cameraFollowSprite instead.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "", meaning: "The player sprite that Camera 1 should center on and follow." },
      ],
      example: `let player = sprites.create(img\`.\`, SpriteKind.Player)
splitScreen.splitScreenCameraFollow(player)`,
    },
    {
      slug: "camera-follow",
      title: "camera follow",
      blockId: "splitscreensetcanerasprite",
      blockString: "camera $camera follow $sprite",
      group: "Global",
      weight: 100,
      problem: "You are building a 2-player or 4-player game and need each player to have their own camera following them around the map.",
      whatItDoes: "Locks a chosen split-screen camera (Camera 1 to 4) onto a sprite so the viewport tracks that sprite as it moves.",
      parameters: [
        { name: "camera", type: "Camera", default: "splitScreen.Camera.Camera1", meaning: "Which camera slot to set (Camera1, Camera2, Camera3, or Camera4)." },
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite that this camera view will track." },
      ],
      example: `let player2 = sprites.create(img\`.\`, SpriteKind.Player)
splitScreen.cameraFollowSprite(splitScreen.Camera.Camera2, player2)`,
    },
    {
      slug: "center-camera",
      title: "center camera",
      blockId: "splitscreencentercameraat",
      blockString: "center camera $camera at x $x y $y",
      group: "Global",
      weight: 90,
      problem: "You want a split-screen camera to lock onto a fixed map location, like an overview of a maze or a boss room, instead of tracking a player.",
      whatItDoes: "Centers a chosen split-screen camera at specific X and Y map pixel coordinates and detaches it from any sprite.",
      parameters: [
        { name: "camera", type: "Camera", default: "", meaning: "The camera slot to reposition." },
        { name: "x", type: "number", default: "", meaning: "The horizontal pixel position on the map to center the camera on." },
        { name: "y", type: "number", default: "", meaning: "The vertical pixel position on the map to center the camera on." },
      ],
      example: "splitScreen.centerCameraAt(splitScreen.Camera.Camera1, 80, 60)",
    },
    {
      slug: "camera-shake",
      title: "camera shake",
      blockId: "splitscreencamerashake",
      blockString: "camera $camera shake by $amplitude pixels for $duration ms",
      group: "Global",
      weight: 80,
      problem: "Player 1 gets hit or triggers an explosion, and you want only Player 1's split-screen view to shake without affecting Player 2's screen.",
      whatItDoes: "Shakes a specific split-screen camera view by a specified pixel distance for a given duration in milliseconds.",
      parameters: [
        { name: "camera", type: "Camera", default: "", meaning: "The camera view to shake." },
        { name: "amplitude", type: "number", default: "4", meaning: "How many pixels wide the shake vibration is." },
        { name: "duration", type: "number", default: "500", meaning: "How long the shake effect lasts in milliseconds." },
      ],
      example: "splitScreen.cameraShake(splitScreen.Camera.Camera1, 5, 500)",
    },
    {
      slug: "set-camera-region",
      title: "set camera region",
      blockId: "splitscreensetcameraregion",
      blockString: "set camera $camera region to $region",
      group: "Global",
      weight: 70,
      problem: "You want to arrange multi-player screen layouts differently, such as dividing the screen horizontally or vertically into custom sections.",
      whatItDoes: "Assigns a specific camera to draw on a defined region of the screen, such as the left half, right half, or top-left corner.",
      parameters: [
        { name: "camera", type: "Camera", default: "", meaning: "The camera whose screen region you want to set." },
        { name: "region", type: "CameraRegion", default: "", meaning: "The region preset (e.g. VerticalLeftHalf, TopLeft) to assign to this camera." },
      ],
      example: "splitScreen.setCameraRegion(splitScreen.Camera.Camera1, splitScreen.CameraRegion.VerticalLeftHalf)",
    },
    {
      slug: "set-split-screen-enabled",
      title: "set split screen enabled",
      blockId: "splitscreencamerasetenabled",
      blockString: "set split screen enabled $enabled",
      group: "Global",
      weight: 60,
      problem: "You want to pause split-screen mode during dialogue cutscenes or shop menus, then switch back to split-screen when action resumes.",
      whatItDoes: "Turns the entire split-screen camera rendering system on or off globally.",
      parameters: [
        { name: "enabled", type: "boolean", default: "", meaning: "True to activate split-screen views, false to hide them." },
      ],
      example: "splitScreen.setSplitScreenEnabled(true)",
    },
    {
      slug: "set-border-color",
      title: "set border color",
      blockId: "splitscreensetBorderColor",
      blockString: "set border color $color",
      group: "Global",
      weight: 50,
      problem: "The line dividing your player screens is hard to see or doesn't match the colors of your game.",
      whatItDoes: "Sets the outline color for borders drawn around split-screen camera regions. Set to 0 (transparent) to remove borders.",
      parameters: [
        { name: "color", type: "number", default: "", meaning: "The color index (0-15) to draw borders around split-screen regions." },
      ],
      example: "splitScreen.setBorderColor(3)",
    },
    {
      slug: "camera",
      title: "camera",
      blockId: "splitscreen_camerashadow",
      blockString: "$camera",
      group: "General",
      weight: 10,
      problem: "You need a block input shadow helper to pick a Camera dropdown value in MakeCode blocks.",
      whatItDoes: "Returns the camera enum choice for block configuration.",
      parameters: [
        { name: "camera", type: "Camera", default: "", meaning: "The selected camera slot." },
      ],
      example: "let cam = splitScreen._cameraShadow(splitScreen.Camera.Camera1)",
    },
    {
      slug: "region",
      title: "region",
      blockId: "splitscreen_cameraregionshadow",
      blockString: "$region",
      group: "General",
      weight: 5,
      problem: "You need a block input shadow helper to select a CameraRegion dropdown option in MakeCode blocks.",
      whatItDoes: "Returns the camera region enum choice for block configuration.",
      parameters: [
        { name: "region", type: "CameraRegion", default: "", meaning: "The selected screen region preset." },
      ],
      example: "let reg = splitScreen._cameraRegionShadow(splitScreen.CameraRegion.TopLeft)",
    },
    {
      slug: "set-split-screen-capture-everything-below-z",
      title: "set split screen capture everything below z",
      blockId: "splitscreen_setSplitScreenZIndex",
      blockString: "set split screen to capture everything below z $z",
      group: "Global",
      weight: 40,
      problem: "Your health bars or score popups are rendering underneath the split-screen camera display instead of on top of it.",
      whatItDoes: "Configures the maximum Z-index layer captured by split-screen cameras so higher Z-index UI elements draw over split views.",
      parameters: [
        { name: "z", type: "number", default: "99", meaning: "The depth layer limit below which all sprites are captured inside split views." },
      ],
      example: "splitScreen.setSplitScreenZIndex(50)",
    },
    {
      slug: "split-screen-sprite",
      title: "split screen sprite",
      blockId: "splitscreen_getSprite",
      blockString: "split screen sprite",
      group: "Global",
      weight: 30,
      problem: "You need direct access to the internal layout manager sprite that controls split-screen rendering.",
      whatItDoes: "Returns the main internal sprite object that draws and manages the split-screen layout.",
      parameters: [],
      returns: { type: "Sprite", meaning: "The global split-screen manager sprite." },
      example: "let manager = splitScreen.getSprite()",
    },
    {
      slug: "camera-property",
      title: "camera property",
      blockId: "splitscreen_getCameraProperty",
      blockString: "camera $camera $property",
      group: "Global",
      weight: 20,
      problem: "You want to find the exact edge positions (like top or left) of a player's split-screen camera to spawn obstacles just off-screen.",
      whatItDoes: "Returns the current numeric value of a specific camera property, such as X, Y, Left, Right, Top, or Bottom.",
      parameters: [
        { name: "camera", type: "Camera", default: "", meaning: "Which camera to inspect." },
        { name: "property", type: "CameraProperty", default: "", meaning: "The coordinate property to read (X, Y, Left, Right, Top, or Bottom)." },
      ],
      returns: { type: "number", meaning: "The current pixel value of the selected property." },
      example: "let camLeft = splitScreen.getCameraProperty(splitScreen.Camera.Camera1, CameraProperty.Left)",
    },
    {
      slug: "set-split-screen-render-size-width-height",
      title: "set split screen render size width height",
      blockId: "splitscreen_setRenderSize",
      blockString: "set split screen render size width $width height $height",
      group: "Global",
      weight: 10,
      problem: "You want your split-screen view area to use a custom width and height instead of taking up the entire screen.",
      whatItDoes: "Sets the width and height of the main split-screen display area.",
      parameters: [
        { name: "width", type: "number", default: "160", meaning: "The overall render width in pixels." },
        { name: "height", type: "number", default: "120", meaning: "The overall render height in pixels." },
      ],
      example: "splitScreen.setRenderSize(160, 120)",
    },
    {
      slug: "create-camera-view-sprite-width-height",
      title: "create camera view sprite width height",
      blockId: "splitscreen_createCameraView",
      blockString: "create camera view sprite width $width height $height",
      group: "Camera View",
      weight: 100,
      problem: "You want a picture-in-picture mini-map or security monitor sprite that shows a different area of the map.",
      whatItDoes: "Creates a new sprite that acts as a standalone camera viewport displaying the game world.",
      parameters: [
        { name: "width", type: "number", default: "160", meaning: "Width of the camera viewport sprite in pixels." },
        { name: "height", type: "number", default: "120", meaning: "Height of the camera viewport sprite in pixels." },
      ],
      returns: { type: "Sprite", meaning: "A camera view sprite that displays part of the world." },
      example: "let miniMap = splitScreen.createCameraView(60, 45)",
    },
    {
      slug: "camera-view-follow-sprite",
      title: "camera view follow sprite",
      blockId: "splitscreen_cameraViewFollow",
      blockString: "camera view $cameraView follow sprite $sprite",
      group: "Camera View",
      weight: 90,
      problem: "You created a mini-map camera view sprite and want it to focus on and track an enemy or second player.",
      whatItDoes: "Locks a standalone camera view sprite so it continuously tracks a target sprite as it moves.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite created using createCameraView." },
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The target sprite that this camera view should follow." },
      ],
      example: `let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
let view = splitScreen.createCameraView(80, 60)
splitScreen.cameraViewFollow(view, enemy)`,
    },
    {
      slug: "center-camera-view",
      title: "center camera view",
      blockId: "splitscreen_centerCameraViewAt",
      blockString: "center camera view $cameraView at x $x y $y",
      group: "Camera View",
      weight: 80,
      problem: "You want a picture-in-picture camera view sprite to stay locked onto a specific location, like a key or exit door.",
      whatItDoes: "Repositions a standalone camera view sprite to look at fixed world X and Y coordinates.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to reposition." },
        { name: "x", type: "number", default: "", meaning: "The X coordinate in world pixels to focus on." },
        { name: "y", type: "number", default: "", meaning: "The Y coordinate in world pixels to focus on." },
      ],
      example: `let view = splitScreen.createCameraView(60, 60)
splitScreen.centerCameraViewAt(view, 200, 150)`,
    },
    {
      slug: "camera-view-shake",
      title: "camera view shake",
      blockId: "splitscreen_cameraViewShake",
      blockString: "camera view $cameraView shake by $amplitude pixels for $duration ms",
      group: "Camera View",
      weight: 70,
      problem: "You want an action occurring inside a security camera or mini-map view to trigger a shake effect on that specific viewport.",
      whatItDoes: "Applies a screen shake effect exclusively to a single standalone camera view sprite.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to shake." },
        { name: "amplitude", type: "number", default: "4", meaning: "Shake distance in pixels." },
        { name: "duration", type: "number", default: "500", meaning: "Duration of shake in milliseconds." },
      ],
      example: `let view = splitScreen.createCameraView(80, 60)
splitScreen.shakeCameraView(view, 4, 300)`,
    },
    {
      slug: "set-camera-view-capture-everything-below-z",
      title: "set camera view capture everything below z",
      blockId: "splitscreen_cameraViewSetZIndex",
      blockString: "set camera view $cameraView to capture everything below z $z",
      group: "Camera View",
      weight: 60,
      problem: "Your custom camera view sprite is showing HUD text or floating controls that shouldn't be rendered inside its view window.",
      whatItDoes: "Sets the maximum Z index limit captured by a specific standalone camera view sprite.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The target camera view sprite." },
        { name: "z", type: "number", default: "99", meaning: "The highest Z depth layer to capture inside this camera view." },
      ],
      example: `let view = splitScreen.createCameraView(80, 60)
splitScreen.cameraViewSetZIndex(view, 50)`,
    },
    {
      slug: "camera-view-property",
      title: "camera view property",
      blockId: "splitscreen_getCameraViewProperty",
      blockString: "$cameraView camera $property",
      group: "Camera View",
      weight: 50,
      problem: "You need to measure where a camera view viewport is currently pointing in world space.",
      whatItDoes: "Reads a positioning property (X, Y, Left, Right, Top, or Bottom) from a custom camera view sprite.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to check." },
        { name: "property", type: "CameraProperty", default: "", meaning: "The camera property to inspect." },
      ],
      returns: { type: "number", meaning: "The pixel position value of the requested property." },
      example: `let view = splitScreen.createCameraView(80, 60)
let viewX = splitScreen.getCameraViewProperty(view, CameraProperty.X)`,
    },
    {
      slug: "set-camera-view-border-color",
      title: "set camera view border color",
      blockId: "splitscreen_setCameraViewBorderColor",
      blockString: "set $cameraView border color $color",
      group: "Camera View",
      weight: 40,
      problem: "You want to draw a colored frame around a picture-in-picture camera view sprite so players can easily see its edges.",
      whatItDoes: "Sets the outline frame color for a specific camera view sprite. Set to 0 for no border.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to outline." },
        { name: "color", type: "number", default: "", meaning: "The color index (0-15) for the border." },
      ],
      example: `let view = splitScreen.createCameraView(80, 60)
splitScreen.setCameraViewBorderColor(view, 5)`,
    }
  ],
};
