import type { ExtensionDoc } from "@/content/extensions/types";

export const arcadeSplitScreen: ExtensionDoc = {
  owner: "riknoll",
  repo: "arcade-split-screen",
  displayName: "Split Screen",
  packageSlug: "github:riknoll/arcade-split-screen",
  description: "Add split-screen multiplayer cameras and picture-in-picture camera view sprites to MakeCode Arcade games.",
  tools: [
    {
      slug: "split-screen-camera-follow",
      title: "split screen camera follow",
      blockId: "splitscreencamerafollowsprite",
      blockString: "split screen camera follow $sprite",
      group: "General",
      weight: 0,
      deprecated: true,
      problem: "You want camera 1 in a split-screen multiplayer game to track player 1 automatically.",
      whatItDoes: "Locks Camera 1 onto a sprite so the view follows it as it moves. Note: This block is deprecated; use 'camera follow sprite' instead.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite Camera 1 should track" },
      ],
      example: `let player1 = sprites.create(img\`.\`, SpriteKind.Player)
splitScreen.splitScreenCameraFollow(player1)`,
    },
    {
      slug: "camera-follow",
      title: "camera follow",
      blockId: "splitscreensetcanerasprite",
      blockString: "camera $camera follow $sprite",
      group: "Global",
      weight: 100,
      problem: "You are making a 2-player or 4-player game and need each section of the screen to follow a different player sprite.",
      whatItDoes: "Locks a specific split-screen camera (like Camera 1 or Camera 2) onto a sprite so it stays centered in that player's view.",
      parameters: [
        { name: "camera", type: "Camera", default: "Camera.Camera1", meaning: "Which camera view to configure (Camera 1 through Camera 4)" },
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite this camera will follow" },
      ],
      example: `let player1 = sprites.create(img\`.\`, SpriteKind.Player)
let player2 = sprites.create(img\`.\`, SpriteKind.Player)
splitScreen.cameraFollowSprite(splitScreen.Camera.Camera1, player1)
splitScreen.cameraFollowSprite(splitScreen.Camera.Camera2, player2)`,
    },
    {
      slug: "center-camera",
      title: "center camera",
      blockId: "splitscreencentercameraat",
      blockString: "center camera $camera at x $x y $y",
      group: "Global",
      weight: 90,
      problem: "You want one of the split screens to focus on a fixed map location, like a boss room or a race finish line, instead of following a sprite.",
      whatItDoes: "Positions a split-screen camera at fixed (x, y) pixel coordinates in the world.",
      parameters: [
        { name: "camera", type: "Camera", default: "Camera.Camera1", meaning: "Which camera view to move" },
        { name: "x", type: "number", default: "0", meaning: "The horizontal pixel position to center on" },
        { name: "y", type: "number", default: "0", meaning: "The vertical pixel position to center on" },
      ],
      example: "splitScreen.centerCameraAt(splitScreen.Camera.Camera2, 80, 60)",
    },
    {
      slug: "camera-shake",
      title: "camera shake",
      blockId: "splitscreencamerashake",
      blockString: "camera $camera shake by $amplitude pixels for $duration ms",
      group: "Global",
      weight: 80,
      problem: "Player 2 just got hit by an obstacle or explosion and you want only their half of the screen to shake without affecting Player 1.",
      whatItDoes: "Applies a screen shake effect to a specific split-screen camera for a set duration and intensity.",
      parameters: [
        { name: "camera", type: "Camera", default: "Camera.Camera1", meaning: "Which camera view should shake" },
        { name: "amplitude", type: "number", default: "4", meaning: "How intense the shake is in pixels (from 1 to 8)" },
        { name: "duration", type: "number", default: "500", meaning: "How long the camera shakes in milliseconds" },
      ],
      example: "splitScreen.cameraShake(splitScreen.Camera.Camera1, 4, 500)",
    },
    {
      slug: "set-camera-region",
      title: "set camera region",
      blockId: "splitscreensetcameraregion",
      blockString: "set camera $camera region to $region",
      group: "Global",
      weight: 70,
      problem: "You want to customize how the screen is divided between players, like putting one player on the top half and another on the bottom half.",
      whatItDoes: "Assigns a specific camera to a layout section of the screen, such as the top half, left third, or bottom-right corner.",
      parameters: [
        { name: "camera", type: "Camera", default: "Camera.Camera1", meaning: "The camera view you want to position" },
        { name: "region", type: "CameraRegion", default: "CameraRegion.VerticalLeftHalf", meaning: "The section of the screen where this camera should render" },
      ],
      example: `splitScreen.setCameraRegion(splitScreen.Camera.Camera1, splitScreen.CameraRegion.HorizontalTopHalf)
splitScreen.setCameraRegion(splitScreen.Camera.Camera2, splitScreen.CameraRegion.HorizontalBottomHalf)`,
    },
    {
      slug: "set-split-screen-enabled",
      title: "set split screen enabled",
      blockId: "splitscreencamerasetenabled",
      blockString: "set split screen enabled $enabled",
      group: "Global",
      weight: 60,
      problem: "Your players enter a cutscene or a mini-game where you want to temporarily switch back to a single shared camera view.",
      whatItDoes: "Turns the entire split-screen camera layout on or off.",
      parameters: [
        { name: "enabled", type: "boolean", default: "true", meaning: "true to display the split screen views; false to return to the regular camera" },
      ],
      example: "splitScreen.setSplitScreenEnabled(false)",
    },
    {
      slug: "set-border-color",
      title: "set border color",
      blockId: "splitscreensetBorderColor",
      blockString: "set border color $color",
      group: "Global",
      weight: 50,
      problem: "The divider line between split screens is hard to see against your background tiles, or you want to match your game's visual theme.",
      whatItDoes: "Sets the color of the border line drawn between split-screen camera views. Setting it to 0 (transparent) removes the border.",
      parameters: [
        { name: "color", type: "number", default: "1", meaning: "The color palette index (0-15) for the dividing lines" },
      ],
      example: "splitScreen.setBorderColor(3)",
    },
    {
      slug: "camera",
      title: "camera",
      blockId: "splitscreen_camerashadow",
      blockString: "$camera",
      group: "General",
      weight: 10,
      problem: "You need to select which player camera (Camera 1 through Camera 4) to use in a split-screen block.",
      whatItDoes: "A helper dropdown block in MakeCode for choosing a camera number.",
      parameters: [
        { name: "camera", type: "Camera", default: "Camera.Camera1", meaning: "The camera index to select" },
      ],
      returns: { type: "Camera", meaning: "The selected camera enum value." },
      example: "let cam = splitScreen.Camera.Camera1",
    },
    {
      slug: "region",
      title: "region",
      blockId: "splitscreen_cameraregionshadow",
      blockString: "$region",
      group: "General",
      weight: 5,
      problem: "You need to select a screen section (such as top half, left half, or corner) to position a camera.",
      whatItDoes: "A helper dropdown block in MakeCode for choosing a screen region layout.",
      parameters: [
        { name: "region", type: "CameraRegion", default: "CameraRegion.VerticalLeftHalf", meaning: "The layout region to select" },
      ],
      returns: { type: "CameraRegion", meaning: "The selected camera region enum value." },
      example: "let reg = splitScreen.CameraRegion.TopLeft",
    },
    {
      slug: "set-split-screen-to-capture-everything-below-z",
      title: "set split screen to capture everything below z",
      blockId: "splitscreen_setSplitScreenZIndex",
      blockString: "set split screen to capture everything below z $z",
      group: "Global",
      weight: 40,
      problem: "You have UI elements, dialogue boxes, or HUD sprites that should sit across the entire screen instead of being duplicated inside each player's camera view.",
      whatItDoes: "Sets the maximum Z-index captured by the split-screen cameras. Sprites with a Z-index at or above this value will be rendered globally on top of the split screens.",
      parameters: [
        { name: "z", type: "number", default: "99", meaning: "The Z-index cutoff. Sprites below this depth render inside the cameras; sprites above stay on the main screen." },
      ],
      example: `splitScreen.setSplitScreenZIndex(50)
let hud = sprites.create(img\`.\`, SpriteKind.Player)
hud.z = 100`,
    },
    {
      slug: "split-screen-sprite",
      title: "split screen sprite",
      blockId: "splitscreen_getSprite",
      blockString: "split screen sprite",
      group: "Global",
      weight: 30,
      problem: "You need direct access to the internal sprite that renders the split screens so you can modify its layer or properties.",
      whatItDoes: "Returns the underlying sprite object responsible for drawing the split-screen viewports.",
      parameters: [],
      returns: { type: "Sprite", meaning: "The internal split-screen manager sprite." },
      example: `let manager = splitScreen.getSprite()
manager.z = 10`,
    },
    {
      slug: "camera-property",
      title: "camera property",
      blockId: "splitscreen_getCameraProperty",
      blockString: "camera $camera $property",
      group: "Global",
      weight: 20,
      problem: "You need to know where a specific player's camera is looking in the tilemap to spawn items nearby or check boundaries.",
      whatItDoes: "Gets a coordinate property (such as X, Y, Left, Right, Top, or Bottom) from a split-screen camera.",
      parameters: [
        { name: "camera", type: "Camera", default: "Camera.Camera1", meaning: "Which camera to inspect" },
        { name: "property", type: "CameraProperty", default: "CameraProperty.X", meaning: "The coordinate property to read (X, Y, Left, Right, Top, or Bottom)" },
      ],
      returns: { type: "number", meaning: "The pixel position of the requested camera property." },
      example: `let camLeft = splitScreen.getCameraProperty(splitScreen.Camera.Camera1, CameraProperty.Left)
console.log(camLeft)`,
    },
    {
      slug: "set-split-screen-render-size-width-height",
      title: "set split screen render size width height",
      blockId: "splitscreen_setRenderSize",
      blockString: "set split screen render size width $width height $height",
      group: "Global",
      weight: 10,
      problem: "You want the split-screen layout to occupy only part of the display, leaving room around the edges for custom borders or player stats.",
      whatItDoes: "Changes the overall width and height of the split-screen display area.",
      parameters: [
        { name: "width", type: "number", default: "160", meaning: "The total width in pixels of the split-screen area" },
        { name: "height", type: "number", default: "120", meaning: "The total height in pixels of the split-screen area" },
      ],
      example: "splitScreen.setRenderSize(160, 100)",
    },
    {
      slug: "create-camera-view-sprite-width-height",
      title: "create camera view sprite width height",
      blockId: "splitscreen_createCameraView",
      blockString: "create camera view sprite width $width height $height",
      group: "Camera View",
      weight: 100,
      problem: "You want a picture-in-picture mini-map, rear-view mirror, or security monitor sprite floating on screen while the game plays.",
      whatItDoes: "Creates a sprite that displays a live camera view of your game world at the specified size.",
      parameters: [
        { name: "width", type: "number", default: "160", meaning: "Width of the camera view sprite in pixels" },
        { name: "height", type: "number", default: "120", meaning: "Height of the camera view sprite in pixels" },
      ],
      returns: { type: "Sprite", meaning: "The newly created camera view sprite." },
      example: "let miniCam = splitScreen.createCameraView(40, 30)",
    },
    {
      slug: "camera-view-follow-sprite",
      title: "camera view follow sprite",
      blockId: "splitscreen_cameraViewFollow",
      blockString: "camera view $cameraView follow sprite $sprite",
      group: "Camera View",
      weight: 90,
      problem: "You created a mini-monitor or drone camera sprite and want it to follow an enemy boss or a second player.",
      whatItDoes: "Sets a camera view sprite to follow a target sprite wherever it moves in the world.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite you created" },
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The sprite to follow" },
      ],
      example: `let miniCam = splitScreen.createCameraView(40, 30)
let boss = sprites.create(img\`.\`, SpriteKind.Enemy)
splitScreen.cameraViewFollow(miniCam, boss)`,
    },
    {
      slug: "center-camera-view",
      title: "center camera view",
      blockId: "splitscreen_centerCameraViewAt",
      blockString: "center camera view $cameraView at x $x y $y",
      group: "Camera View",
      weight: 80,
      problem: "You want a mini-camera window to look at a stationary point on the map, like a locked treasure chest or dungeon exit.",
      whatItDoes: "Centers the viewport of a camera view sprite at fixed (x, y) coordinates in the world.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to position" },
        { name: "x", type: "number", default: "0", meaning: "The horizontal pixel position in the game world" },
        { name: "y", type: "number", default: "0", meaning: "The vertical pixel position in the game world" },
      ],
      example: `let miniCam = splitScreen.createCameraView(40, 30)
splitScreen.centerCameraViewAt(miniCam, 100, 100)`,
    },
    {
      slug: "camera-view-shake",
      title: "camera view shake",
      blockId: "splitscreen_cameraViewShake",
      blockString: "camera view $cameraView shake by $amplitude pixels for $duration ms",
      group: "Camera View",
      weight: 70,
      problem: "An explosion happened near a remote camera monitor, and you want only that mini-camera window to shake.",
      whatItDoes: "Applies a screen shake effect inside a single camera view sprite.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to shake" },
        { name: "amplitude", type: "number", default: "4", meaning: "Shake strength in pixels (1 to 8)" },
        { name: "duration", type: "number", default: "500", meaning: "Shake duration in milliseconds" },
      ],
      example: `let miniCam = splitScreen.createCameraView(40, 30)
splitScreen.shakeCameraView(miniCam, 4, 500)`,
    },
    {
      slug: "set-camera-view-to-capture-everything-below-z",
      title: "set camera view to capture everything below z",
      blockId: "splitscreen_cameraViewSetZIndex",
      blockString: "set camera view $cameraView to capture everything below z $z",
      group: "Camera View",
      weight: 60,
      problem: "You have UI icons or health bars on screen that you don't want visible inside your picture-in-picture camera view.",
      whatItDoes: "Sets the maximum Z-index captured by a camera view sprite. Sprites with higher Z-indexes will not appear inside the camera window.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to configure" },
        { name: "z", type: "number", default: "99", meaning: "The Z-index threshold for rendering inside this camera view" },
      ],
      example: `let miniCam = splitScreen.createCameraView(40, 30)
splitScreen.cameraViewSetZIndex(miniCam, 50)`,
    },
    {
      slug: "camera-view-property",
      title: "camera view property",
      blockId: "splitscreen_getCameraViewProperty",
      blockString: "$cameraView camera $property",
      group: "Camera View",
      weight: 50,
      problem: "You need to know the world coordinates (like center X, center Y, or top edge) of what a camera view sprite is currently viewing.",
      whatItDoes: "Reads a coordinate property (X, Y, Left, Right, Top, or Bottom) from a camera view sprite's view.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite to inspect" },
        { name: "property", type: "CameraProperty", default: "CameraProperty.X", meaning: "The coordinate property to get (X, Y, Left, Right, Top, or Bottom)" },
      ],
      returns: { type: "number", meaning: "The coordinate value of the requested property in the camera view." },
      example: `let miniCam = splitScreen.createCameraView(40, 30)
let viewX = splitScreen.getCameraViewProperty(miniCam, CameraProperty.X)
console.log(viewX)`,
    },
    {
      slug: "set-camera-view-border-color",
      title: "set camera view border color",
      blockId: "splitscreen_setCameraViewBorderColor",
      blockString: "set $cameraView border color $color",
      group: "Camera View",
      weight: 40,
      problem: "You want to outline your picture-in-picture camera sprite with a colored frame or remove its border entirely.",
      whatItDoes: "Sets the border outline color for a camera view sprite. Set it to 0 (transparent) to hide the border.",
      parameters: [
        { name: "cameraView", type: "Sprite", default: "myCameraView", meaning: "The camera view sprite" },
        { name: "color", type: "number", default: "1", meaning: "The palette color index (0-15) for the border" },
      ],
      example: `let miniCam = splitScreen.createCameraView(40, 30)
splitScreen.setCameraViewBorderColor(miniCam, 7)`,
    }
  ],
};
