import type { ExtensionDoc } from "@/content/extensions/types";

export const arcadeOverworld: ExtensionDoc = {
  owner: "riknoll",
  repo: "arcade-overworld",
  displayName: "Overworld",
  packageSlug: "github:riknoll/arcade-overworld",
  description: "Create connected grid-based tilemap worlds with room transitions, scroll animations, and continuous map modes.",
  tools: [
    {
      slug: "set-overworld16",
      title: "set overworld 16x16",
      blockId: "overworld_setOverworld16",
      blockString: "set overworld $maps",
      group: "Create",
      weight: 100,
      problem: "You want to set up an adventure world made of connected 16x16 tilemap rooms that the player can explore.",
      whatItDoes: "Sets the 2D grid of 16x16 tilemaps used as your game world. Call loadMap afterwards to display the starting room.",
      parameters: [
        { name: "maps", type: "tiles.TileMapData[][]", meaning: "A 2D array representing rows and columns of tilemaps." },
      ],
      example: `overworld.setOverworld16([
    [tilemap\`level1\`, tilemap\`level2\`]
])
overworld.loadMap(0, 0)`,
    },
    {
      slug: "set-overworld8",
      title: "set overworld 8x8",
      blockId: "overworld_setOverworld8",
      blockString: "set overworld $maps",
      group: "Create",
      weight: 90,
      problem: "You want to create an overworld using smaller 8x8 pixel tilemaps for a retro arcade feel.",
      whatItDoes: "Sets the 2D grid of 8x8 tilemaps used for your game world. Call loadMap afterwards to display the starting room.",
      parameters: [
        { name: "maps", type: "tiles.TileMapData[][]", meaning: "A 2D grid of 8x8 tilemaps." },
      ],
      example: `overworld.setOverworld8([
    [overworld.tilemap8(tilemap\`level1\`)]
])
overworld.loadMap(0, 0)`,
    },
    {
      slug: "set-player-sprite",
      title: "set player sprite",
      blockId: "overworld_setPlayerSprite",
      blockString: "set player sprite $sprite",
      group: "Create",
      weight: 80,
      problem: "You want room transitions to happen automatically when your character reaches the edge of the screen.",
      whatItDoes: "Assigns a sprite as the player. When this sprite walks near the border of the current tilemap, adjacent rooms load automatically.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The player character sprite that triggers room transitions." },
      ],
      example: `let mySprite = sprites.create(img\`.\`, SpriteKind.Player)
controller.moveSprite(mySprite)
overworld.setPlayerSprite(mySprite)`,
    },
    {
      slug: "current-location",
      title: "overworld location",
      blockId: "overworld_currentLocation",
      blockString: "overworld location $property",
      group: "Load",
      weight: 100,
      problem: "You need to know which room column or row in the world grid the player is currently inside.",
      whatItDoes: "Returns the grid column or row index of the currently loaded tilemap.",
      parameters: [
        { name: "property", type: "LocationProperty", meaning: "Choose Column to get x-coordinate in grid or Row to get y-coordinate." },
      ],
      returns: { type: "number", meaning: "The grid index (starting from 0) of the current room." },
      example: `let col = overworld.currentLocation(overworld.LocationProperty.Column)
console.log(col)`,
    },
    {
      slug: "load-map",
      title: "load overworld map at",
      blockId: "overworld_loadMap",
      blockString: "load overworld map at col $column row $row",
      group: "Load",
      weight: 90,
      problem: "You want to jump or teleport the player directly into a specific room in your world grid.",
      whatItDoes: "Loads the tilemap located at the specified column and row in your overworld grid.",
      parameters: [
        { name: "column", type: "number", meaning: "The grid column coordinate to load." },
        { name: "row", type: "number", meaning: "The grid row coordinate to load." },
      ],
      example: "overworld.loadMap(0, 1)",
    },
    {
      slug: "load-map-in-direction",
      title: "load overworld map in direction",
      blockId: "overworld_loadMapInDirection",
      blockString: "load overworld map in direction $direction",
      group: "Load",
      weight: 80,
      problem: "You want to force a room switch when the player touches a doorway or stair tile.",
      whatItDoes: "Loads the tilemap located directly next to the current map in the specified direction.",
      parameters: [
        { name: "direction", type: "CollisionDirection", meaning: "The direction (Top, Right, Bottom, or Left) of the neighboring room." },
      ],
      example: "overworld.loadMapInDirection(CollisionDirection.Right)",
    },
    {
      slug: "get-map-at",
      title: "get overworld map at",
      blockId: "overworld_getMapAt",
      blockString: "get overworld map at col $column row $row",
      group: "Load",
      weight: 70,
      problem: "You want to inspect or read information from a room tilemap at a specific coordinate without switching to it.",
      whatItDoes: "Returns the tilemap data for the room at the given grid column and row.",
      parameters: [
        { name: "column", type: "number", meaning: "Grid column position." },
        { name: "row", type: "number", meaning: "Grid row position." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The tilemap object at that grid location, or undefined if empty." },
      example: "let map = overworld.getMapAt(1, 0)",
    },
    {
      slug: "get-map-in-direction",
      title: "get overworld map in direction",
      blockId: "overworld_getMapInDirection",
      blockString: "get overworld map in direction $direction",
      group: "Load",
      weight: 60,
      problem: "You want to check what tiles or layout exist in an adjacent room before moving the player there.",
      whatItDoes: "Returns the tilemap data of the neighboring room in a given direction.",
      parameters: [
        { name: "direction", type: "CollisionDirection", meaning: "Direction relative to the active map." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The tilemap data in that direction." },
      example: "let nextMap = overworld.getMapInDirection(CollisionDirection.Top)",
    },
    {
      slug: "map-exists-at",
      title: "overworld map exists at",
      blockId: "overworld_mapExistsAt",
      blockString: "overworld map exists at col $column row $row",
      group: "Load",
      weight: 50,
      problem: "You want to verify if a valid room exists at specific coordinates before teleporting the player.",
      whatItDoes: "Returns true if a tilemap is defined at the specified column and row grid position.",
      parameters: [
        { name: "column", type: "number", meaning: "Grid column position." },
        { name: "row", type: "number", meaning: "Grid row position." },
      ],
      returns: { type: "boolean", meaning: "true if a room exists at the given grid coordinates." },
      example: `if (overworld.mapExistsAt(2, 0)) {
    overworld.loadMap(2, 0)
}`,
    },
    {
      slug: "map-exists-in-direction",
      title: "overworld map exists in direction",
      blockId: "overworld_mapExistsInDirection",
      blockString: "overworld map exists in direction $direction",
      group: "Load",
      weight: 40,
      problem: "You want to check if the player has reached the outer edge of your world so you can stop them or show a message.",
      whatItDoes: "Returns true if there is an existing tilemap adjacent to the current room in the given direction.",
      parameters: [
        { name: "direction", type: "CollisionDirection", meaning: "Direction to check." },
      ],
      returns: { type: "boolean", meaning: "true if a neighboring room exists in that direction." },
      example: "let canMoveRight = overworld.mapExistsInDirection(CollisionDirection.Right)",
    },
    {
      slug: "on-map-loaded",
      title: "on map loaded",
      blockId: "overworld_onMapLoaded",
      blockString: "on map loaded at $overworldColumn $overworldRow $map",
      group: "Load",
      weight: 30,
      problem: "You want to spawn monsters, chests, or NPCs whenever the player enters a new room.",
      whatItDoes: "Runs code whenever a new tilemap room is loaded, giving you the room grid coordinates and tilemap data.",
      parameters: [
        { name: "handler", type: "function", meaning: "Callback function receiving overworldColumn, overworldRow, and map parameters." },
      ],
      example: `overworld.onMapLoaded(function (col, row, map) {
    game.splash("Entered room at " + col + "," + row)
})`,
    },
    {
      slug: "set-animation-type",
      title: "overworld set animation type",
      blockId: "overworld_setAnimationType",
      blockString: "overworld set animation type $animationType",
      group: "Animation",
      weight: 100,
      problem: "You want camera transitions between rooms to scroll smoothly or fade out like classic dungeon crawlers.",
      whatItDoes: "Sets the animation effect used when switching rooms, such as scrolling or fading to a color.",
      parameters: [
        { name: "animationType", type: "AnimationType", meaning: "Transition style: Scroll, FadeToBlack, FadeToWhite, FadeToColor, or None." },
      ],
      example: "overworld.setAnimationType(overworld.AnimationType.Scroll)",
    },
    {
      slug: "set-animation-duration",
      title: "overworld set animation duration",
      blockId: "overworld_setAnimationDuration",
      blockString: "overworld set animation duration $duration",
      group: "Animation",
      weight: 90,
      problem: "You want room transitions to happen faster or slower.",
      whatItDoes: "Sets how long the room transition animation takes in milliseconds.",
      parameters: [
        { name: "duration", type: "number", meaning: "Duration of transition in milliseconds (e.g. 500 for half a second)." },
      ],
      example: "overworld.setAnimationDuration(500)",
    },
    {
      slug: "set-animation-timing-function",
      title: "overworld set animation timing function",
      blockId: "overworld_setAnimationTimingFunction",
      blockString: "overworld set animation timing function $func",
      group: "Animation",
      weight: 80,
      problem: "You want room transition camera speed to ease smoothly in and out instead of moving at a constant rate.",
      whatItDoes: "Sets the easing function that controls acceleration during transition animations.",
      parameters: [
        { name: "func", type: "TimingFunction", meaning: "Easing function such as Linear, EaseIn, EaseOut, or EaseInOut." },
      ],
      example: "overworld.setAnimationTimingFunction(overworld.TimingFunction.EaseInOut)",
    },
    {
      slug: "set-animation-fade-color",
      title: "overworld set animation custom fade color",
      blockId: "overworld_setAnimationFadeColor",
      blockString: "overworld set animation custom fade color $color",
      group: "Animation",
      weight: 70,
      problem: "You want screen transitions to fade through a custom theme color, like red for a volcano area.",
      whatItDoes: "Sets the custom color used when animation type is set to FadeToColor.",
      parameters: [
        { name: "color", type: "string", default: "#000000", meaning: "Hex color code string (e.g. #FF0000 for red)." },
      ],
      example: `overworld.setAnimationType(overworld.AnimationType.FadeToColor)
overworld.setAnimationFadeColor("#FF0000")`,
    },
    {
      slug: "set-scroll-animation-z-index",
      title: "overworld set scroll animation z",
      blockId: "overworld_setScrollAnimationZIndex",
      blockString: "overworld set scroll animation z $z",
      group: "Animation",
      weight: 70,
      problem: "Your HUD or UI sprites are getting hidden or scrolled away during room transitions.",
      whatItDoes: "Sets the Z-index rendering layer for scroll animations. Sprites with higher Z values won't be moved by the scroll.",
      parameters: [
        { name: "z", type: "number", default: 99, meaning: "Z-depth index for transition rendering." },
      ],
      example: "overworld.setScrollAnimationZIndex(99)",
    },
    {
      slug: "set-map-transitions-enabled",
      title: "set overworld transitions enabled",
      blockId: "overworld_setMapTransitionsEnabled",
      blockString: "set overworld transitions enabled $enabled",
      group: "Options",
      weight: 100,
      problem: "You want to temporarily lock the player in a boss arena or disable screen switching during dialogue.",
      whatItDoes: "Turns automatic screen-edge room transitions on or off.",
      parameters: [
        { name: "enabled", type: "boolean", meaning: "true to enable room switching, false to prevent room changes." },
      ],
      example: "overworld.setMapTransitionsEnabled(false)",
    },
    {
      slug: "set-map-transition-radius",
      title: "set overworld transition radius",
      blockId: "overworld_setMapTransitionRadius",
      blockString: "set overworld transition radius $radius",
      group: "Options",
      weight: 90,
      problem: "You want room switches to trigger earlier or closer to screen edges as the player moves.",
      whatItDoes: "Sets the pixel distance from tilemap borders required to trigger automatic room transitions.",
      parameters: [
        { name: "radius", type: "number", meaning: "Trigger distance in pixels from the edge of the map." },
      ],
      example: "overworld.setMapTransitionRadius(8)",
    },
    {
      slug: "set-walls-block-transitions",
      title: "set walls block map transitions",
      blockId: "overworld_setWallsBlockTransitions",
      blockString: "set walls block map transitions $blockEnabled",
      group: "Options",
      weight: 80,
      problem: "You want to prevent players from transitioning into a room if a wall blocks the entry spot on the other side.",
      whatItDoes: "When enabled, stops the player from entering an adjacent room if the destination tile is a wall.",
      parameters: [
        { name: "blockEnabled", type: "boolean", meaning: "true to block room transitions into wall tiles." },
      ],
      example: "overworld.setWallsBlockTransitions(true)",
    },
    {
      slug: "set-continuous-mode-enabled",
      title: "set continuous mode enabled",
      blockId: "overworld_setContinuousModeEnabled",
      blockString: "set continuous mode enabled $enabled",
      group: "Options",
      weight: 70,
      problem: "You want your room grid to seamlessly merge into one giant open-world map instead of separate rooms.",
      whatItDoes: "Stitches all grid tilemaps into one massive continuous map without transition screens.",
      parameters: [
        { name: "enabled", type: "boolean", meaning: "true for one continuous open map, false for room-by-room grid." },
      ],
      example: "overworld.setContinuousModeEnabled(true)",
    },
    {
      slug: "create-map16",
      title: "create map 16x16",
      blockId: "overworld_createMap16",
      blockString: "$row0 $row1 $row2|| $row3 $row4 $row5",
      group: "Shadows",
      weight: 0,
      problem: "You need to combine rows of 16x16 tilemaps into a full 2D world grid.",
      whatItDoes: "Combines row arrays of 16x16 tilemaps into a complete 2D array grid.",
      parameters: [
        { name: "row0", type: "tiles.TileMapData[]", meaning: "First row array of tilemaps." },
        { name: "row1", type: "tiles.TileMapData[]", meaning: "Second row array of tilemaps." },
        { name: "row2", type: "tiles.TileMapData[]", meaning: "Third row array of tilemaps." },
        { name: "row3", type: "tiles.TileMapData[]", meaning: "Optional fourth row array." },
        { name: "row4", type: "tiles.TileMapData[]", meaning: "Optional fifth row array." },
        { name: "row5", type: "tiles.TileMapData[]", meaning: "Optional sixth row array." },
      ],
      returns: { type: "tiles.TileMapData[][]", meaning: "2D tilemap grid." },
      example: `let row1 = overworld.mapRow16(tilemap\`map1\`, tilemap\`map2\`)
let grid = overworld.createMap16(row1, row1, row1)`,
    },
    {
      slug: "create-map8",
      title: "create map 8x8",
      blockId: "overworld_createMap8",
      blockString: "$row0 $row1 $row2|| $row3 $row4 $row5",
      group: "Shadows",
      weight: 0,
      problem: "You need to combine rows of 8x8 tilemaps into a full 2D world grid.",
      whatItDoes: "Combines row arrays of 8x8 tilemaps into a complete 2D array grid.",
      parameters: [
        { name: "row0", type: "tiles.TileMapData[]", meaning: "First row array of 8x8 tilemaps." },
        { name: "row1", type: "tiles.TileMapData[]", meaning: "Second row array of 8x8 tilemaps." },
        { name: "row2", type: "tiles.TileMapData[]", meaning: "Third row array of 8x8 tilemaps." },
        { name: "row3", type: "tiles.TileMapData[]", meaning: "Optional fourth row array." },
        { name: "row4", type: "tiles.TileMapData[]", meaning: "Optional fifth row array." },
        { name: "row5", type: "tiles.TileMapData[]", meaning: "Optional sixth row array." },
      ],
      returns: { type: "tiles.TileMapData[][]", meaning: "2D tilemap grid." },
      example: `let row1 = overworld.mapRow8(tilemap\`map1\`, tilemap\`map2\`)
let grid = overworld.createMap8(row1, row1, row1)`,
    },
    {
      slug: "map-row16",
      title: "map row 16x16",
      blockId: "overworld_mapRow16",
      blockString: "$map0 $map1 $map2|| $map3 $map4 $map5",
      group: "Shadows",
      weight: 0,
      problem: "You want to define a horizontal row of 16x16 tilemaps for your overworld grid.",
      whatItDoes: "Combines up to 6 tilemaps into a single row array for 16x16 worlds.",
      parameters: [
        { name: "map0", type: "tiles.TileMapData", meaning: "Tilemap at column 0." },
        { name: "map1", type: "tiles.TileMapData", meaning: "Tilemap at column 1." },
        { name: "map2", type: "tiles.TileMapData", meaning: "Tilemap at column 2." },
        { name: "map3", type: "tiles.TileMapData", meaning: "Optional tilemap at column 3." },
        { name: "map4", type: "tiles.TileMapData", meaning: "Optional tilemap at column 4." },
        { name: "map5", type: "tiles.TileMapData", meaning: "Optional tilemap at column 5." },
      ],
      returns: { type: "tiles.TileMapData[]", meaning: "An array of 16x16 tilemaps for one grid row." },
      example: "let row = overworld.mapRow16(tilemap`room1`, tilemap`room2`, tilemap`room3`)",
    },
    {
      slug: "map-row8",
      title: "map row 8x8",
      blockId: "overworld_mapRow8",
      blockString: "$map0 $map1 $map2|| $map3 $map4 $map5",
      group: "Shadows",
      weight: 0,
      problem: "You want to define a horizontal row of 8x8 tilemaps for your overworld grid.",
      whatItDoes: "Combines up to 6 tilemaps into a single row array for 8x8 worlds.",
      parameters: [
        { name: "map0", type: "tiles.TileMapData", meaning: "Tilemap at column 0." },
        { name: "map1", type: "tiles.TileMapData", meaning: "Tilemap at column 1." },
        { name: "map2", type: "tiles.TileMapData", meaning: "Tilemap at column 2." },
        { name: "map3", type: "tiles.TileMapData", meaning: "Optional tilemap at column 3." },
        { name: "map4", type: "tiles.TileMapData", meaning: "Optional tilemap at column 4." },
        { name: "map5", type: "tiles.TileMapData", meaning: "Optional tilemap at column 5." },
      ],
      returns: { type: "tiles.TileMapData[]", meaning: "An array of 8x8 tilemaps for one grid row." },
      example: "let row = overworld.mapRow8(tilemap`room1`, tilemap`room2`, tilemap`room3`)",
    },
    {
      slug: "tilemap8",
      title: "8 tilemap",
      blockId: "overworld_tilemap8",
      blockString: "8 $tilemap",
      group: "Tilemaps",
      weight: 49,
      problem: "You need to mark a tilemap as using 8x8 pixel tiles when adding it to an overworld row.",
      whatItDoes: "Returns the provided tilemap data for use with 8x8 overworld grids.",
      parameters: [
        { name: "tilemap", type: "tiles.TileMapData", meaning: "The tilemap data." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The 8x8 tilemap data." },
      example: "let tm = overworld.tilemap8(tilemap`level1`)",
    },
    {
      slug: "tilemap16",
      title: "16 tilemap",
      blockId: "overworld_tilemap16",
      blockString: "16 $tilemap",
      group: "Tilemaps",
      weight: 49,
      problem: "You need to mark a tilemap as using 16x16 pixel tiles when adding it to an overworld row.",
      whatItDoes: "Returns the provided tilemap data for use with 16x16 overworld grids.",
      parameters: [
        { name: "tilemap", type: "tiles.TileMapData", meaning: "The tilemap data." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The 16x16 tilemap data." },
      example: "let tm = overworld.tilemap16(tilemap`level1`)",
    }
  ],
};
