import type { ExtensionDoc } from "@/content/extensions/types";

export const arcadeOverworld: ExtensionDoc = {
  owner: "riknoll",
  repo: "arcade-overworld",
  displayName: "Overworld",
  packageSlug: "github:riknoll/arcade-overworld",
  description: "Create connected worlds with grid-based room navigation, room transitions, animations, and continuous map scrolling in MakeCode Arcade.",
  tools: [
    {
      slug: "set-overworld-16",
      title: "set overworld 16",
      blockId: "overworld_setOverworld16",
      blockString: "set overworld $maps",
      group: "Create",
      weight: 100,
      problem: "You want to create a world composed of connected 16x16 tilemaps that your hero can walk between like an adventure game.",
      whatItDoes: "Registers a grid layout of 16x16 tilemaps as your overworld. You still need to load an initial map using loadMap to display it on screen.",
      parameters: [
        { name: "maps", type: "tiles.TileMapData[][]", meaning: "A 2D array representing rows and columns of 16x16 tilemaps." },
      ],
      example: `let row1 = [tilemap\`level1\`, tilemap\`level2\`]
overworld.setOverworld16([row1])
overworld.loadMap(0, 0)`,
    },
    {
      slug: "set-overworld-8",
      title: "set overworld 8",
      blockId: "overworld_setOverworld8",
      blockString: "set overworld $maps",
      group: "Create",
      weight: 90,
      problem: "You want to set up a grid of connected 8x8 pixel tilemaps for retro, low-resolution world maps.",
      whatItDoes: "Registers a grid layout of 8x8 tilemaps for the overworld system.",
      parameters: [
        { name: "maps", type: "tiles.TileMapData[][]", meaning: "A 2D array representing rows and columns of 8x8 tilemaps." },
      ],
      example: `let row1 = [tilemap\`map1\`, tilemap\`map2\`]
overworld.setOverworld8([row1])
overworld.loadMap(0, 0)`,
    },
    {
      slug: "set-player-sprite",
      title: "set player sprite",
      blockId: "overworld_setPlayerSprite",
      blockString: "set player sprite $sprite",
      group: "Create",
      weight: 80,
      problem: "You want the screen to automatically switch rooms when your main hero reaches the edge of the tilemap.",
      whatItDoes: "Sets the designated sprite as the player character whose movement triggers automatic map switches when hitting screen edges.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The player sprite to monitor for map transition triggers." },
      ],
      example: `let hero = sprites.create(img\`.\`, SpriteKind.Player)
overworld.setPlayerSprite(hero)`,
    },
    {
      slug: "current-location",
      title: "overworld location",
      blockId: "overworld_currentLocation",
      blockString: "overworld location $property",
      group: "Load",
      weight: 100,
      problem: "You need to know which column or row in the overworld grid the player is currently occupying.",
      whatItDoes: "Returns the active overworld grid column or row coordinate of the current tilemap.",
      parameters: [
        { name: "property", type: "LocationProperty", meaning: "The coordinate property to read (LocationProperty.Column or LocationProperty.Row)." },
      ],
      returns: { type: "number", meaning: "The active column or row index in the overworld grid." },
      example: `let col = overworld.currentLocation(overworld.LocationProperty.Column)
console.log(col)`,
    },
    {
      slug: "load-map",
      title: "load overworld map",
      blockId: "overworld_loadMap",
      blockString: "load overworld map at col $column row $row",
      group: "Load",
      weight: 90,
      problem: "You want to start the player at a specific map room or teleport them to a specific room coordinate.",
      whatItDoes: "Loads the tilemap located at the specified overworld column and row. Does nothing if continuous mode is on or no map exists at those coordinates.",
      parameters: [
        { name: "column", type: "number", meaning: "The grid column coordinate of the target map." },
        { name: "row", type: "number", meaning: "The grid row coordinate of the target map." },
      ],
      example: "overworld.loadMap(0, 1)",
    },
    {
      slug: "load-map-in-direction",
      title: "load overworld map in direction",
      blockId: "overworld_loadMapInDirection",
      blockString: "load overworld map in direction $direction",
      group: "Load",
      weight: 80,
      problem: "You want a spell, door, or event to push the player into the next room to the North, South, East, or West.",
      whatItDoes: "Loads the adjacent tilemap room relative to the current room in the given collision direction.",
      parameters: [
        { name: "direction", type: "CollisionDirection", meaning: "The direction to move (Top, Right, Bottom, or Left)." },
      ],
      example: "overworld.loadMapInDirection(CollisionDirection.Right)",
    },
    {
      slug: "get-map-at",
      title: "get overworld map",
      blockId: "overworld_getMapAt",
      blockString: "get overworld map at col $column row $row",
      group: "Load",
      weight: 70,
      problem: "You want to inspect or modify the tilemap data of a specific grid room before loading it.",
      whatItDoes: "Returns the TileMapData for the room at the given grid coordinates, or undefined if no map exists there.",
      parameters: [
        { name: "column", type: "number", meaning: "The grid column index." },
        { name: "row", type: "number", meaning: "The grid row index." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The tilemap object at the grid location." },
      example: "let map = overworld.getMapAt(1, 0)",
    },
    {
      slug: "get-map-in-direction",
      title: "get overworld map in direction",
      blockId: "overworld_getMapInDirection",
      blockString: "get overworld map in direction $direction",
      group: "Load",
      weight: 60,
      problem: "You want to inspect the neighboring room map before moving the player into it.",
      whatItDoes: "Returns the TileMapData of the room immediately adjacent to the current room in the specified direction.",
      parameters: [
        { name: "direction", type: "CollisionDirection", meaning: "The adjacent direction to retrieve." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The tilemap object in that direction." },
      example: "let nextMap = overworld.getMapInDirection(CollisionDirection.Top)",
    },
    {
      slug: "map-exists-at",
      title: "overworld map exists",
      blockId: "overworld_mapExistsAt",
      blockString: "overworld map exists at col $column row $row",
      group: "Load",
      weight: 50,
      problem: "You want to check if a valid map room exists at a given coordinate before trying to teleport the player there.",
      whatItDoes: "Returns true if a valid tilemap is configured at the target grid column and row.",
      parameters: [
        { name: "column", type: "number", meaning: "The grid column coordinate." },
        { name: "row", type: "number", meaning: "The grid row coordinate." },
      ],
      returns: { type: "boolean", meaning: "true if a map exists at the specified coordinates." },
      example: `if (overworld.mapExistsAt(2, 0)) {
    overworld.loadMap(2, 0)
}`,
    },
    {
      slug: "map-exists-in-direction",
      title: "overworld map exists in direction",
      blockId: "overworld_mapExistsInDirection",
      blockString: "overworld map exists in direction $direction",
      group: "Load",
      weight: 40,
      problem: "You want to display a message or stop the player when they hit the outer boundary of your world.",
      whatItDoes: "Returns true if an adjacent tilemap room exists in the specified direction from the current room.",
      parameters: [
        { name: "direction", type: "CollisionDirection", meaning: "The direction to check." },
      ],
      returns: { type: "boolean", meaning: "true if a neighboring room exists in that direction." },
      example: "let canMove = overworld.mapExistsInDirection(CollisionDirection.Left)",
    },
    {
      slug: "on-map-loaded",
      title: "on map loaded",
      blockId: "overworld_onMapLoaded",
      blockString: "on map loaded at $overworldColumn $overworldRow $map",
      group: "Load",
      weight: 30,
      problem: "You want to spawn monsters, treasure chests, or NPCs whenever the player enters a new room.",
      whatItDoes: "Registers an event handler that runs every time a new tilemap room is loaded.",
      parameters: [
        { name: "handler", type: "(overworldColumn: number, overworldRow: number, map: tiles.TileMapData) => void", meaning: "Code handler receiving room column, row, and tilemap data." },
      ],
      example: `overworld.onMapLoaded(function (col, row, map) {
    console.log("Entered room at col: " + col)
})`,
    },
    {
      slug: "set-animation-type",
      title: "overworld set animation type",
      blockId: "overworld_setAnimationType",
      blockString: "overworld set animation type $animationType",
      group: "Animation",
      weight: 100,
      problem: "You want smooth visual screen transitions like scrolling or fading when moving between rooms.",
      whatItDoes: "Configures the transition animation type used when switching between rooms (e.g., Scroll, FadeToBlack, None).",
      parameters: [
        { name: "animationType", type: "AnimationType", meaning: "The style of transition animation to play." },
      ],
      example: "overworld.setAnimationType(overworld.AnimationType.Scroll)",
    },
    {
      slug: "set-animation-duration",
      title: "overworld set animation duration",
      blockId: "overworld_setAnimationDuration",
      blockString: "overworld set animation duration $duration",
      group: "Animation",
      weight: 90,
      problem: "You want room transitions to happen faster or slower.",
      whatItDoes: "Sets the length of time transition animations play in milliseconds.",
      parameters: [
        { name: "duration", type: "number", meaning: "Transition duration in milliseconds." },
      ],
      example: "overworld.setAnimationDuration(500)",
    },
    {
      slug: "set-animation-timing-function",
      title: "overworld set animation timing function",
      blockId: "overworld_setAnimationTimingFunction",
      blockString: "overworld set animation timing function $func",
      group: "Animation",
      weight: 80,
      problem: "You want room transition animations to ease smoothly rather than moving at a flat speed.",
      whatItDoes: "Sets the mathematical easing curve used during screen transition animations.",
      parameters: [
        { name: "func", type: "TimingFunction", meaning: "The timing/easing function (e.g. Linear, EaseIn, EaseOut)." },
      ],
      example: "overworld.setAnimationTimingFunction(overworld.TimingFunction.EaseInOut)",
    },
    {
      slug: "set-animation-fade-color",
      title: "overworld set animation custom fade color",
      blockId: "overworld_setAnimationFadeColor",
      blockString: "overworld set animation custom fade color $color",
      group: "Animation",
      weight: 70,
      problem: "You want room transitions to fade through a custom color like red for a volcano dungeon or blue for water.",
      whatItDoes: "Sets the hex color used when the animation type is set to FadeToColor.",
      parameters: [
        { name: "color", type: "string", default: "#000000", meaning: "Hex color code string (e.g., #ff0000)." },
      ],
      example: `overworld.setAnimationType(overworld.AnimationType.FadeToColor)
overworld.setAnimationFadeColor("#ff0000")`,
    },
    {
      slug: "set-scroll-animation-z",
      title: "overworld set scroll animation z",
      blockId: "overworld_setScrollAnimationZIndex",
      blockString: "overworld set scroll animation z $z",
      group: "Animation",
      weight: 70,
      problem: "You want HUD elements or game UI text to stay visible on top while rooms scroll beneath them.",
      whatItDoes: "Sets the Z-depth rendering priority of the room scroll transition effect.",
      parameters: [
        { name: "z", type: "number", default: "99", meaning: "Z-index value for the scroll animation layer." },
      ],
      example: "overworld.setScrollAnimationZIndex(90)",
    },
    {
      slug: "set-overworld-transitions-enabled",
      title: "set overworld transitions enabled",
      blockId: "overworld_setMapTransitionsEnabled",
      blockString: "set overworld transitions enabled $enabled",
      group: "Options",
      weight: 100,
      problem: "You want to trap the player in a boss arena room until they defeat all enemies.",
      whatItDoes: "Enables or disables automatic map transitions when hitting screen boundaries.",
      parameters: [
        { name: "enabled", type: "boolean", meaning: "Set true to enable map transitions, false to lock current map." },
      ],
      example: "overworld.setMapTransitionsEnabled(false)",
    },
    {
      slug: "set-overworld-transition-radius",
      title: "set overworld transition radius",
      blockId: "overworld_setMapTransitionRadius",
      blockString: "set overworld transition radius $radius",
      group: "Options",
      weight: 90,
      problem: "You want map switching to trigger closer to or further from physical screen edges.",
      whatItDoes: "Sets the distance in pixels from map borders where player movement triggers a room change.",
      parameters: [
        { name: "radius", type: "number", meaning: "Distance in pixels from map edges to trigger transitions." },
      ],
      example: "overworld.setMapTransitionRadius(8)",
    },
    {
      slug: "set-walls-block-map-transitions",
      title: "set walls block map transitions",
      blockId: "overworld_setWallsBlockTransitions",
      blockString: "set walls block map transitions $blockEnabled",
      group: "Options",
      weight: 80,
      problem: "You want to prevent players from transitioning into a new room if the entry spot in that room is blocked by solid wall tiles.",
      whatItDoes: "Configures whether wall collisions in the destination room prevent room transition.",
      parameters: [
        { name: "blockEnabled", type: "boolean", meaning: "Set true so solid walls block entering adjacent maps." },
      ],
      example: "overworld.setWallsBlockTransitions(true)",
    },
    {
      slug: "set-continuous-mode-enabled",
      title: "set continuous mode enabled",
      blockId: "overworld_setContinuousModeEnabled",
      blockString: "set continuous mode enabled $enabled",
      group: "Options",
      weight: 70,
      problem: "You want all your smaller room tilemaps stitched into one giant, seamlessly scrolling world map.",
      whatItDoes: "Combines all grid tilemaps into one seamless giant map. Requires all tilemaps to have matching dimensions and tile sizes.",
      parameters: [
        { name: "enabled", type: "boolean", meaning: "Set true to enable seamless continuous tilemap mode." },
      ],
      example: "overworld.setContinuousModeEnabled(true)",
    },
    {
      slug: "create-map-16",
      title: "create map 16",
      blockId: "overworld_createMap16",
      blockString: "$row0 $row1 $row2|| $row3 $row4 $row5",
      group: "Shadows",
      weight: 0,
      problem: "You need to build a 2D matrix layout of 16x16 tilemaps for your overworld definition.",
      whatItDoes: "Helper function combining up to six 16x16 tilemap row arrays into a 2D overworld map matrix.",
      parameters: [
        { name: "row0", type: "tiles.TileMapData[]", meaning: "First row of 16x16 tilemaps." },
        { name: "row1", type: "tiles.TileMapData[]", meaning: "Second row of 16x16 tilemaps." },
        { name: "row2", type: "tiles.TileMapData[]", meaning: "Third row of 16x16 tilemaps." },
        { name: "row3", type: "tiles.TileMapData[]", meaning: "Optional fourth row of 16x16 tilemaps." },
        { name: "row4", type: "tiles.TileMapData[]", meaning: "Optional fifth row of 16x16 tilemaps." },
        { name: "row5", type: "tiles.TileMapData[]", meaning: "Optional sixth row of 16x16 tilemaps." },
      ],
      returns: { type: "tiles.TileMapData[][]", meaning: "A 2D array matrix of tilemap data." },
      example: `let row = overworld.mapRow16(tilemap\`room1\`, tilemap\`room2\`)
let mapGrid = overworld.createMap16(row, row, row)`,
    },
    {
      slug: "create-map-8",
      title: "create map 8",
      blockId: "overworld_createMap8",
      blockString: "$row0 $row1 $row2|| $row3 $row4 $row5",
      group: "Shadows",
      weight: 0,
      problem: "You need to create a 2D matrix grid using rows of 8x8 tilemaps.",
      whatItDoes: "Helper function combining up to six 8x8 tilemap row arrays into a 2D overworld map matrix.",
      parameters: [
        { name: "row0", type: "tiles.TileMapData[]", meaning: "First row of 8x8 tilemaps." },
        { name: "row1", type: "tiles.TileMapData[]", meaning: "Second row of 8x8 tilemaps." },
        { name: "row2", type: "tiles.TileMapData[]", meaning: "Third row of 8x8 tilemaps." },
        { name: "row3", type: "tiles.TileMapData[]", meaning: "Optional fourth row of 8x8 tilemaps." },
        { name: "row4", type: "tiles.TileMapData[]", meaning: "Optional fifth row of 8x8 tilemaps." },
        { name: "row5", type: "tiles.TileMapData[]", meaning: "Optional sixth row of 8x8 tilemaps." },
      ],
      returns: { type: "tiles.TileMapData[][]", meaning: "A 2D array matrix of 8x8 tilemap data." },
      example: `let row = overworld.mapRow8(tilemap\`room1\`, tilemap\`room2\`)
let mapGrid = overworld.createMap8(row, row, row)`,
    },
    {
      slug: "map-row-16",
      title: "map row 16",
      blockId: "overworld_mapRow16",
      blockString: "$map0 $map1 $map2|| $map3 $map4 $map5",
      group: "Shadows",
      weight: 0,
      problem: "You want to assemble individual 16x16 tilemap rooms horizontally into a row.",
      whatItDoes: "Groups up to six 16x16 tilemaps into a single row array.",
      parameters: [
        { name: "map0", type: "tiles.TileMapData", meaning: "First 16x16 tilemap in the row." },
        { name: "map1", type: "tiles.TileMapData", meaning: "Second 16x16 tilemap in the row." },
        { name: "map2", type: "tiles.TileMapData", meaning: "Third 16x16 tilemap in the row." },
        { name: "map3", type: "tiles.TileMapData", meaning: "Optional fourth 16x16 tilemap." },
        { name: "map4", type: "tiles.TileMapData", meaning: "Optional fifth 16x16 tilemap." },
        { name: "map5", type: "tiles.TileMapData", meaning: "Optional sixth 16x16 tilemap." },
      ],
      returns: { type: "tiles.TileMapData[]", meaning: "An array of 16x16 tilemaps." },
      example: "let row = overworld.mapRow16(tilemap`room1`, tilemap`room2`, tilemap`room3`)",
    },
    {
      slug: "map-row-8",
      title: "map row 8",
      blockId: "overworld_mapRow8",
      blockString: "$map0 $map1 $map2|| $map3 $map4 $map5",
      group: "Shadows",
      weight: 0,
      problem: "You want to assemble individual 8x8 tilemaps horizontally into a row array.",
      whatItDoes: "Groups up to six 8x8 tilemaps into a single row array.",
      parameters: [
        { name: "map0", type: "tiles.TileMapData", meaning: "First 8x8 tilemap in the row." },
        { name: "map1", type: "tiles.TileMapData", meaning: "Second 8x8 tilemap in the row." },
        { name: "map2", type: "tiles.TileMapData", meaning: "Third 8x8 tilemap in the row." },
        { name: "map3", type: "tiles.TileMapData", meaning: "Optional fourth 8x8 tilemap." },
        { name: "map4", type: "tiles.TileMapData", meaning: "Optional fifth 8x8 tilemap." },
        { name: "map5", type: "tiles.TileMapData", meaning: "Optional sixth 8x8 tilemap." },
      ],
      returns: { type: "tiles.TileMapData[]", meaning: "An array of 8x8 tilemaps." },
      example: "let row = overworld.mapRow8(tilemap`room1`, tilemap`room2`, tilemap`room3`)",
    },
    {
      slug: "tilemap-8",
      title: "8 tilemap",
      blockId: "overworld_tilemap8",
      blockString: "8 $tilemap",
      group: "Tilemaps",
      weight: 49,
      problem: "You want to tag a tilemap block as an 8x8 pixel tilemap.",
      whatItDoes: "Passes through a TileMapData object formatted for 8x8 pixel tiles.",
      parameters: [
        { name: "tilemap", type: "tiles.TileMapData", meaning: "The 8x8 tilemap data." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The tilemap object." },
      example: "let m = overworld.tilemap8(tilemap`map1`)",
    },
    {
      slug: "tilemap-16",
      title: "16 tilemap",
      blockId: "overworld_tilemap16",
      blockString: "16 $tilemap",
      group: "Tilemaps",
      weight: 49,
      problem: "You want to tag a tilemap block as a standard 16x16 pixel tilemap.",
      whatItDoes: "Passes through a TileMapData object formatted for 16x16 pixel tiles.",
      parameters: [
        { name: "tilemap", type: "tiles.TileMapData", meaning: "The 16x16 tilemap data." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The tilemap object." },
      example: "let m = overworld.tilemap16(tilemap`map1`)",
    }
  ],
};
