import type { ExtensionDoc } from "@/content/extensions/types";

export const arcadeOverworld: ExtensionDoc = {
  owner: "riknoll",
  repo: "arcade-overworld",
  displayName: "Arcade Overworld",
  packageSlug: "github:riknoll/arcade-overworld",
  description: "Create large, Zelda-style multi-screen worlds or seamlessly connected continuous maps in MakeCode Arcade.",
  tools: [
    {
      slug: "set-overworld-16",
      title: "set overworld",
      blockId: "overworld_setOverworld16",
      blockString: "set overworld $maps",
      group: "Create",
      weight: 100,
      problem: "You want to build a sprawling adventure game with a grid of connected 16x16 tilemaps that players can explore room by room.",
      whatItDoes: "Sets the 2D grid of 16x16 tilemaps that make up your overworld. It stores the layout but does not load a map automatically until you call loadMap.",
      parameters: [
        { name: "maps", type: "tiles.TileMapData[][]", meaning: "A 2D array representing rows and columns of 16x16 tilemaps." },
      ],
      example: `overworld.setOverworld16([
    [tilemap\`level1\`, tilemap\`level2\`]
])
overworld.loadMap(0, 0)`,
    },
    {
      slug: "set-overworld-8",
      title: "set overworld",
      blockId: "overworld_setOverworld8",
      blockString: "set overworld $maps",
      group: "Create",
      weight: 90,
      problem: "You are making a retro 8-bit game using 8x8 pixel tiles and need to set up a multi-room overworld grid.",
      whatItDoes: "Sets the 2D grid of 8x8 tilemaps that make up your overworld. You will still need to call loadMap to load the starting screen.",
      parameters: [
        { name: "maps", type: "tiles.TileMapData[][]", meaning: "A 2D array representing rows and columns of 8x8 tilemaps." },
      ],
      example: `overworld.setOverworld8([
    [tilemap\`level1\`, tilemap\`level2\`]
])
overworld.loadMap(0, 0)`,
    },
    {
      slug: "set-player-sprite",
      title: "set player sprite",
      blockId: "overworld_setPlayerSprite",
      blockString: "set player sprite $sprite",
      group: "Create",
      weight: 80,
      problem: "You want the game to automatically switch to the next room whenever your main character walks off the edge of the screen.",
      whatItDoes: "Designates a sprite as the main player tracked by the overworld system. When this sprite reaches the boundary of the current map, adjacent maps load automatically.",
      parameters: [
        { name: "sprite", type: "Sprite", default: "mySprite", meaning: "The hero or player sprite to track for edge-of-screen transitions." },
      ],
      example: `let hero = sprites.create(img\`.\`, SpriteKind.Player)
controller.moveSprite(hero)
overworld.setPlayerSprite(hero)`,
    },
    {
      slug: "current-location",
      title: "overworld location",
      blockId: "overworld_currentLocation",
      blockString: "overworld location $property",
      group: "Load",
      weight: 100,
      problem: "You want to display the player's grid coordinates on a minimap or check if they are in the boss room.",
      whatItDoes: "Returns the current grid coordinate (either the column or the row) of the actively loaded tilemap.",
      parameters: [
        { name: "property", type: "LocationProperty", meaning: "Whether to get the Column (X) or Row (Y) grid index." },
      ],
      returns: { type: "number", meaning: "The zero-based column or row index of the current room." },
      example: `let col = overworld.currentLocation(overworld.LocationProperty.Column)
let row = overworld.currentLocation(overworld.LocationProperty.Row)`,
    },
    {
      slug: "load-map",
      title: "load overworld map at col row",
      blockId: "overworld_loadMap",
      blockString: "load overworld map at col $column row $row",
      group: "Load",
      weight: 90,
      problem: "You want to warp the player to a secret room, teleport them across the kingdom, or initialize the first room at game start.",
      whatItDoes: "Loads the tilemap located at the specified column and row in your overworld grid and moves the camera there. This does nothing if continuous mode is active.",
      parameters: [
        { name: "column", type: "number", meaning: "The column index (horizontal position) of the map to load." },
        { name: "row", type: "number", meaning: "The row index (vertical position) of the map to load." },
      ],
      example: "overworld.loadMap(0, 1)",
    },
    {
      slug: "load-map-in-direction",
      title: "load overworld map in direction",
      blockId: "overworld_loadMapInDirection",
      blockString: "load overworld map in direction $direction",
      group: "Load",
      weight: 80,
      problem: "You stepped on an arrow button or reached an exit trigger and want to force the camera to move to the neighboring screen.",
      whatItDoes: "Loads the adjacent tilemap located in the specified direction relative to the current map. Does nothing if continuous mode is enabled or if no map exists there.",
      parameters: [
        { name: "direction", type: "CollisionDirection", meaning: "The direction (Top, Right, Bottom, Left) of the room to switch to." },
      ],
      example: "overworld.loadMapInDirection(CollisionDirection.Right)",
    },
    {
      slug: "get-map-at",
      title: "get overworld map at col row",
      blockId: "overworld_getMapAt",
      blockString: "get overworld map at col $column row $row",
      group: "Load",
      weight: 70,
      problem: "You want to inspect tiles or place objects into a specific room's tilemap before the player actually walks into it.",
      whatItDoes: "Fetches the tilemap data stored at the given column and row in your overworld grid. Returns undefined if the coordinate is out of bounds.",
      parameters: [
        { name: "column", type: "number", meaning: "The column index of the tilemap." },
        { name: "row", type: "number", meaning: "The row index of the tilemap." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The tilemap data at that coordinate, or undefined if none exists." },
      example: "let roomMap = overworld.getMapAt(1, 0)",
    },
    {
      slug: "get-map-in-direction",
      title: "get overworld map in direction",
      blockId: "overworld_getMapInDirection",
      blockString: "get overworld map in direction $direction",
      group: "Load",
      weight: 60,
      problem: "You want to preview what kind of terrain is in the room ahead to see if it is safe to enter.",
      whatItDoes: "Returns the tilemap data for the adjacent map in the specified direction. Returns undefined if you are at the edge of the world.",
      parameters: [
        { name: "direction", type: "CollisionDirection", meaning: "The direction to look (Top, Right, Bottom, Left)." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The neighboring tilemap data, or undefined if none exists." },
      example: "let nextMap = overworld.getMapInDirection(CollisionDirection.Top)",
    },
    {
      slug: "map-exists-at",
      title: "overworld map exists at col row",
      blockId: "overworld_mapExistsAt",
      blockString: "overworld map exists at col $column row $row",
      group: "Load",
      weight: 50,
      problem: "You are generating random quests and need to verify whether a particular coordinate in your overworld grid has a room or is empty space.",
      whatItDoes: "Checks if a tilemap is defined at the specified column and row coordinates.",
      parameters: [
        { name: "column", type: "number", meaning: "The column coordinate to check." },
        { name: "row", type: "number", meaning: "The row coordinate to check." },
      ],
      returns: { type: "boolean", meaning: "true if a tilemap exists at that grid position, false otherwise." },
      example: `if (overworld.mapExistsAt(2, 2)) {
    overworld.loadMap(2, 2)
}`,
    },
    {
      slug: "map-exists-in-direction",
      title: "overworld map exists in direction",
      blockId: "overworld_mapExistsInDirection",
      blockString: "overworld map exists in direction $direction",
      group: "Load",
      weight: 40,
      problem: "You want to prevent your player from trying to cross an edge if there is no room beyond it.",
      whatItDoes: "Returns true if there is a valid tilemap in the specified direction from the current room, or false if the player has reached the outer boundary.",
      parameters: [
        { name: "direction", type: "CollisionDirection", meaning: "The direction (Top, Right, Bottom, Left) to check." },
      ],
      returns: { type: "boolean", meaning: "true if an adjacent map exists in that direction, false otherwise." },
      example: `if (overworld.mapExistsInDirection(CollisionDirection.Right)) {
    overworld.loadMapInDirection(CollisionDirection.Right)
}`,
    },
    {
      slug: "on-map-loaded",
      title: "on map loaded",
      blockId: "overworld_onMapLoaded",
      blockString: "on map loaded at $overworldColumn $overworldRow $map",
      group: "Load",
      weight: 30,
      problem: "You need to spawn enemies, place treasure chests, and clear out old monsters whenever the player enters a new room.",
      whatItDoes: "Runs an event callback every time a new tilemap is loaded. In continuous mode, it triggers whenever the player crosses into a new room's boundary.",
      parameters: [
        { name: "handler", type: "(overworldColumn: number, overworldRow: number, map: tiles.TileMapData) => void", meaning: "The code to run when a room loads, receiving the column, row, and tilemap data." },
      ],
      example: `overworld.onMapLoaded(function (overworldColumn, overworldRow, map) {
    sprites.destroyAllSpritesOfKind(SpriteKind.Enemy)
    let enemy = sprites.create(img\`.\`, SpriteKind.Enemy)
})`,
    },
    {
      slug: "set-animation-type",
      title: "overworld set animation type",
      blockId: "overworld_setAnimationType",
      blockString: "overworld set animation type $animationType",
      group: "Animation",
      weight: 100,
      problem: "You want room transitions to look smooth and polished like classic dungeon games with sliding cameras or screen fades.",
      whatItDoes: "Sets the transition visual effect used when moving between tilemaps (None, Scroll, FadeToWhite, FadeToBlack, or FadeToColor). Does nothing in continuous mode.",
      parameters: [
        { name: "animationType", type: "AnimationType", meaning: "The animation style to use for screen changes." },
      ],
      example: "overworld.setAnimationType(overworld.AnimationType.Scroll)",
    },
    {
      slug: "set-animation-duration",
      title: "overworld set animation duration",
      blockId: "overworld_setAnimationDuration",
      blockString: "overworld set animation duration $duration",
      group: "Animation",
      weight: 90,
      problem: "You feel room scrolling is too fast or too slow and want to adjust how long the transition animation takes.",
      whatItDoes: "Configures how many milliseconds the room transition animation lasts. Does nothing in continuous mode or when animation type is None.",
      parameters: [
        { name: "duration", type: "number", meaning: "Transition length in milliseconds (e.g. 500 for half a second)." },
      ],
      example: "overworld.setAnimationDuration(400)",
    },
    {
      slug: "set-animation-timing-function",
      title: "overworld set animation timing function",
      blockId: "overworld_setAnimationTimingFunction",
      blockString: "overworld set animation timing function $func",
      group: "Animation",
      weight: 80,
      problem: "You want your room transitions to accelerate smoothly or ease out rather than moving at a constant speed.",
      whatItDoes: "Sets the easing curve used for transitions, controlling whether the animation eases in, eases out, or moves linearly.",
      parameters: [
        { name: "func", type: "TimingFunction", meaning: "The easing function to apply to room transitions." },
      ],
      example: "overworld.setAnimationTimingFunction(overworld.TimingFunction.EaseInOut)",
    },
    {
      slug: "set-animation-fade-color",
      title: "overworld set animation custom fade color",
      blockId: "overworld_setAnimationFadeColor",
      blockString: "overworld set animation custom fade color $color",
      group: "Animation",
      weight: 70,
      problem: "You are making a spooky game or lava dungeon and want room transitions to fade to deep red or purple instead of standard black.",
      whatItDoes: "Sets the custom color used when the animation type is set to FadeToColor. Colors are given as hexadecimal strings (e.g. \"#ff0000\").",
      parameters: [
        { name: "color", type: "string", default: "#000000", meaning: "The hex color string to fade through (e.g. \"#ff0000\")." },
      ],
      example: `overworld.setAnimationType(overworld.AnimationType.FadeToColor)
overworld.setAnimationFadeColor("#ff0000")`,
    },
    {
      slug: "set-scroll-animation-z-index",
      title: "overworld set scroll animation z",
      blockId: "overworld_setScrollAnimationZIndex",
      blockString: "overworld set scroll animation z $z",
      group: "Animation",
      weight: 70,
      problem: "Your custom UI elements or dialog boxes are getting scrolled away during room transitions instead of staying fixed on screen.",
      whatItDoes: "Sets the render layer (Z-index) for the scrolling animation. Any sprite or renderable with a higher Z-index will remain visible on top of the scrolling screens.",
      parameters: [
        { name: "z", type: "number", default: "99", meaning: "The Z-index layer for the scroll transition (default is 99)." },
      ],
      example: "overworld.setScrollAnimationZIndex(99)",
    },
    {
      slug: "set-map-transitions-enabled",
      title: "set overworld transitions enabled",
      blockId: "overworld_setMapTransitionsEnabled",
      blockString: "set overworld transitions enabled $enabled",
      group: "Options",
      weight: 100,
      problem: "You are in the middle of a boss fight or dialogue cutscene and need to temporarily stop the player from leaving the current room.",
      whatItDoes: "Enables or disables automatic map transitions when the player hits the screen edges.",
      parameters: [
        { name: "enabled", type: "boolean", meaning: "True to allow room transitions, false to lock the player in the current map." },
      ],
      example: "overworld.setMapTransitionsEnabled(false)",
    },
    {
      slug: "set-map-transition-radius",
      title: "set overworld transition radius",
      blockId: "overworld_setMapTransitionRadius",
      blockString: "set overworld transition radius $radius",
      group: "Options",
      weight: 90,
      problem: "The player is triggering room transitions too early before actually reaching the boundary, or they get stuck at the edge.",
      whatItDoes: "Sets the distance in pixels from the map edge at which moving toward the border triggers a transition to the next room.",
      parameters: [
        { name: "radius", type: "number", meaning: "Distance in pixels from the screen boundary required to trigger a room change." },
      ],
      example: "overworld.setMapTransitionRadius(6)",
    },
    {
      slug: "set-walls-block-transitions",
      title: "set walls block map transitions",
      blockId: "overworld_setWallsBlockTransitions",
      blockString: "set walls block map transitions $blockEnabled",
      group: "Options",
      weight: 80,
      problem: "Your player accidentally moves into a new room and ends up trapped inside a solid wall tile.",
      whatItDoes: "When enabled, prevents the player from transitioning into an adjacent map if the destination entry point is blocked by wall tiles.",
      parameters: [
        { name: "blockEnabled", type: "boolean", meaning: "True to block transitions into obstructed spaces, false to allow the transition and nudge the player to open space." },
      ],
      example: "overworld.setWallsBlockTransitions(true)",
    },
    {
      slug: "set-continuous-mode-enabled",
      title: "set continuous mode enabled",
      blockId: "overworld_setContinuousModeEnabled",
      blockString: "set continuous mode enabled $enabled",
      group: "Options",
      weight: 70,
      problem: "You want one gigantic seamless open world where the camera follows the player smoothly instead of snapping between separate screens.",
      whatItDoes: "Stitches all tilemaps in the overworld grid into one giant combined tilemap. Requires all maps to have identical dimensions and tile scale.",
      parameters: [
        { name: "enabled", type: "boolean", meaning: "True to stitch tilemaps into one large seamless world, false for room-by-room mode." },
      ],
      example: "overworld.setContinuousModeEnabled(true)",
    },
    {
      slug: "create-map-16",
      title: "create map 16",
      blockId: "overworld_createMap16",
      blockString: "$row0 $row1 $row2|| $row3 $row4 $row5",
      group: "Shadows",
      weight: 0,
      problem: "You are organizing multiple rows of 16x16 tilemaps into a full world grid inside the block editor.",
      whatItDoes: "Assembles multiple rows of 16x16 tilemaps into a 2D tilemap grid. This is a helper block primarily used in the MakeCode block workspace.",
      parameters: [
        { name: "row0", type: "tiles.TileMapData[]", meaning: "First row of 16x16 tilemaps." },
        { name: "row1", type: "tiles.TileMapData[]", meaning: "Second row of 16x16 tilemaps." },
        { name: "row2", type: "tiles.TileMapData[]", meaning: "Third row of 16x16 tilemaps." },
        { name: "row3", type: "tiles.TileMapData[]", meaning: "Optional fourth row of tilemaps." },
        { name: "row4", type: "tiles.TileMapData[]", meaning: "Optional fifth row of tilemaps." },
        { name: "row5", type: "tiles.TileMapData[]", meaning: "Optional sixth row of tilemaps." },
      ],
      returns: { type: "tiles.TileMapData[][]", meaning: "A 2D array of tilemaps ready for setOverworld16." },
      example: `let grid = overworld.createMap16(
    [tilemap\`map1\`, tilemap\`map2\`],
    [tilemap\`map3\`, tilemap\`map4\`],
    []
)
overworld.setOverworld16(grid)`,
    },
    {
      slug: "create-map-8",
      title: "create map 8",
      blockId: "overworld_createMap8",
      blockString: "$row0 $row1 $row2|| $row3 $row4 $row5",
      group: "Shadows",
      weight: 0,
      problem: "You are organizing multiple rows of 8x8 tilemaps into a full world grid inside the block editor.",
      whatItDoes: "Assembles multiple rows of 8x8 tilemaps into a 2D tilemap grid. This is a helper block primarily used in the MakeCode block workspace.",
      parameters: [
        { name: "row0", type: "tiles.TileMapData[]", meaning: "First row of 8x8 tilemaps." },
        { name: "row1", type: "tiles.TileMapData[]", meaning: "Second row of 8x8 tilemaps." },
        { name: "row2", type: "tiles.TileMapData[]", meaning: "Third row of 8x8 tilemaps." },
        { name: "row3", type: "tiles.TileMapData[]", meaning: "Optional fourth row of tilemaps." },
        { name: "row4", type: "tiles.TileMapData[]", meaning: "Optional fifth row of tilemaps." },
        { name: "row5", type: "tiles.TileMapData[]", meaning: "Optional sixth row of tilemaps." },
      ],
      returns: { type: "tiles.TileMapData[][]", meaning: "A 2D array of tilemaps ready for setOverworld8." },
      example: `let grid = overworld.createMap8(
    [tilemap\`map1\`, tilemap\`map2\`],
    [tilemap\`map3\`, tilemap\`map4\`],
    []
)
overworld.setOverworld8(grid)`,
    },
    {
      slug: "map-row-16",
      title: "map row 16",
      blockId: "overworld_mapRow16",
      blockString: "$map0 $map1 $map2|| $map3 $map4 $map5",
      group: "Shadows",
      weight: 0,
      problem: "You are building a row of horizontal rooms using 16x16 tilemaps inside the block workspace.",
      whatItDoes: "Combines up to 6 individual 16x16 tilemaps into a single horizontal row for the overworld grid.",
      parameters: [
        { name: "map0", type: "tiles.TileMapData", meaning: "First tilemap in the row." },
        { name: "map1", type: "tiles.TileMapData", meaning: "Second tilemap in the row." },
        { name: "map2", type: "tiles.TileMapData", meaning: "Third tilemap in the row." },
        { name: "map3", type: "tiles.TileMapData", meaning: "Optional fourth tilemap." },
        { name: "map4", type: "tiles.TileMapData", meaning: "Optional fifth tilemap." },
        { name: "map5", type: "tiles.TileMapData", meaning: "Optional sixth tilemap." },
      ],
      returns: { type: "tiles.TileMapData[]", meaning: "An array of tilemaps representing a single row in the overworld grid." },
      example: "let row = overworld.mapRow16(tilemap`room1`, tilemap`room2`, tilemap`room3`)",
    },
    {
      slug: "map-row-8",
      title: "map row 8",
      blockId: "overworld_mapRow8",
      blockString: "$map0 $map1 $map2|| $map3 $map4 $map5",
      group: "Shadows",
      weight: 0,
      problem: "You are building a row of horizontal rooms using 8x8 tilemaps inside the block workspace.",
      whatItDoes: "Combines up to 6 individual 8x8 tilemaps into a single horizontal row for the overworld grid.",
      parameters: [
        { name: "map0", type: "tiles.TileMapData", meaning: "First tilemap in the row." },
        { name: "map1", type: "tiles.TileMapData", meaning: "Second tilemap in the row." },
        { name: "map2", type: "tiles.TileMapData", meaning: "Third tilemap in the row." },
        { name: "map3", type: "tiles.TileMapData", meaning: "Optional fourth tilemap." },
        { name: "map4", type: "tiles.TileMapData", meaning: "Optional fifth tilemap." },
        { name: "map5", type: "tiles.TileMapData", meaning: "Optional sixth tilemap." },
      ],
      returns: { type: "tiles.TileMapData[]", meaning: "An array of tilemaps representing a single row in the overworld grid." },
      example: "let row = overworld.mapRow8(tilemap`room1`, tilemap`room2`, tilemap`room3`)",
    },
    {
      slug: "tilemap-8",
      title: "8 tilemap",
      blockId: "overworld_tilemap8",
      blockString: "8 $tilemap",
      group: "Tilemaps",
      weight: 49,
      problem: "You want to create and edit an 8x8 pixel tilemap directly inside an overworld row block.",
      whatItDoes: "Provides an 8x8 tilemap editor field within overworld construction blocks. Returns the tilemap data passed to it.",
      parameters: [
        { name: "tilemap", type: "tiles.TileMapData", meaning: "The 8x8 tilemap data." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The provided 8x8 tilemap data." },
      example: "let map = overworld.tilemap8(tilemap`level1`)",
    },
    {
      slug: "tilemap-16",
      title: "16 tilemap",
      blockId: "overworld_tilemap16",
      blockString: "16 $tilemap",
      group: "Tilemaps",
      weight: 49,
      problem: "You want to create and edit a standard 16x16 pixel tilemap directly inside an overworld row block.",
      whatItDoes: "Provides a 16x16 tilemap editor field within overworld construction blocks. Returns the tilemap data passed to it.",
      parameters: [
        { name: "tilemap", type: "tiles.TileMapData", meaning: "The 16x16 tilemap data." },
      ],
      returns: { type: "tiles.TileMapData", meaning: "The provided 16x16 tilemap data." },
      example: "let map = overworld.tilemap16(tilemap`level1`)",
    }
  ],
};
